### ISSUE TITLE
not feeding, and will it accept http proxy?

### ISSUE THREAD

**Issue by Octolus** [davidmann4/ogar-feeder-bot#101]
For some reason it's not feeding me, i don't see any bots at all tbh

`
[root@agar agario-feeder-bot-master]# node server/server.js
Starting server on port 80
User connected with id:YOUR_UUID
User connected with id:undefined
User connected with id:9c00
{ name: 'connect_server', ip: 'ws://151.80.96.59:1506' }
User connected with id:undefined
User connected with id:9c00
{ name: 'connect_server', ip: 'ws://151.80.98.73:1508' }

User connected with id:9c00
{ name: 'connect_server', ip: 'ws://151.80.98.73:1508' }
`

**Comment by Octolus** [comment]
i am alone in my server too in ogar.

**Comment by WJKH** [comment]
Get your ID and put it in config file.

**Comment by Octolus** [comment]
ID? Username? or the actual ID in game

**Comment by Octolus** [comment]
Got it, however.. http://i.imgur.com/BM0ZQ0B.gifv

not feeding me, it's not following my user or cursor at all @WJKH

**Comment by Octolus** [comment]
its like they are going into a corner http://i.imgur.com/elRug7i.png

**Comment by hamido12** [comment]
hey pliz help me how to install this

**Comment by WJKH** [comment]
config.client_uuid = "YOUR_UUID"; // after you install the userscript it will show you a UUID in the corner

**Comment by Octolus** [comment]
@WJKH  yeh solved it but it's not appearing my uid whatsoever :)
