### ISSUE TITLE
Do SOCKS4 & SOCKS5 proxies work with your bot?

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#102]
Do socks proxies work?

Edit: yes, the bot supports SOCKS4 SOCKS5 and HTTP proxies - there are different sections for them in the https://github.com/davidmann4/agario-feeder-bot/blob/master/proxy.sample.txt file

**Comment by Octolus** [comment]
Try?

I tried HTTP, however 90% of them was getting 403/500.

@davidmann4 does it keep re-trying the proxies that doesnt work? would be nice if the app would remove ones that don't connect / 403 by it self..

**Comment by WJKH** [comment]
@AmazingGamerBoy No, do you forget https://github.com/davidmann4/agario-feeder-bot/issues/41?

@techpulse I believe it's not something that a feeder bot should handle, you can use an external script or even better don't use public proxys.

**Comment by davidmann4** [comment]
yes,  check

https://github.com/davidmann4/agario-feeder-bot/blob/master/proxy.sample.txt
