### ISSUE TITLE
UserScript Problem

### ISSUE THREAD

**Issue by mhchen-UA** [davidmann4/ogar-feeder-bot#103]
So I correctly booted up the server. On node.js command prompt, it says:

agario-feeeder-bot started! Join a game in Chrome with the userscript installed.
startup
server-booted-up

But in chrome, i don't see any interfaces about the bots' status. I could only zoom out further.

**Comment by MarkDsonYT** [comment]
Actually, if I delete that line (or change it to a comment), there are many other lines that have an Illegal return statement.

**Comment by Octolus** [comment]
yeah same

**Comment by WJKH** [comment]
Did you get your ID and put it in config file?

**Comment by Octolus** [comment]
yes, using Chrome

**Comment by WJKH** [comment]
Did you change the IP:PORT in the userscript?

**Comment by loboere** [comment]
iqual ,I don't show bots either

**Comment by Octolus** [comment]
@WJKH  yes since bots are connecting

**Comment by WJKH** [comment]
Well, I don't know what is the issue here.

F12 and check browser console, any warning/error there?
Where are bots going?
Do you have the last version of all files?

**Comment by Octolus** [comment]
in public servers they work fine, but in Ogar they go straight into a corner

**Comment by WJKH** [comment]
Oh.. you must have started saying that.
Then, it's some issue with Ogar and @davidmann4 should check it to see what happen there.

**Comment by mhchen-UA** [comment]
Is ID the social idea, or the UUid?

**Comment by WJKH** [comment]
UUID

**Comment by davidmann4** [comment]
press F12 and take the uuid

I just made an update so it writes "this is your id : " before it was just a ID like 5EG7

**Comment by mhchen-UA** [comment]
Okay so I made progress. The servers runs fine. I used 127.0.0.1  as my local host, and changed something into this `var socket = io.connect('ws://127.0.0.1:8081');`   in the userscript. Now when I open 2 command prompts and `node feeder` and `node server`  Both of them seem to work fine. But whenever I join in agar.io, there's no bots coming to me.   When i stop the server with ctrl+c on the command prompt, the console on chrome says it has ERR:Connection refused so I know the server is working perfectly fine. I set the bots to 28. Do you want me to record another video to show you what i"m doing and see what I did wrong?

**Comment by davidmann4** [comment]
do oyu see bots joining your server? why you run your own feeder server? kinda advance way to do it

**Comment by mhchen-UA** [comment]
really? So var socket = io.connect(  Do I manually put the ws server in this place?  );     and   config.FeederServer as well?     Also fyi, I didn't change the proxy.txt at all except renaming it to proxy.

**Comment by davidmann4** [comment]
https://www.youtube.com/watch?v=FVNNo93ZVGg

just made a tutorial maybe it helps

**Comment by mhchen-UA** [comment]
Davidmann you are awesome. When you put in your proxies, do I put in 127.0.0.1:8081 instead?   If I do, do I have to do anything extra like node server.js ?  I got 3 bots by copying the proxies you entered.

**Comment by mhchen-UA** [comment]
actually no, I'll just use the server instead :D I'll see if that works

**Comment by davidmann4** [comment]
you will need proxies - yes
