### ISSUE TITLE
Bad lagging

### ISSUE THREAD

**Issue by Octolus** [davidmann4/ogar-feeder-bot#104]
I've hosted Ogar server on same server, and there is no noticeable lag. However once I use the feeder bot, on public Ogar servers or my own it's lagging horribly.

The feeder bot server is a Dedicated high end server, also tried on Digital Ocean and other providers. It's like lagging the entire game when i am trying to play?

Basically what's lagging is the game, so when i try to move cursor my cell sometimes stays the same position, once i disable the feeder it works fine.

**Comment by davidmann4** [comment]
lol, how many bots did you used ?

**Comment by Octolus** [comment]
Around 3. The thing is, it lags in my browser (where I use the userscript).. So i dont see why its making me lag

**Comment by davidmann4** [comment]
wtf, and your home computer is like a good computer? the script sends out commands in a 100ms interval - I do not see a problem here

**Comment by Octolus** [comment]
I think so? :P http://i.imgur.com/cep3UM0.png

**Comment by davidmann4** [comment]
puh strange a 4790k should handle this with ease ... ( got the same in my rig)

**Comment by Octolus** [comment]
Could it have anything about the latency to the remote server? I mean, shouldn't. I can play fine using my own custom Ogar server, on same server..

**Comment by davidmann4** [comment]
no should be no issue 

also you just run 3 bots

**Comment by Octolus** [comment]
tried again, noticed no issue.. eh idk what to say
