### ISSUE TITLE
Cant seem to install package.json

### ISSUE THREAD

**Issue by GOpb** [davidmann4/ogar-feeder-bot#105]
when i run npm install package.json this comes up

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'package.json' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData package.json
8 silly fetchOtherPackageData package.json
9 silly cache add args [ 'package.json', null ]
10 verbose cache add spec package.json
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'package.json',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'package.json',
11 silly cache add   spec: '/Users/guthriepurinton-brown/agario-feeder-bot/package.json',
11 silly cache add   type: 'local' }
12 silly addLocalTarball shasum (computed) 75c2d1187af452dd460494c21a389431a6364e63
13 verbose addTmpTarball /Users/guthriepurinton-brown/agario-feeder-bot/package.json not in flight; adding
14 verbose addTmpTarball validating metadata from /Users/guthriepurinton-brown/agario-feeder-bot/package.json
15 verbose tar unpack /Users/guthriepurinton-brown/agario-feeder-bot/package.json
16 verbose tar unpacking to /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06
17 silly gentlyRm /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06 is being purged
18 verbose gentlyRm don't care about contents; nuking /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06
19 silly gunzTarPerm modes [ '755', '644' ]
20 error not a package /Users/guthriepurinton-brown/agario-feeder-bot/package.json
21 error addLocal Could not install /Users/guthriepurinton-brown/agario-feeder-bot/package.json
22 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json'
22 silly fetchPackageMetaData     at Error (native)
22 silly fetchPackageMetaData  error for package.json { [Error: ENOENT: no such file or directory, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json']
22 silly fetchPackageMetaData   errno: -2,
22 silly fetchPackageMetaData   code: 'ENOENT',
22 silly fetchPackageMetaData   syscall: 'open',
22 silly fetchPackageMetaData   path: '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Starting
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: ENOENT: no such file or directory, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json'
28 verbose stack     at Error (native)
29 verbose cwd /Users/guthriepurinton-brown/agario-feeder-bot
30 error Darwin 14.0.0
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "package.json"
32 error node v5.5.0
33 error npm  v3.3.12
34 error path /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json
35 error code ENOENT
36 error errno -2
37 error syscall open
38 error enoent ENOENT: no such file or directory, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12400-5d339398/unpack-5bcffb9f9346732efe1d43cde6ae5c06/package.json'
38 error enoent This is most likely not a problem with npm itself
38 error enoent and is related to npm not being able to find a file.
39 verbose exit [ -2, true ]

**Comment by GOpb** [comment]
help

**Comment by GOpb** [comment]
this happend

Guthries-MacBook-Pro-2:~ guthriepurinton-brown$ npm install /Users/guthriepurinton-brown/agario-feeder-bot/package.json 
npm ERR! not a package /Users/guthriepurinton-brown/agario-feeder-bot/package.json
npm ERR! addLocal Could not install /Users/guthriepurinton-brown/agario-feeder-bot/package.json
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "/Users/guthriepurinton-brown/agario-feeder-bot/package.json"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! path /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12580-e77e1bd8/unpack-28788ba07c57983538817d16aa50c26e/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-12580-e77e1bd8/unpack-28788ba07c57983538817d16aa50c26e/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guthriepurinton-brown/npm-debug.log
Guthries-MacBook-Pro-2:~ guthriepurinton-brown$

**Comment by Octolus** [comment]
cd into the dir with the agar feeder.js etc

then npm install package.json

thats what i did

or

npm install -g package.json

**Comment by GOpb** [comment]
ok thx

**Comment by GOpb** [comment]
Guthries-MacBook-Pro-2:~ guthriepurinton-brown$ cd agario-feeder-bot
Guthries-MacBook-Pro-2:agario-feeder-bot guthriepurinton-brown$ npm install -g package.json
npm ERR! not a package /Users/guthriepurinton-brown/agario-feeder-bot/package.json
npm ERR! addLocal Could not install /Users/guthriepurinton-brown/agario-feeder-bot/package.json
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "package.json"
npm ERR! node v0.10.32
npm ERR! npm  v3.6.0
npm ERR! path /var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-13790-ed10e0d5/unpack-599c23a4/package.json
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-13790-ed10e0d5/unpack-599c23a4/package.json'
npm ERR! enoent ENOENT, open '/var/folders/95/t3hy9zbj0vg4p6c4py0th2m80000gn/T/npm-13790-ed10e0d5/unpack-599c23a4/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guthriepurinton-brown/agario-feeder-bot/npm-debug.log
Guthries-MacBook-Pro-2:agario-feeder-bot guthriepurinton-brown$

**Comment by GOpb** [comment]
this happend

**Comment by davidmann4** [comment]
git pull and check again

**Comment by GOpb** [comment]
it says permission denied

**Comment by davidmann4** [comment]
i made a tutorial video for windows:
https://www.youtube.com/watch?v=FVNNo93ZVGg

**Comment by makandz** [comment]
@davidmann4 Old post, might want to close :D
