### ISSUE TITLE
error agarioclient

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#106]
agario-feeder-bot started! Join a game in Chrome with the Userscript
startup
server-booted-up
{ name: 'connect_server', ip: 'ws://167.114.172.220:1507' }
client requested bots on: ws://167.114.172.220:1507
Auth_Token: null
http://NOPROXY
Attempting connection to ws://167.114.172.220:1507
Error occured on startup: TypeError: AgarioClient is not a function
http://181.111.177.115:8080
Attempting connection to ws://167.114.172.220:1507
Error occured on startup: TypeError: AgarioClient is not a function
http://190.52.32.126:80
Attempting connection to ws://167.114.172.220:1507
Error occured on startup: TypeError: AgarioClient is not a function

**Comment by davidmann4** [comment]
hmm funny - did you already managed to fix it? more infos would be helpfull

**Comment by makandz** [comment]
@davidmann4 Inactive post, might want to close :D
