### ISSUE TITLE
help bots do not connect to others private servers

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#109]
just it works on my own server but not in others
servers

**Comment by auxo-git** [comment]
I recall  someone saying something about blocking bots in ogar.. idk something like that.

**Comment by auxo-git** [comment]
Make sure your using proxies as they could've limited max connections per ip

**Comment by davidmann4** [comment]
any error msgs?

**Comment by mhchen-UA** [comment]
auxo is right, using proxies I could only get 3 bots each.
