### ISSUE TITLE
Error disconnected from the server

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#112]
after a while my bot stops and leaves the server

**Comment by akaashjain1** [comment]
same here  :(

**Comment by mhchen-UA** [comment]
It's because the proxies you're using limits it. I think it's 3 bots (clients) per proxy that are allowed to go on one server. So you need a bunch of proxies that aren't blocked by agar.io

**Comment by akaashjain1** [comment]
@MarkDsonYT  please can you suggest some proxies to use. i cant find any working ones

**Comment by mhchen-UA** [comment]
Well it's hard for me to find ones too. I think agar.io blocked some of them too. I used to use browsec, but now browsec doesn't even work. What did is google "free http proxies" or "http proxy list"  and find ones in North America that works. I found these two, one of them should work:

**Comment by mhchen-UA** [comment]
163.44.119.72
104.131.19.173

**Comment by makandz** [comment]
@davidmann4 Close request? xD

**Comment by agarioBotDev** [comment]
@akaashjain1 agar.io blocked 99% of the public proxies - if you want working proxies host them.

**Comment by akaashjain1** [comment]
how do we host them? @agarioBotDev

**Comment by makandz** [comment]
OpenVPN @akaashjain1

**Comment by akaashjain1** [comment]
gimme a tutorial @MastaCoder

**Comment by makandz** [comment]
@akaashjain1 Linux or Windows?

**Comment by akaashjain1** [comment]
windows @MastaCoder

**Comment by makandz** [comment]
http://lmgtfy.com/?q=how+to+install+openvpn+on+windows

@akaashjain1 Proxy is something that requires multiple IP's. If you are going to do this on your home computer, you're out of luck.

**Comment by mhchen-UA** [comment]
ACtually here's a better way that sonicmaster does: 
1. Go here for a list of proxies http://vip-socks24.blogspot.com/2016/02/14-02-16-vip-socks-5-servers-1530.html
2. Go here to check which proxies work http://www.checker.freeproxy.ru/checker/  
3. After that, copy and paste all that proxies in your file and boom you have like 63 of them or something at least.

**Comment by WJKH** [comment]
The problem with public socks/proxies is almost all are blocked from public servers, others are very slow or will cause any connection/network issue.

If you want it totally free, then you haven't another choice than run bots at home with public socks/proxies. You will get some bots what is good, but doesn't complain about issues or try to get too many bots.

If you can afford spend some money, then you can buy proxies or even better rent a VPS with some IPs to run your own proxy. This is much better and much cheaper than websites selling bots. For example 50 bots will cost something like as $20-$30 per month.

**Comment by makandz** [comment]
@WJKH +1
