### ISSUE TITLE
npm install package.json

### ISSUE THREAD

**Issue by issy123** [davidmann4/ogar-feeder-bot#114]
If you run the shell script: "npm install package.json"

It assumes that "package.json" is an package and searches for "package.json" module.

But what you want to do is install all dependencies that the package.json file contains.

So please use "npm install" in your instructions (it will search for dependencies in package.json). And let them know the bulletpoints are indeed instructions.

**Comment by NotSoSuper** [comment]
I don't see it state anywhere to do "npm install package.json" so either it was fixed or you did something wrong? I saw your pull request merged so I assume you fixed it already.
This should be closed.

**Comment by issy123** [comment]
Yes I fixed it, I thought why not pull request
