### ISSUE TITLE
Make bot split upon pressing key

### ISSUE THREAD

**Issue by custoso** [davidmann4/ogar-feeder-bot#12]
Make the bot split and feed, upon pressing a button.

**Comment by AgarioCheats** [comment]
The agar minimap feeds when holding Q. Q has javascript charcode 81, but I can't find it in the agar-minimap.js userscript file? "case 81" or something similar. Wheres that part?

For e to split bots, i assume this needs to be done
Client:
Minimap needs to fetch E pressed. (keycode 69)
this.pressE = false;
  case 69:
            // E pressed
            this.pressE = true;
      
            break;


Server sided:

case 128:
bot.client.split()

**Comment by custoso** [comment]
The agar minimap feeds when holding Q. Q has javascript charcode 81, but I can't find it in the agar-minimap.js userscript file? "case 81" or something similar. Wheres that part?

For e to split bots, i assume this needs to be done
Client:
Minimap needs to fetch E pressed. (keycode 69)
this.pressE = false;
  case 69:
            // E pressed
            this.pressE = true;

```
        break;
```

Server sided:

case 128:
bot.client.split()

**Comment by camilleeyries** [comment]
ok...

**Comment by clouedoc** [comment]
we need to create our own userscript before...

**Comment by clouedoc** [comment]
without msgpack :D

**Comment by davidmann4** [comment]
msgpack is great - it saves a lot of traffic @dimotsai made a great job with https://github.com/dimotsai/agar-mini-map

**Comment by clouedoc** [comment]
We need to use node 0.12 with msgpack... 

Envoyé de mon iPhone

**Comment by AgarioCheats** [comment]
Wouldn't it be possible to use case X with agar-minimap? To fetch keys pressed

**Comment by davidmann4** [comment]
case X ?

**Comment by AgarioCheats** [comment]
case 69 for example to fetch E pressed

**Comment by davidmann4** [comment]
ahh ok yeah sure we could improve the map server - I really think that the whole follow the mouse thing is overrated ...

**Comment by AgarioCheats** [comment]
It's cool as it is now! But if the bots follow the mouse, then other cool stuff can be done such as Play in spectator mode, spawn as one of the bots when pressing e (split bot) and also split master cell into bot / bot into master cell

**Comment by davidmann4** [comment]
ahh got it

**Comment by dimotsai** [comment]
@camilleeyries msgpack-node has been updated for node v4. Please check this out: https://github.com/pgriess/node-msgpack/issues/63. I haven't updated the dependency.

**Comment by davidmann4** [comment]
done in the newest version
