### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#122]
You should add so it says in the userscript how many bots are connected and shift button/fast split. And make it able to connect multiple facebook accounts

**Comment by Octolus** [comment]
+1

**Comment by MasonBurdette** [comment]
shift button/fast split can be easily done on the userscript.
(my modified version has it :D)

**Comment by Petterholm** [comment]
Can you send it?#

**Comment by MasonBurdette** [comment]
skype?

**Comment by makandz** [comment]
@MasonBurdette It would be great if you can make a pull request on it so everyone can have it xD
