### ISSUE TITLE
would it be possible to use a chrome extention in this service you are providing for proxies

### ISSUE THREAD

**Issue by akaashjain1** [davidmann4/ogar-feeder-bot#124]
would it be possible to use a chrome extention in this service you are providing for proxies, the chrome extension is from browse sec heres the code

davidmann4 censorship: REMOVED COPY PASTA (reason: unlicensed code)

**Comment by davidmann4** [comment]
are you publishing unlicensed code as an issue? 

whats wrong with you people. show a little respect to people who worked on something.
