### ISSUE TITLE
Bots connecting slow?

### ISSUE THREAD

**Issue by Octolus** [davidmann4/ogar-feeder-bot#125]
I used a nodejs proxy checker, that would check for certain word on agario with the proxies, then if that word was there it would add it to valid.txt

Now, i have over 500 proxies that works with agario however when using the bot on a dedicated server or a vps, i only see 2-3 connecting at a time.. So slow, why this? On YouTube videos, i see 100's at once flooding you.

if someone could help me out i'd be able to provide a lot of proxies :)

**Comment by Octolus** [comment]
If one proxy connects slow, or errors - does that slow down other ones as well? like they wait in a que.

**Comment by MasonBurdette** [comment]
i use http://www.checker.freeproxy.ru/checker/ to see which proxies work.

**Comment by makandz** [comment]
@MasonBurdette +1

**Comment by davidmann4** [comment]
faster proxies & config.js settings should do the trick
