### ISSUE TITLE
How can i make it all automated just like raga.pw and agrbot.ovh???

### ISSUE THREAD

**Issue by mayed505** [davidmann4/ogar-feeder-bot#127]
How can i make it all automated just like raga.pw and agrbot.ovh???
Im starting like them soon and is it possible to the uuid all automated and time expire?
Maybe we can work together?

**Comment by mbm3** [comment]
instead of doing uuid try doing ip-based access

EDIT:
also try using npm agario-client to code your own bots

**Comment by davidmann4** [comment]
This is about ogar servers
