### ISSUE TITLE
Make Feeder.js server-side

### ISSUE THREAD

**Issue by mbm3** [davidmann4/ogar-feeder-bot#128]
making feeder.js would be better, so the only thing running on your computer is the userscript

**Comment by WJKH** [comment]
It's server side, you run it on your computer because you haven't a server.

**Comment by mbm3** [comment]
so could i run it on my ovh server?  how would it point to a different server?

**Comment by WJKH** [comment]
Same way as you run it on your machine.

**Comment by mbm3** [comment]
nvm im just working on my own bot script now... :P
