### ISSUE TITLE
Willing to pay a substantial amount for this to be automated

### ISSUE THREAD

**Issue by Niko454** [davidmann4/ogar-feeder-bot#129]
Hi! If I can get your email or some sort of contact information I'm willing to pay a substantial amount of money to get this thing automated. Sorry for submitting this as an issue. As it appears this is the only way to contact you. Let me know!

**Comment by MasonBurdette** [comment]
whats your skype.

**Comment by davidmann4** [comment]
if you add features please contribute it back to the repository

**Comment by davidmann4** [comment]
my skype is: david.mann.rsa

**Comment by Niko454** [comment]
My skype is: siliconvalley46
Great. :D

**Comment by Niko454** [comment]
Still waiting for a reply from you guys! Just let me know!

**Comment by MasonBurdette** [comment]
@Niko454 I'll be back on today soon.  Looking forward to work with you.

**Comment by Niko454** [comment]
@MasonBurdette Alright great then :+1:

**Comment by DeepSnowNeeL** [comment]
It pays well so be sure to ask for a % ;)

**Comment by MasonBurdette** [comment]
@DeepSnowNeeL we worked it out, thanks :)

**Comment by Niko454** [comment]
Yep. We did. Closing this now.
