### ISSUE TITLE
how can i connect the bots to fb so they spawn bigger. 

### ISSUE THREAD

**Issue by akaashjain1** [davidmann4/ogar-feeder-bot#130]
want the bots to spawn with my Facebook starting mass

**Comment by MasonBurdette** [comment]
agario limited 1 IP per FaceBook, per party server.
(meaning that isnt possible anymore, unless you have MANY fb accounts)

**Comment by Petterholm** [comment]
i have alot of fb accounts how can i connect all of them

**Comment by MasonBurdette** [comment]
this script wouldn't support that unless you heavily modify it.

but, you can make your own using https://github.com/pulviscriptor/agario-client
and make a token generator for all of them. (its simpler than it sounds)

**Comment by akaashjain1** [comment]
but why do i see other bots the size of facebook starting mass. this is from agariobots.ovh

there are loads of them the size of fb starting mass.

**Comment by MasonBurdette** [comment]
@akaashjain1 you are correct.  also whenever someone uses agarbot.ovh it stores their facebook data.

**Comment by akaashjain1** [comment]
can someone make a script that will make the bots the size of Facebook starting mass. it would be really grateful if you do so.

**Comment by makandz** [comment]
@MasonBurdette Wait they do?! The more you know :D

**Comment by MasonBurdette** [comment]
@MastaCoder look at http://agarbot.ovh/tos.php.
its listed, but a privacy concern for some xD

**Comment by davidmann4** [comment]
ogar has no fb login
