### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by WJKH** [davidmann4/ogar-feeder-bot#133]
**VPS Configuration**
Ubuntu 15.10 Server 64-Bit
CPU: 2 vCPU
RAM: 4 GB

Testing 162 bots:

```
root@GS:~# ps -C node -o %cpu,%mem,cmd
%CPU %MEM CMD
 0.5  3.3 node server.js
99.3 21.2 node feeder.js
```

**Comment by MasonBurdette** [comment]
thats odd, i have a 2gb ovh server, and it never uses more than 60%

**Comment by KingMatt123** [comment]
@WJKH How on earth did you get a vncserver setup on ubuntu 15.10?

**Comment by WJKH** [comment]
@MasonBurdette I'm not talking about RAM, I'm talking about CPU usage (99.3%).
Did you checked the CPU usage?

**Comment by makandz** [comment]
It's node. Node.js is absolutely sh*t when it comes to considering ram and CPU leaks. To run the script, trying using JXCore, it is multi threaded, much better with ram and such.

Install it and run scripts just like node, but instead use jx, so jx feeder.js. I'll test it to see if it's working with the bots and update this if I don't forget xD

**Comment by WJKH** [comment]
Yes, I know.
Now I'm running 60 bots per process, then if I want 180 bots I need run 3 process and it's a bit better.

I will try JX later and post result here.

**Comment by makandz** [comment]
Wait I just tested this out with node, I don't see where the issue is. I am running this script right now like this:

1 vCore server with 512mb of ram
Running the server also on my own VPS (not using davids public one)
And running just above 60% CPU usage.

That's not much for the crappy VPS I have right now. (I'm running with Node.js, not JXCore)

**Comment by WJKH** [comment]
As far as I know, 1 or 4 cores is the same as node.js isn't multithreading.
How many bots did you run?

**Comment by makandz** [comment]
I did some playing around, around 100 active bots, about 30~% of CPU is used. Over 400 and I get serious lag and I break into my swap for ram.

**Comment by WJKH** [comment]
Tried 250 bots and get lagged badly.
Now if I run five process with 50 bots each, no issues.

Perhaps, we could implement a master process that run child process every X bots.

@MastaCoder did you try JXCore? Is it working with the same code?

**Comment by makandz** [comment]
Yeah it works. I haven't tried it yet on a server with more than 1 core yet.

**Comment by MasonBurdette** [comment]
@WJKH yea, for now I just run a few instances.

**Comment by WJKH** [comment]
Tried JXCore, it's not lagged with one process using 4 cores.
Anyway I think node.js and multiple process give best performance.

I'm running 50 bots per process in my system, but the bots amount to run per process could be configured at config.js

**Comment by davidmann4** [comment]
yeah it does a lot of calculations ... run it on good hw fixes the problem for most of the people
