### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#134]
Guys, i can see that this program can use http/socks4/socks5 but can it support https as well? so then it would support http/https/socks4/socks5?

**Comment by WJKH** [comment]
Why don't try before to ask?

**Comment by KingMatt123** [comment]
Just tried it, doesn't work, gives me errors, could someone confirm this please?

**Comment by davidmann4** [comment]
Should work as http proxies are https proxies - i think the current bersion has just a bug with http proxies

**Comment by DOMJx** [comment]
@davidmann4 i get getaddrinfo even in my Private Server

**Comment by davidmann4** [comment]
hmm works for me - maybe try socks4 or socks5 - if you provide more infos we can reopen the issue
