### ISSUE TITLE
Which Operating System should i get?

### ISSUE THREAD

**Issue by DOMJx** [davidmann4/ogar-feeder-bot#136]
Well, im trying to get a VPS for my bots but the problem is Windows Os is more expensive than Archlinux, Ubuntus, Centos so which one should i get?

**Comment by WJKH** [comment]
Any linux, Ubuntu for example.

**Comment by DOMJx** [comment]
i installed Fedora, does it works?

**Comment by WJKH** [comment]
Yes, of course.

**Comment by DOMJx** [comment]
WJKH u have ur proxies working? im trying to get my bots to work but is like a bug or a glitch, but only my first 2 bots join then bot 3,4... send me Unexpected Server Responde or getaddrinfo happens with every proxy only the first proxy work.

**Comment by DOMJx** [comment]
@WJKH if u help me with this i can run the bots for u.

**Comment by WJKH** [comment]
You need good proxy, forget public proxy.
Buy private proxy or get some server with enough IPs and run your own proxy.

**Comment by DOMJx** [comment]
GG,but private proxies are more expensive than the vps. Thanks for the help

**Comment by WJKH** [comment]
Then get a VPS with 20-30 IPs
