### ISSUE TITLE
Some problem with npm...

### ISSUE THREAD

**Issue by clouedoc** [davidmann4/ogar-feeder-bot#14]
Hello ! Can you send me a zip with your node_module folder and agar minimap builded ? I have some problem with npm and msgpack...

_thanks........._

**Comment by custoso** [comment]
Use node version 0.12 -> It solved issues. Spent like 10 hours to find out the node version caused the problems.

**Comment by clouedoc** [comment]
THANK YOU YOU ARE A GOD !!!
