### ISSUE TITLE
Connection Failed: Error: getaddrinfo ENOTFOUND 8080 8080:80

### ISSUE THREAD

**Issue by Nick8fr32** [davidmann4/ogar-feeder-bot#140]
Bot_1: Connection Failed: Error: getaddrinfo ENOTFOUND 8080 8080:80
i know the proxy work. what do i do to fix this

**Comment by DOMJx** [comment]
I have the same problem only first proxy connects.

**Comment by easyrider81** [comment]
Same for me. Same Error type.

**Comment by davidmann4** [comment]
still a thing? someone commited a patch

**Comment by Nick8fr32** [comment]
where can i get the patch ?????????

**Comment by makandz** [comment]
@Nick8fr32 Download the latest version of the feeder bot.

**Comment by davidmann4** [comment]
fixed in actual version
