### ISSUE TITLE
Bot Amount

### ISSUE THREAD

**Issue by mbm3** [davidmann4/ogar-feeder-bot#142]
I'm working on my own version of this script, but how would I send the variable "bot_count" through socket.io-client to the client script, so it could be displayed.  This question is mainly related to socket.io.  Any help would be great.

**Comment by gcsoftware** [comment]
I'm working to implement this and will submit a pull request when it's complete. You can then see how it was done.

**Comment by mbm3** [comment]
@gcsoftware Thank you.
