### ISSUE TITLE
Facebook login!

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#145]
hey, i will pay real money if someone can make the script to allow me to add multiple facebook and google accounts.
Remember it have to be easy so i dont have to log into every account every 3 hours. if possible i want so i can just write in the email and password :)

**Comment by Petterholm** [comment]
add me on skype petter.holm11

**Comment by MasonBurdette** [comment]
When I get home I'll add you.  I have a multiple account system that supports however many accounts you have!

**Comment by Petterholm** [comment]
Ok how much?

Den mandag 8. februar 2016 skrev Mason Burdette notifications@github.com
følgende:

**Comment by Petterholm** [comment]
@MasonBurdette hey i havent heard from you yet

**Comment by Petterholm** [comment]
@MasonBurdette you have still not added me... if anyone else has a system so i can connect multiple facebook accounts add me on skype petter.holm11

**Comment by Petterholm** [comment]
@MasonBurdette when will u add me?
