### ISSUE TITLE
I used 1000 proxies on agar feeder but when i play i only received 3 or 7 bots.

### ISSUE THREAD

**Issue by ThunderDoug** [davidmann4/ogar-feeder-bot#147]
Anyone can help me ? pls add me on skype facebook:douglas.pereiradasilveira

**Comment by makandz** [comment]
Then only 3 - 7 proxies actually work?

**Comment by ThunderDoug** [comment]
Wtf but i checked all proxies i'm using and all are working :(

**Comment by makandz** [comment]
Yeah I have the same issue too. Either Agar.io have blocked those proxies, or the proxy can't work with the feeder bot.

**Comment by ThunderDoug** [comment]
yeh

**Comment by ThunderDoug** [comment]
only david can help us

**Comment by ThunderDoug** [comment]
Look at this pic http://prntscr.com/a0sijj

**Comment by WJKH** [comment]
You're funny guys, 1k proxy? WTF?
Then... 1000*3=3000 bots?

Stop it, find good proxy and doesn't complain if the bots aren't working with public/low quality proxy.

**Comment by makandz** [comment]
@WJKH +1

**Comment by davidmann4** [comment]
Do not use the bots on official servers
