### ISSUE TITLE
 Userscript should provide a STOP (D) button so I can just control the bots

### ISSUE THREAD

**Issue by mayed505** [davidmann4/ogar-feeder-bot#148]
Hello Everyone i have this cool idea for the script :+1: 
If u press Letter D ur cell stops at its cords just like agarbot.ovh!
so u can control ur bots as if u were teaming with the bot feeding you!
Would be seriously useful!

**Comment by MasonBurdette** [comment]
This is basically #87

**Comment by mayed505** [comment]
@MasonBurdette its not......

**Comment by MasonBurdette** [comment]
@mayed505 explain.  i may have read you issue incorrectly. to me it looks the same.

**Comment by WJKH** [comment]
@MasonBurdette it's not the same, he's talking about stop ball movement.

**Comment by MasonBurdette** [comment]
@WJKH ah i see

**Comment by mayed505** [comment]
@WJKH  and @MasonBurdette  Yeah :D

**Comment by gcsoftware** [comment]
Will be implementing this shortly :smiley:

**Comment by WJKH** [comment]
@gcsoftware nice, thanks!

**Comment by gcsoftware** [comment]
@mayed505 @WJKH @MasonBurdette Fulfilled :grin:

**Comment by MasonBurdette** [comment]
@davidmann4 Needs closed, gcsoftware has made a pull request implementing this.

**Comment by mayed505** [comment]
Closed
