### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by luqueruben** [davidmann4/ogar-feeder-bot#150]
This is my actual config: http://i.imgur.com/2BpkvXn.png
server stay in "server-booted-up"
and not run

**Comment by gcsoftware** [comment]
You can fix this by running the server locally on the same machine. Edit the userscript with your local ip:8081

**Comment by davidmann4** [comment]
you need to install the user script and join a game

**Comment by luqueruben** [comment]
yes, i install the user script, and i have open my ogar private server

**Comment by davidmann4** [comment]
any error msgs on th econsole ? chrome or firefox? any changes on the userscript?

**Comment by luqueruben** [comment]
to test, i put in userscript " var socket = io.connect('ws://127.0.0.1:8081');" , to test in localhost, and run the server, and then run the feeder.js , but in the feeder.js "startup and server-booted-up"
and in the server put "User connected with id: cb83"

**Comment by gcsoftware** [comment]
Run feeder and server on same machine. If userscript is running on a different machine but same network make sure to put the private IP such as "192.168.x.x" or "10.x.x.x" instead of 127.0.0.1.

**Comment by makandz** [comment]
The server running socket.io isn't connecting with each other or running. I had the same issue, it was because I forgot to change the IP in the userscript :D

**Comment by luqueruben** [comment]
i put in the userscript my private IP and nothing...
https://i.imgur.com/bA9CAHK.png
EDIT: I try the update of MastaCoder , and run the server ...but the bots can not connect:

http://i.imgur.com/Inwniac.png

**Comment by gcsoftware** [comment]
Now you need proxies that aren't dead / low quality.

**Comment by luqueruben** [comment]
and all free proxys have low quality ??

**Comment by gcsoftware** [comment]
Some are flat out blocked from agar.io so you can try using another list. If your using free lists it's best you get one that is within the last 48 hrs, and not one that's a week old etc.

**Comment by makandz** [comment]
Just buy some, the cheapest I found that is quite good quality is around $0.50 per proxy.

**Comment by luqueruben** [comment]
ok,I found a forum where daily updated proxies ... Still not connect more than 5 bots me, although in the counter put 50 bots connected :| 
Photo: http://i.imgur.com/0UGLRpm.png

**Comment by gcsoftware** [comment]
If your using the public server, you will need to wait for the latest fix to take care of invalid counter.

**Comment by davidmann4** [comment]
i updated the public server

**Comment by gcsoftware** [comment]
@davidmann4 Nvm. Seems you got it taken care of.
