### ISSUE TITLE
Attach event

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#157]
Can someone attach this? : 
bot.on('packetError', function(packet, err, preventCrash) {
   bot.log('Packet error detected for packet: ' + packet.toString());
   bot.log('Crash will be prevented, bot will be disconnected');
   preventCrash();
   bot.disconnect();
});

**Comment by mbm3** [comment]
oh yea this needs implemented.

**Comment by WJKH** [comment]
@Petterholm can you reply @pulviscriptor at https://github.com/pulviscriptor/agario-client/issues/73

He's going to fix it if you help and there's no many people getting your error, then maybe you could help a bit there.

Thanks.

**Comment by makandz** [comment]
Damn it, could have added this to the pull request I just made.

**Comment by pulviscriptor** [comment]
@WJKH 
Source of crash is bugged SOCKS servers that sends garbage randomly (most probably). 
Check my investigation https://github.com/pulviscriptor/agario-client/issues/56#issuecomment-171772427
Anyway i can't do anything with damaged packet when i receive it so my fix was adding `packetError` event.

**Comment by davidmann4** [comment]
Alteady added it
