### ISSUE TITLE
Press button to toggle between bots following mouse and player.

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#159]
I'm not sure if this has been added yet, but could u add a toggle that when a button is pressed the bots change from moving from the mouse point, to the player, and vice versa? so i can get the bots to follow the my ball instead of my mouse if i want? thx

**Comment by gcsoftware** [comment]
I will look into this..

**Comment by makandz** [comment]
@gcsoftware :+1:

**Comment by gcsoftware** [comment]
Submitted for pull request #163 !

**Comment by davidmann4** [comment]
merged - so this is resolved
