### ISSUE TITLE
Fix MAX bot on party (598/128) bots

### ISSUE THREAD

**Issue by SrNicolas** [davidmann4/ogar-feeder-bot#161]

**Comment by makandz** [comment]
Wait what?

**Comment by SrNicolas** [comment]
i get that amount of bots when the max amount of bots is 128

https://gyazo.com/82894d4699e6113c4d65e2cc5e7ef7d7

https://gyazo.com/160f2a1fa64c567b13415513869d3b84

**Comment by quuuuuuu** [comment]
@SrNicolas can sent me the Bot starts GUI

**Comment by makandz** [comment]
That happens when the server hasn't been restarted. That is a bug I am working on, it's a bit glitch so far.

**Comment by gcsoftware** [comment]
@MastaCoder  @SrNicolas Will have this fixed soon.

**Comment by SrNicolas** [comment]
Actually @MastaCoder its not a glitch i get that amount of bots, the problem is that it doesnt sstop at 128, it just still connecting bots

**Comment by makandz** [comment]
@SrNicolas Fixed it in my update.

**Comment by davidmann4** [comment]
fixed in lastest pull request
