### ISSUE TITLE
Bot Count acts random using the public feeder server.

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#165]
![image](https://cloud.githubusercontent.com/assets/1736570/12989033/bfc8ffd4-d103-11e5-9a5b-67b56e925a24.png)
@gcsoftware can you make it work on the public server aswell? 

more people are connected and it should just return the one value which affects the correct player

**Comment by gcsoftware** [comment]
I will try to take care of this when I can. Thanks for letting me know :+1:

**Comment by WJKH** [comment]
Something similar happens when you run multiple instances of feeder to avoid issue https://github.com/davidmann4/agario-feeder-bot/issues/133
