### ISSUE TITLE
Facebook bots?

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#169]
Is there any way to make bots ruin trough my facebook acc ?

**Comment by pantshobhit** [comment]
Hii, I too am experiencing the same problem and hope someone will help me. When I use access token as auth. I still get the warning for all the three cookies (developer says they get overwritten, but they dont) and login doesnt work. When I use the cookie method there is no warning and all my ips connect to the server but none of the bots spawn (gives me an error), keeps on connecting and disconnecting, please please resolve my problem that will be very nice.

**Comment by WJKH** [comment]
1 FB Account = 1 Bot
2 FB Account = 2 Bot
...

And feeder isn't ready to handle more than one account yet.

**Comment by pantshobhit** [comment]
wjkh i am getting neither of the fb as well as non fb bots

**Comment by WJKH** [comment]
@pantshobhit I haven't tested it recently because I could connect one bot (I have one FB account). Anyway in the past it wasn't working properly (I was doing the auth step manually) and maybe @davidmann4 could check it and confirm if it's working or not.

**Comment by davidmann4** [comment]
ogar does not uses fb login
