### ISSUE TITLE
Bots auto join agario server, reconnect and join a new server when player changes server.

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#176]
When I have about half of my bots loaded into a game, then I change agar server, it says in server concole that bots have disconnected from original server but they do not join the new one automatically. I think this is already coded in the script but it doesn't work well for me, or not even at all. Maybe this thing could be recoded and more stable?

**Comment by KingMatt123** [comment]
They connect to the old server again though so none go to the new one

**Comment by davidmann4** [comment]
please only use on ogar servers
