### ISSUE TITLE
Facebook bots

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#177]
hey, i will pay real money if someone can make the script to allow me to add multiple facebook and google accounts.
Remember it have to be easy so i dont have to log into every account every 3 hours. if possible i want so i can just write in the email and password :)

**Comment by WJKH** [comment]
I believe before to make something like it, you need bots avoid others players or you will feed everyone and it's useless.

**Comment by davidmann4** [comment]
ogar does not have fb support
