### ISSUE TITLE
How to make a feeder server?

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#178]
I want to make my own feeder server for the bots. How

**Comment by WJKH** [comment]
Just run server.js

**Comment by ravyn120** [comment]
k

**Comment by Veykiou** [comment]
How I can run this server.js file ?

**Comment by Nick8fr32** [comment]
Just open console on the _server_ folder and then 
**node server.js**

**Comment by rle-im** [comment]
It's says: Error: Cannot find module 'socket.io'

**Comment by ItzLevvie** [comment]
Have you even installed the dependencies? ^^
