### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by xa** [davidmann4/ogar-feeder-bot#179]
Userscript doesn't work on firefox.
Will provide more details if required.

**Comment by xa** [comment]
This error comes up when userscript is installed.

TypeError: window.setGameMode is not a function

**Comment by xa** [comment]
When I changed
var isFirefox = /Firefox/.test(navigator.userAgent)
to
var isFirefox = false;

Game now runs, but I can't connect to Google account, and there are graphical glitches. (the splash screen flashes)

**Comment by davidmann4** [comment]
install chrome

**Comment by xa** [comment]
I did it and everything works on chrome, but I prefer firefox ui.

**Comment by davidmann4** [comment]
make a pull request or use chrome
