### ISSUE TITLE
Make bot network calculate seed value of Ogar scramble 

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#18]
Ogar uses a protection algorithm called scramble. If we have enough data we should able to calculate the seed values c.borderLeft, c.borderRight , c.borderTop ,  c.borderBottom

``` javascript
 this.scrambleX = Math.floor((1<<15) * Math.random());
 this.scrambleY = Math.floor((1<<15) * Math.random());

this.socket.sendPacket(new Packet.SetBorder(
                        c.borderLeft + this.socket.playerTracker.scrambleX,
                        c.borderRight + this.socket.playerTracker.scrambleX,
                        c.borderTop + this.socket.playerTracker.scrambleY,
                        c.borderBottom + this.socket.playerTracker.scrambleY
                ));
```

**Comment by davidmann4** [comment]
default values are: 

``` bash
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000
```

**Comment by davidmann4** [comment]
possible solution;
bots could have a warm-up phase where they collect food, if they find another bot the following happens:

BOT A makes a snapshot of his position
BOT B also makes a snapshot of BOT A's position on his client

now we can calculate the seed values

another possible solution:
spam move to commands in different ranges until the bot will start moving - so we can get the borders on the map. Now we can compare this values and calculate the base values.

**Comment by Faicu** [comment]
@davidmann4 can you please make a video tutorial with your script please? I'm just not know anything about js node and all things :D

**Comment by MastaCoder** [comment]
@Faicu Off topic, try making a new issue about it :)

**Comment by davidmann4** [comment]
solution: do not crack at all - create a own scramble system based on the start packet

calculate offset to the tracking system

**Comment by davidmann4** [comment]
done
