### ISSUE TITLE
New ReadMe (I didn't know where to post :P)

### ISSUE THREAD

**Issue by DeadWarrior58** [davidmann4/ogar-feeder-bot#180]
Export ZIP file anywhere

Install agario-feeder-bot.user.js to Chrome/Firefox
•Download [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) ([Firefox link](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)) , click it, “Add a new script…”, and copy agario-feeder-bot.user’s code and paste it to tampermonkey. Then save it (The little floppy disk icon)

Change config.sample.js to config.js and adjust values (You can use Wordpad or download [Notepad++](https://notepad-plus-plus.org/download/v6.8.8.html))
• In the config.js, you must assign the UUID to the one generated by the client script you installed above, you can find this by going to agar.io and copying the “UUID” tab ([Example Picture](http://prntscr.com/a3bgpg)) or else press F12 and go to console, it should be there ([Example Picture](http://prntscr.com/a3binr))

Change proxy.sample.txt to proxy.txt and adjust values

Download Node.js

You should also find some proxies. You can buy some or find some free ones (most of them will not work) from website or by scraping programs

**The following part can be skipped by downloading, putting into the bots’ folder and running [this](http://www.mediafire.com/download/p6pnlencb0pcbso/Install.cmd) CMD**

Run a CMD (Windows + R, then type cmd)
Type **cd (Folder Location)**  = For example **cd C:\Users\Admin\Desktop\Bots**
Then type **npm install**
After that install libs, in our case we type **npm install socket.io-client**

Then you are done, just type node feeder.js to run or make/[download](http://www.mediafire.com/download/4chee4arkaovdv7/Put+on+bots+folder.cmd) a cmd to do it

**For DavidMann4**
Pastebin with the raw text : http://pastebin.com/F0f4tUXe

**Comment by mbm3** [comment]
this should be a pull request...

**Comment by hassanila** [comment]
I also just made a pull request without seeing this... We can maybe combine them...

**Comment by DeadWarrior58** [comment]
@hassanila97 yeah it would be a good idea
Contact me via skype : live:deadwarrior58_1

**Comment by davidmann4** [comment]
puh duplicate with the pull request?
