### ISSUE TITLE
 agar-feeder-bot

### ISSUE THREAD

**Issue by VictorShadow** [davidmann4/ogar-feeder-bot#181]
Hello David could tell me how almentar the mass amount of bots ?
Thanks!

**Comment by Lukkez** [comment]
'almentar' it's what?

**Comment by hassanila** [comment]
Increase in some language, he means increase the bot mass...

**Comment by Lukkez** [comment]
I know, it's portuguese (I'm brazillian and understand) but the correct on portuguese is 'aumentar'
