### ISSUE TITLE
New error after updated files

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#183]
I got this error after i update the files, files should fix (rage error) and they actually fix it but make an new. Help [http://imgur.com/VZyatar](url)

**Comment by MasonBurdette** [comment]
comment line 426 out on WebSocket.js

**Comment by ghost** [comment]
same problem :/

**Comment by ghost** [comment]
haha i already fixed it today

This is what it looks like if its crashing 
Bot_63: Packet error detected for packet: 10 03 00 af 0b 2c 00 07 f5 2b 00 82 9c 2b 00 0a 08 2c 00 cd d3 2b 00 c1 0a 2c 00 82 9c 2b 00 9f 12 00 00 17 13 00 00 27 02 ff 07 f9 00 00 00 17 dd 2b 00 07 15 00 00 d4 15 00 00 7e 01 ff 07 f9 00 00 00 18 dd 2b 00 51 17 00 00 ff 12 00 00 99 00 ff 07 f9 00 00 00 f8 07 2c 00 56 16 00 00 0d 10 00 00 22 02 ff 07 f9 00 00 00 f9 07 2c 00 c5 15 00 00 6f 13 00 00 03 01 08 2c 00 9b 16 00 00 8f 12 00 00 37 00 ff 07 f9 00 00 00 a7 08 2c 00 cb 14 00 00 42 12 00 00 30 00 ff 07 f9 00 00 00 a9 08 2c 00 41 16 00 00 5a 12 00 00 30 00 ff 07 f9 00 00 00 ac 08 2c 00 e6 14 00 00 a0 12 00 00 30 00 ff 07 f9 00 00 00 56 0b 2c 00 4d 12 00 00 ad 15 00 00 25 00 ff 07 f9 20 00 00 00 00 00 00 00 00 00 00 82 7e 01 03 10 06 00 f4 0c 2c 00

**Comment by sejo153** [comment]
MinersMC how u fixed it ?

**Comment by sejo153** [comment]
MasonBurdette can u explain me pls?

**Comment by ghost** [comment]
i modified the code of websocket.js its really simple

**Comment by gamer2331** [comment]
how?

**Comment by bvsxdmodz** [comment]
how?

**Comment by sejo153** [comment]
how pls?

**Comment by hassanila** [comment]
Sorry but how can people be so stupid and ignorants? Don't you read other comments? @MasonBurdette said comment line 426 out on WebSocket.js and it will work wake up people!!!

**Comment by bvsxdmodz** [comment]
http://prntscr.com/a4143s @hassanila97 what should i change lmao ur comment doesnt help at all

**Comment by hassanila** [comment]
I think That line need to be replaced by this: //event.type = 'error';

**Comment by bvsxdmodz** [comment]
http://prntscr.com/a41dek i still get these errors and no bots spawn

**Comment by bvsxdmodz** [comment]
http://prntscr.com/a41heo then i does this and closes the socket

**Comment by hassanila** [comment]
@bvsxdmodz sry but I don't personally know the solution I don't get the error. Better ask someone else... :+1:

**Comment by bvsxdmodz** [comment]
can u send me all ur files in a rar and i can try urs?

**Comment by hassanila** [comment]
Maybe but Wait till I get home... I run Windows btw...
