### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gamer2331** [davidmann4/ogar-feeder-bot#188]
Bot_63: Packet error detected for packet: 10 03 00 af 0b 2c 00 07 f5 2b 00 82 9c 2b 00 0a 08 2c 00 cd d3 2b 00 c1 0a 2c 00 82 9c 2b 00 9f 12 00 00 17 13 00 00 27 02 ff 07 f9 00 00 00 17 dd 2b 00 07 15 00 00 d4 15 00 00 7e 01 ff 07 f9 00 00 00 18 dd 2b 00 51 17 00 00 ff 12 00 00 99 00 ff 07 f9 00 00 00 f8 07 2c 00 56 16 00 00 0d 10 00 00 22 02 ff 07 f9 00 00 00 f9 07 2c 00 c5 15 00 00 6f 13 00 00 03 01 08 2c 00 9b 16 00 00 8f 12 00 00 37 00 ff 07 f9 00 00 00 a7 08 2c 00 cb 14 00 00 42 12 00 00 30 00 ff 07 f9 00 00 00 a9 08 2c 00 41 16 00 00 5a 12 00 00 30 00 ff 07 f9 00 00 00 ac 08 2c 00 e6 14 00 00 a0 12 00 00 30 00 ff 07 f9 00 00 00 56 0b 2c 00 4d 12 00 00 ad 15 00 00 25 00 ff 07 f9 20 00 00 00 00 00 00 00 00 00 00 82 7e 01 03 10 06 00 f4 0c 2c 00 CRASH

**Comment by gamer2331** [comment]
So everytime it crashes i have to type node feeder.js but cant i just fix that?

**Comment by davidmann4** [comment]
ws error - they are working on a patch
