### ISSUE TITLE
Bots have been patched?

### ISSUE THREAD

**Issue by Arkzyy** [davidmann4/ogar-feeder-bot#190]
Have bots been patched? Is this the end? :(

**Comment by ravyn120** [comment]
Well bots work for me but they don't come to me so I think they patched the coordination system or something or changed it

**Comment by Arkzyy** [comment]
They changed mouse cords. I'm trying to make a bypass rn

**Comment by hassanila** [comment]
Hope to see a pull request soon keep up the good work and always open source btw sharing is caring...

**Comment by easyrider81** [comment]
Well there should be some kind of way around it as some of the paid bots sites are still working

**Comment by Nick8fr32** [comment]
yea the clan leader in 《Ƹ̵̡Ӝ̵̨̄Ʒ》 have made a fix to the patch but he dont wont to save it

**Comment by davidmann4** [comment]
https://github.com/davidmann4/agario-feeder-bot/issues/172

**Comment by Lukkez** [comment]
.

**Comment by bvsxdmodz** [comment]
i keep getting error 407 and econnreset in the command window i have added 47 working proxys and still nothing

**Comment by ghost** [comment]
@bvsxdmodz This proxies is crazy, i have same problem more i'm added more proxies  some have workings, use HTTP is more good.

**Comment by RaynerXXX** [comment]
yep

**Comment by bvsxdmodz** [comment]
can u copy ur proxy file and send it to me i wanna try urs and see if it fixes my problem

**Comment by ghost** [comment]
@bvsxdmodz I have a list with 1500 proxies more same work and others no, more is a mix HTTP, HTTPS, SSL, SOCKS4/5 use a proxy checker for know right use.
I am New  the GitHub, have private message? for pass download link for you.
