### ISSUE TITLE
Wrong bot movement.

### ISSUE THREAD

**Issue by xa** [davidmann4/ogar-feeder-bot#194]
Bots don't move in random direction, but all of them move in the same direction, not following the player.

**Comment by Nick8fr32** [comment]
yea its because all clients have diffrent cords

**Comment by xa** [comment]
I thought it was fixed in last update.

**Comment by Nick8fr32** [comment]
nope i dont think so

**Comment by DanielLewis97NL** [comment]
It was fixed, update agario-client module. It works for me on ogar

**Comment by Nick8fr32** [comment]
what about agar.io??

**Comment by davidmann4** [comment]
update user script and script. and confirm that it is not working - console output would be nice

**Comment by xa** [comment]
Deleted whole ogar-feeder directory, updated everything, and it isn't working with agar.io but with ogar works perfectly fine.

**Comment by xa** [comment]
http://pastebin.com/LfLYtjta
