### ISSUE TITLE
raga.pw working again. How did they got it working ?

### ISSUE THREAD

**Issue by picusc** [davidmann4/ogar-feeder-bot#195]
Just wanted to post it here that raga.pw fixed their bots and it is now working again. 

So, there is hope.

http://i.imgur.com/GxGJSTE.png

**Comment by davidmann4** [comment]
link the msg please

**Comment by ItzLevvie** [comment]
https://www.facebook.com/ragahelp/?fref=ts

**Comment by picusc** [comment]
https://www.facebook.com/ragahelp/photos/a.519109208238584.1073741828.513978345418337/590076261141878/

**Comment by issy123** [comment]
I have seen some bots maybe its theirs. Its not a nice fix though. The bots go to the direction as usual, so the bots also moves to random directions. But as soon as one bot detects the player's cell id it goes straight to them.
If the bots I have seen is theirs, than it's just a PR stunt to claim that they decrypted the algorithm. If they really did the bots would follow the mouse as usual and are controlable

Will test the bots tomorrow though

**Comment by WJKH** [comment]
@issy123 even thus their bots work, better than nothing.

**Comment by picusc** [comment]
Their bots are working perfectly. I have tested it. The bots flow directly at your cell and you can't control the bots.

**Comment by DanielLewis97NL** [comment]
@picusc your account is 1 day old, many people on their facebook say bots don't work...

**Comment by issy123** [comment]
@picusc I have tested their bots, the bots only follow your mouse when they can see you. So maybe 50% of those bots are not detected and will never go to you. And when you are split multiple times the bots dont follow your mouse correctly

The bots do work it is an solution but not the best, lose of maybe 50% of your bots and not following your mouse correctly

**Comment by gcsoftware** [comment]
Well since this project has dropped support for agar.io and some of you are interested in a post-patch version.. https://github.com/gcsoftware/gc-feeder

**Comment by davidmann4** [comment]
@gcsoftware most of your commits could also go to this repo - just call it "blind mode" interesting thing to code
