### ISSUE TITLE
Server does not boot up

### ISSUE THREAD

**Issue by jacobduba** [davidmann4/ogar-feeder-bot#196]
The feeder.js file does not say the text: "server booted up." (it also does not work) Here's are the windows I think the error could be in: 
![capture](https://cloud.githubusercontent.com/assets/11655457/13098542/bfbd6eb8-d4ef-11e5-907a-2934632cb233.PNG)

**Comment by ravyn120** [comment]
put port on ur feeder server ip -- 8081 says in server also put it in the user script

**Comment by jacobduba** [comment]
It still does not "boot up" or work.

**Comment by davidmann4** [comment]
You need to add:8081 to you ws config ( like in tge example)

**Comment by Dohab** [comment]
Me too can't make it work.
But the [Ogar ](https://github.com/OgarProject/Ogar) server works perfectly

**Comment by Dohab** [comment]
@davidmann4 what should I install in the server machine? I have A VPS with 7 IPs, Node.js, opened a port in iptable. When I use my ws://IP:PORT in the config file and the user script, feeder bot doesn't connect, nor the agar.io/ip=IP:PORT

**Comment by hassanila** [comment]
@Dohab are you sure the port 443 which is the default port for Ogar
server... is not in use by anything else? Because often that port is used
if you are hosting a webserver... or using skype on your vps...  If so then
you can try to change the default port on the gameserver.ini file... Hope
to hear back... :+1:

On 17 February 2016 at 20:07, Dohab notifications@github.com wrote:

> @davidmann4 https://github.com/davidmann4 what should I install in the
> server machine? I have A VPS with 7 IPs, Node.js, opened a port in iptable.
> When I use my ws://IP:PORT in the config file and the user script, feeder
> bot doesn't connect, nor the agar.io/ip=IP:PORT
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davidmann4/ogar-feeder-bot/issues/196#issuecomment-185353819
> .

## 

_Med vänliga hälsningar_
_Hassan_

**Comment by hassanila** [comment]
@Dohab and of course don't forget to restart the Ogar server...

On 17 February 2016 at 20:14, Hassan Ila hassanila97@gmail.com wrote:

> @Dohab are you sure the port 443 which is the default port for Ogar
> server... is not in use by anything else? Because often that port is used
> if you are hosting a webserver... or using skype on your vps...  If so then
> you can try to change the default port on the gameserver.ini file... Hope
> to hear back... :+1:
> 
> On 17 February 2016 at 20:07, Dohab notifications@github.com wrote:
> 
> > @davidmann4 https://github.com/davidmann4 what should I install in the
> > server machine? I have A VPS with 7 IPs, Node.js, opened a port in iptable.
> > When I use my ws://IP:PORT in the config file and the user script, feeder
> > bot doesn't connect, nor the agar.io/ip=IP:PORT
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/davidmann4/ogar-feeder-bot/issues/196#issuecomment-185353819
> > .
> 
> ## 
> 
> _Med vänliga hälsningar_
> _Hassan_

## 

_Med vänliga hälsningar_
_Hassan_

**Comment by Dohab** [comment]
@hassanila97 Yup, I'm sure.
I've changed the port from 443 to 8081 in the [Ogar](https://github.com/OgarProject/Ogar) configuration file and it's working great.
But with @davidmann4 server, It doesn't work.

Although, I could go with [Ogar](https://github.com/OgarProject/Ogar) , but it doesn't work with the feed bot unless I use the free server which is in the confing.js as the defualt server.

**Comment by Dohab** [comment]
@hassanila97 I don't have a problem with Ogar server, it's running great.
I just can't make it my feeder server.
I figured if I could make @davidmann4 server working, maybe I can set it up as my feeder server in the config and the user script.

**Comment by hassanila** [comment]
@Dohab ok but have you changed the port also not just the ip:port string you need to change the port integer also... check the image :+1: 
![2016-02-17 20_30_53-greenshot](https://cloud.githubusercontent.com/assets/15068696/13122058/693f5698-d5b5-11e5-8006-ef23572625e2.png)

**Comment by Dohab** [comment]
@hassanila97 I did that already, still not connection in the browser.

**Comment by hassanila** [comment]
@Dohab Sorry I don't know more solutions...

**Comment by Dohab** [comment]
@hassanila97 thank you sir

**Comment by hassanila** [comment]
@Dohab :+1:

**Comment by MooShoe** [comment]
Ok I've gotten it to work, I'm using the public server.

But what server do I now connect to now? Do I just go to agar.io/?ip="my ip" or do I have to connect to the feeder server? If so how?

**Comment by jacobduba** [comment]
I fixed this error but now I'm getting another - the sockets keep on getting closed.

**Comment by davidmann4** [comment]
open a new issue for your new problem
