### ISSUE TITLE
It's amazing, but ...

### ISSUE THREAD

**Issue by Dohab** [davidmann4/ogar-feeder-bot#197]
Hi all,
This script is very amazing thanks to david.

Now, I have a VPS, with 7 IPs, but still, I don't get something like raga.pw or even 1% of his minions.
Is there a secret setup to turn my VPS into a real feeder?

Maybe raga.pw is powered by Agar.io (just an idea).

**Comment by jacobduba** [comment]
From my limited knowledge, you'll need to set it up yourself. The feeder was designed for personal use, not to be like raga.pw.

Also agar.io ip bans people using bots, so agar.io would never make somthing like raga.pw.

**Comment by hassanila** [comment]
@MooShoe Bro, you never know, business comes before anything for some people in this corrupted world, just saying... :+1:
