### ISSUE TITLE
Agar.io compatible version w/ Experimental Feeding

### ISSUE THREAD

**Issue by gcsoftware** [davidmann4/ogar-feeder-bot#198]
@davidmann4 Let me know if you ever want to re-add support for agar.io to this project. Until then I'll try and keep it separate.

If anyone wants to test a post patch feeder bot (experimental) with agar.io support. I've also implemented the bot counter from @MastaCoder with a few fixes.

https://github.com/gcsoftware/gc-feeder.

Thanks :smiley:

**Comment by picusc** [comment]
It is not working with the official agario. It has the same problem as this repo. Says connected and spawning but the bots never show up anymore.

**Comment by davidmann4** [comment]
I guess you want to add this to my bot? https://github.com/davidmann4/ogar-feeder-bot/issues/199

it works on ogar so why not add it to this code?

**Comment by davidmann4** [comment]
also your changes are not agario related - its just a new behavior mode for the bot 

custom AI - and thats the main purpose of this repo - AI for a 2d based cell game
