### ISSUE TITLE
No bots connecting....

### ISSUE THREAD

**Issue by easyrider81** [davidmann4/ogar-feeder-bot#204]
None of my bots are connecting, I get this error for the first few:

"Bot_2: Connection Failed: Error: Socket Closed"

then this for the rest:
"Bot_12: Crash will be prevented, bot will be disconnected
Bot_12: Packet error detected for packet: 40 5f 95 a4 5e 0d 2c c0 c0 02 0d c2 87 be f9 bb c0 ce 98 19 af e4 02 b1 c0 05 1a 84 0f 7d a3 ae c0"

**Comment by WJKH** [comment]
Same https://github.com/davidmann4/ogar-feeder-bot/issues/199#event-555579271

**Comment by davidmann4** [comment]
Hmm I think it is a agario-client issue

**Comment by SnowyTube** [comment]
Same:

**Comment by WJKH** [comment]
Fix: https://github.com/pulviscriptor/agario-client/issues/90#issuecomment-185988568

**Comment by davidmann4** [comment]
added it
