### ISSUE TITLE
Update for blind mode.

### ISSUE THREAD

**Issue by xa** [davidmann4/ogar-feeder-bot#206]
If one bot can see target cell it can be marked as 'found target' and other bots can follow him too. It could create network of bots that are following the same target.

http://i.imgur.com/4Q9RxbE.png

**Comment by easyrider81** [comment]
Great idea if possible then the small ones could each other other to make bigger mass balls en route to your ball.

**Comment by davidmann4** [comment]
this is exactly what I wrote here: https://github.com/davidmann4/ogar-feeder-bot/issues/200

but your aproach is slightly different - I like it!

**Comment by davidmann4** [comment]
copy paste your msg to the other thread
