### ISSUE TITLE
Not connectiong on my private server

### ISSUE THREAD

**Issue by Lukkez** [davidmann4/ogar-feeder-bot#208]
How i connect the bots to my OWN private server, only says 'Error!' and don't spawn, i have working proxys

**Comment by Lukkez** [comment]
Bot_8894: Connecting to: ws://192.168.25.20:443
Bot_8895: Connecting to: ws://192.168.25.20:443
Bot_8896: Connecting to: ws://192.168.25.20:443
Bot_8897: Connecting to: ws://192.168.25.20:443
Bot_8898: Connecting to: ws://192.168.25.20:443
Bot_8899: Connecting to: ws://192.168.25.20:443
Bot_8900: Connecting to: ws://192.168.25.20:443
Bot_8901: Connecting to: ws://192.168.25.20:443
Bot_8902: Connecting to: ws://192.168.25.20:443
Bot_8903: Connecting to: ws://192.168.25.20:443
Bot_8904: Connecting to: ws://192.168.25.20:443
Bot_8905: Connecting to: ws://192.168.25.20:443
Bot_8906: Connecting to: ws://192.168.25.20:443
Bot_8907: Connecting to: ws://192.168.25.20:443
Bot_8908: Connecting to: ws://192.168.25.20:443
Bot_8909: Connecting to: ws://192.168.25.20:443
Bot_8910: Connecting to: ws://192.168.25.20:443
Bot_8911: Connecting to: ws://192.168.25.20:443
Bot_8912: Connecting to: ws://192.168.25.20:443
Bot_8913: Connecting to: ws://192.168.25.20:443
Bot_8914: Connecting to: ws://192.168.25.20:443
Bot_8915: Connecting to: ws://192.168.25.20:443
Bot_8916: Connecting to: ws://192.168.25.20:443
Bot_8917: Connecting to: ws://192.168.25.20:443
Bot_8918: Connecting to: ws://192.168.25.20:443
Bot_8919: Connecting to: ws://192.168.25.20:443
Bot_8920: Connecting to: ws://192.168.25.20:443
Bot_8921: Connecting to: ws://192.168.25.20:443
Bot_8922: Connecting to: ws://192.168.25.20:443
Bot_8923: Connecting to: ws://192.168.25.20:443
Bot_8924: Connecting to: ws://192.168.25.20:443
Bot_8925: Connecting to: ws://192.168.25.20:443
Bot_8926: Connecting to: ws://192.168.25.20:443
Bot_8927: Connecting to: ws://192.168.25.20:443
Bot_8928: Connecting to: ws://192.168.25.20:443
Bot_8929: Connecting to: ws://192.168.25.20:443
Bot_8930: Connecting to: ws://192.168.25.20:443
Bot_8931: Connecting to: ws://192.168.25.20:443
Bot_8932: Connecting to: ws://192.168.25.20:443
Bot_8933: Connecting to: ws://192.168.25.20:443
Bot_8934: Connecting to: ws://192.168.25.20:443
Bot_8935: Connecting to: ws://192.168.25.20:443
Bot_8936: Connecting to: ws://192.168.25.20:443
Bot_8937: Connecting to: ws://192.168.25.20:443
Bot_8938: Connecting to: ws://192.168.25.20:443
Bot_8939: Connecting to: ws://192.168.25.20:443
Bot_8940: Connecting to: ws://192.168.25.20:443
Bot_8941: Connecting to: ws://192.168.25.20:443
Bot_8942: Connecting to: ws://192.168.25.20:443
Bot_8943: Connecting to: ws://192.168.25.20:443
Bot_8944: Connecting to: ws://192.168.25.20:443
Bot_8945: Connecting to: ws://192.168.25.20:443
Bot_8946: Connecting to: ws://192.168.25.20:443
Bot_8947: Connecting to: ws://192.168.25.20:443
Bot_8948: Connecting to: ws://192.168.25.20:443
Bot_8949: Connecting to: ws://192.168.25.20:443
Bot_8950: Connecting to: ws://192.168.25.20:443
Bot_8951: Connecting to: ws://192.168.25.20:443
Bot_8952: Connecting to: ws://192.168.25.20:443
Bot_8953: Connecting to: ws://192.168.25.20:443
Bot_8954: Connecting to: ws://192.168.25.20:443
Bot_8955: Connecting to: ws://192.168.25.20:443
Bot_8956: Connecting to: ws://192.168.25.20:443
Bot_8957: Connecting to: ws://192.168.25.20:443
Bot_8958: Connecting to: ws://192.168.25.20:443
Bot_8959: Connecting to: ws://192.168.25.20:443
Bot_8960: Connecting to: ws://192.168.25.20:443
Bot_8961: Connecting to: ws://192.168.25.20:443
Bot_8962: Connecting to: ws://192.168.25.20:443
Bot_8963: Connecting to: ws://192.168.25.20:443
Bot_8964: Connecting to: ws://192.168.25.20:443
Bot_8965: Connecting to: ws://192.168.25.20:443
Bot_8966: Connecting to: ws://192.168.25.20:443
Bot_8967: Connecting to: ws://192.168.25.20:443
Bot_8968: Connecting to: ws://192.168.25.20:443
Bot_8969: Connecting to: ws://192.168.25.20:443
Bot_8970: Connecting to: ws://192.168.25.20:443
Bot_8971: Connecting to: ws://192.168.25.20:443
Bot_8972: Connecting to: ws://192.168.25.20:443
Bot_8973: Connecting to: ws://192.168.25.20:443
Bot_8974: Connecting to: ws://192.168.25.20:443
Bot_8975: Connecting to: ws://192.168.25.20:443
Bot_8976: Connecting to: ws://192.168.25.20:443
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
Error!
The log

**Comment by WJKH** [comment]
Use your external IP.

**Comment by Lukkez** [comment]
The server it's hosted on my computer, i can't connect by external ip

**Comment by Lukkez** [comment]
When i try to connect by extenal : WebSocket connection to 'ws://111.111.111:443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED, i put this ip because i don't want ddos on my pc

**Comment by WJKH** [comment]
Then don't use proxy.

**Comment by davidmann4** [comment]
well if you use proxies it has to be reachable to them

**Comment by Lukkez** [comment]
I'm brazillian and all proxys i have is brazil proxys...

**Comment by Lukkez** [comment]
;-; i think i will never get bots with no lagg on my server

**Comment by WJKH** [comment]
Just setup your own proxy server and use private network IPs.
You will get as many proxy as you want, no lag at all.

Or just allow more connections per IP and get as many bots as you want with only one IP.

**Comment by Lukkez** [comment]
But i can do with agar-feeder-bot?

2016-02-19 18:19 GMT-02:00 WJKH notifications@github.com:

**Comment by davidmann4** [comment]
use NOPROXY

**Comment by Lukkez** [comment]
Still doesn't work, work normal on my friend server
