### ISSUE TITLE
New descramble method?

### ISSUE THREAD

**Issue by hassanila** [davidmann4/ogar-feeder-bot#210]
Checkout this userscript, the minimap works perfectly so we can take the code from it, they have successfully descrabled it...

http://scastshow.com/agarplus.user.js

**Comment by mbm3** [comment]
this has potiential, looking right now.
EDIT: link doesnt work for me :P

**Comment by hassanila** [comment]
Wait I will get new link

**Comment by hassanila** [comment]
Here ye go: http://pastebin.com/raw/Ct6w9fDr

**Comment by KingMatt123** [comment]
I really miss bots, thanks @hassanila97 for finding this thing out! Brings us ever so closer to maybe finding a solution!

**Comment by hassanila** [comment]
Np, I've got it from the skype group discussion :)

**Comment by WJKH** [comment]
Some helpful data:

> Hi guys, I am Essence from the [A.I.] clan and I want to present you a script made by my russian friend Ivicoder. It makes map actually work in agarplus v2, with some limitations. First of all, I am not sure that I am allowed 100% to post link to this script here, so if I am not allowed to do that, I am sure that moderator will delete it ( do not delete this post, please), in that case please just PM me to get the script. I am sure that Acyd will fix agarplus soon, but anyway this script is better then nothing. I am sure this script will be more then helpfull. Anyway, let's get to business . 
> 
> This script uses borders as strarting point for the minimap. This mean that it doesn't make the map work from the start, but you need to actually reach and see (not touch!) borders of the map to set up map correctly. You need to reach any vertical AND any horizontal walls of the map to make it work, after it, borders and the minimap itself works just fine, and you can see your teammates too. Also you need to do it everytime you die, unfortunatly.  
> If you didn't see any walls the minimap will have red borders and your cell on the minimap will be red too. When you reach one wall, e.g. horizontal, red borders of horizontal walls will disappear, meaning you need to reach vertical walls. Of course you can just reach any corner to set up map ASAP. In case you didn't see any walls, your location will not be correct, but it will correctly show your quadrant ( top left, top right, bottom left, bottom right). That basically means that when your cell is somewhere around top  left quadrant the fastest way to set up your map is to reach top left corner. Also if your map is not set up just yet, you can see your teammate on the map anyway, but only if he had his map set up, if he didn't set up his map, he won't be shown correctly on the minimap. 
> This script does not affect any other aspect of agarplus v2 like skins, chat etc, moreover, in case when you have this script, and your teammate have usuall agarplus v2 it still works for you (you can use chat and see his skin etc.), you just don't see your teammate correctly on the minimap. 
> I've been testing this for couple of days, and it worked fine for me and my friends, I also helped a little to improve this script, so consider me a betatester :) 
> Please note though, this is still work in progress so bugs may occur, but I did not see too many of it. Also it will update automatically if you use google chrome, not so sure with other browsers though, anyway you can do it manually if there will be any updates before Acyd releases his fix. 
> I am more then sure this will be very helpfull for the community. 
> Here is the link - http://scastshow.com/agarplus.user.js To install it, just do it like you did with agarplus v2, so you should get tampermonkey first and then install the script. You should first disable any other extensions though ( including agarplus v 2!).  
> Script was tested and worked fine on google chrome and opera.
> Post any questions or bugreports here, I'll try to answer them all. 
> Anyway, have a great time guys! Let's wish Acyd best of luck!
> 
> P.S. There are other ways to make the map work -  e.g. use spectator mode, but it will possibly need high perfomance computer to handle this, so this method was not used. Also I suppose this method was used by bot sellers to make them work again.

**Comment by davidmann4** [comment]
does not work perfectly for me

**Comment by davidmann4** [comment]
> This script uses borders as strarting point for the minimap. This mean that it doesn't make the map work from the start, but you need to actually reach and see (not touch!) borders of the map to set up map correctly.

So nothing new here
