### ISSUE TITLE
Can it be faster? 

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#212]
hello i was just wondering if the bots can be faster and more accurate, ik that this took some time and not to rush but its just a kinda bug i guess bcs it takes really long for them to detect to me.

**Comment by davidmann4** [comment]
use better hardware and proxies and it will be faster

**Comment by Lukkez** [comment]
I have a Intel i3, my bots only get stopped and sometimes much laggy, i only use VIP Socks5 with more than 1Mbps

**Comment by Lukkez** [comment]
And one time the bots crashed my pc and using only 30% of cpu ( total used 64%)
