### ISSUE TITLE
Server booted up

### ISSUE THREAD

**Issue by RyanMLG** [davidmann4/ogar-feeder-bot#213]
![image](https://cloud.githubusercontent.com/assets/17353753/13196412/4ea4baf4-d807-11e5-8266-f3641a4b1e56.png)

**Comment by RyanMLG** [comment]
it doesnt show any proxies downstair

**Comment by hassanila** [comment]
You need to install the userscript in Chrome or Firefox and edit your uuid in both the userscript and config.js then go to Agar.io and it will work...

**Comment by hassanila** [comment]
And don't forget to start feeder.js also

**Comment by RyanMLG** [comment]
i already installed the userscript

**Comment by RyanMLG** [comment]
![image](https://cloud.githubusercontent.com/assets/17353753/13196446/9b5c4e92-d808-11e5-810f-5f6a79097693.png)

**Comment by hassanila** [comment]
But ok, r u sure you replaced uuid in both files and that you didn't edit the ip?

**Comment by RyanMLG** [comment]
yes

**Comment by RyanMLG** [comment]
![image](https://cloud.githubusercontent.com/assets/17353753/13196464/5c2a47a0-d809-11e5-8648-7683c0b7441d.png)

**Comment by RyanMLG** [comment]
![image](https://cloud.githubusercontent.com/assets/17353753/13196610/66bcbf46-d80d-11e5-964a-65b9b4fc9054.png)
i think i found the problem..but i dont know which part to put my uuid
