### ISSUE TITLE
Bot doesn't work on Ogar

### ISSUE THREAD

**Issue by AlexandriteErikParacelsus** [davidmann4/ogar-feeder-bot#215]
I don't know why my bots keep getting coordinate scramble on my own Ogar server, any help?

**Comment by hassanila** [comment]
@ErikParacelsus You need to change the option on gameserver.ini called something with scramble... By default it's 1 you need to replace it with 0 and restart the server...

**Comment by AlexandriteErikParacelsus** [comment]
@hassanila97 I did and it still doesn't work.

**Comment by davidmann4** [comment]
it should work with scramble and without scramble

**Comment by davidmann4** [comment]
Blind Mode: http://gfycat.com/KaleidoscopicMinorInvisiblerail
Default Mode: http://gfycat.com/ChiefThornyBanteng

default mode had an bug - I fixed it in the newest version, enjoy!
