### ISSUE TITLE
bots dont follow my mouse

### ISSUE THREAD

**Issue by Nick8fr32** [davidmann4/ogar-feeder-bot#216]
my bots dont follow my mouse??

**Comment by Dohab** [comment]
Bots have been patched by Agar.io, there is no fix yet.

**Comment by Nick8fr32** [comment]
i know... i mean on ogar

**Comment by Petterholm** [comment]
In settings on the ogar server you see cordinates scrambling set it to 0

**Comment by Nick8fr32** [comment]
thx  =D

**Comment by davidmann4** [comment]
should also work with scramble is set to 1 - you can update and try it again

**Comment by Petterholm** [comment]
Wait you have fixed cordinates scrambling? Does it work on public too?
