### ISSUE TITLE
Auto update and multi uuid

### ISSUE THREAD

**Issue by hassanila** [davidmann4/ogar-feeder-bot#219]
@davidmann4 Please add an **auto update feature** to this repo as it's very irritating to download zip every single commit and also allow server to manage **multi uuid** or better ip adresses...

**Comment by davidmann4** [comment]
whats auto update?

use git pull

**Comment by hassanila** [comment]
@davidmann4 in Windows make it a batch so that when there's new version it updates itself

**Comment by davidmann4** [comment]
git pull
