### ISSUE TITLE
How to use server.js exactly?

### ISSUE THREAD

**Issue by Dohab** [davidmann4/ogar-feeder-bot#231]
Every time I run server.js, I can't connect to it in chrome.
Changing feederServer in config (and userscript) to 127.0.0.1:443 doesn't work either.
But, if I use the free agar.io server, the console prints stuff like:
`Starting server on port 443
User connected with id:undefined
User connected with id:fce4
{ name: 'connect_server', ip: '' }
User connected with id:undefined
User connected with id:fce4
{ name: 'connect_server', ip: '' }
User connected with id:undefined
User connected with id:fce4`
, but it the game doesn't start in Chrome.

I don't know what to do with this file, why is it important?

**Comment by hassanila** [comment]
How many times do I have to say 127.0.0.1:8081   not 443  Both in userscript and config

**Comment by Dohab** [comment]
@hassanila97 I tried 8081 also, same result.

**Comment by hassanila** [comment]
Its something wrong with userscript....

**Comment by Dohab** [comment]
@hassanila97 Can't figure it out yet, I know it's a simple thing like always.
So tell me, does server.js itself start an actual agar.io game like [Ogar](https://github.com/OgarProject/Ogar) do?

**Comment by hassanila** [comment]
No, it doesn't
Server.js listens for userscript to send a message saying to connect the bots... Then when server.js received this message it forwards it to feeder.js that then spawns bots via proxies to the actual Agario original server or Ogar if you use private....
U get it?

**Comment by Dohab** [comment]
Well, one of us is wrong.
Feeder.js works without the need to run server.js at all. It contacts with userscript directly.
All this time, I never run server.js, and the bots floating like crazy. In Public FFA too.

But If server.js job is what you described, then why does it run separately from feeder.js? we can use one line in feeder.js instead of an entire process, like so:
`app.listen(config.serverPort);`

The rest of server.js is actually included in feeder.js

**Comment by hassanila** [comment]
Yeah exactly sry you r right... its cuz I wrote it fast without thinking lol   its exactly the opposite of what I said

**Comment by Dohab** [comment]
Never mind, but still I need to know what does server.js do?

**Comment by kstanley7** [comment]
how do I configure the server guys I'm new to scripting.

**Comment by hassanila** [comment]
@kstanley7 Go to [**Skype chat**](https://join.skype.com/eQuN52iQVzZg) and ask for help...

**Comment by davidmann4** [comment]
it coordinates clients and bots
