### ISSUE TITLE
Bots with mouse are working...

### ISSUE THREAD

**Issue by hassanila** [davidmann4/ogar-feeder-bot#234]
The bots with mouse do work check this video out uploaded today...  On raga.pw   I think they're using this, come on guys implement it:  
https://camo.githubusercontent.com/6eb2a5c0272942aa574c8ed017e459953290e8c8/687474703a2f2f692e696d6775722e636f6d2f345139527862452e706e67

---

https://www.youtube.com/watch?v=zLWKvI3CIdQ

**Comment by ghost** [comment]
Yeah I saw that too u might want to look into the code or it might just be inside of there own server
