### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#236]
Hey, yesterday the bots worked perfectly fine in blind mode but now they wont connect 
https://gyazo.com/2636e0b2eafb5f9a65c14cbce5c605e3
i also get some errors in chrome that looks like the public server ip
https://gyazo.com/51a5aee4fe4c6979378b3f708222d7cc

**Comment by Petterholm** [comment]
do i have to run server.js at the same time?

**Comment by easyrider81** [comment]
yes exactly the same issue and same errors in chrome console.

**Comment by Petterholm** [comment]
Hey i fixed it it is a problem with the public server. First open config.js
and find feeder server remove the ip there and ws:// and write in 127.0.0.1
and then edit the userscript the same and run server.js and then feeder.js
If it didnt work i can help you

Den tirsdag 23. februar 2016 skrev easyrider81 notifications@github.com
følgende:

**Comment by easyrider81** [comment]
Well i changed it all like you said but now i just get:

`GET http://127.0.0.1:8081/socket.io/?EIO=3&transport=polling&t=LCFLkxG net::ERR_CONNECTION_REFUSED`

**Comment by Petterholm** [comment]
Hey! I can send you my config and userscript in around 30 minutes.

Den tirsdag 23. februar 2016 skrev easyrider81 notifications@github.com
følgende:

**Comment by Petterholm** [comment]
Did you remember to start the server by holding down shift and right click
on the whole folder then write node server/server.js ?

Den tirsdag 23. februar 2016 skrev Petter Holm petterholm2012@gmail.com
følgende:

**Comment by easyrider81** [comment]
yeah i started server.js with node and it connects:

`{ name: 'connect_server', ip: 'ws://151.80.96.53:1518' }`

then i node feeder.js with agario page loaded and I just get those errors.

**Comment by Petterholm** [comment]
Can you copy the whole feeder server line? And send it in text not in a
file i'm at my phone

Den tirsdag 23. februar 2016 skrev easyrider81 notifications@github.com
følgende:

**Comment by easyrider81** [comment]
User connected with id:fdcd
{ name: 'connect_server', ip: 'ws://151.80.96.53:1518' }

**Comment by Petterholm** [comment]
No in config

Den tirsdag 23. februar 2016 skrev easyrider81 notifications@github.com
følgende:

**Comment by easyrider81** [comment]
config.feederServer = "127.0.0.1:8081";

**Comment by Petterholm** [comment]
Ok. Start the server first and then the feeder i know you already have done
it but do it again

Den tirsdag 23. februar 2016 skrev easyrider81 notifications@github.com
følgende:

**Comment by Petterholm** [comment]
I think you managed to delete something in config that you should have done

Den tirsdag 23. februar 2016 skrev Petter Holm petterholm2012@gmail.com
følgende:

**Comment by easyrider81** [comment]
no not working still. only edited what needed to be.

**Comment by hassanila** [comment]
@easyrider81 You have windows? if so go to skype chat we will help you...

**Comment by easyrider81** [comment]
I'm there now with same username

**Comment by Dohab** [comment]
Me too have this problem.
Yesterday everything works great, today nothing works,**not even** my own feeder.js (that I built from basic.js, which was working yesterday also but not today). **without changing anything from my side.**
First I suspected the internet connection, but at my job place I tried also.

If someone fixed this, please share the solution.

**Comment by Petterholm** [comment]
Its because the public server is down

Den tirsdag 23. februar 2016 skrev Dohab notifications@github.com
følgende:

**Comment by hassanila** [comment]
Yes it's down you have to use your own server
server.js

**Comment by Dohab** [comment]
server.js doesn't work for me @hassanila97 , remember? ;)

But, I've a VPS, running my own server there, I can log in successfully, but setting my VPS ip in confing and userscript doesn't work either.

**Comment by easyrider81** [comment]
tried using my own sever but it won't connect.

**Comment by Dohab** [comment]
@easyrider81 yeah, me too.

**Comment by easyrider81** [comment]
public server seems to work now but I get :

[https://gyazo.com/74ee63d633f7e09881e2b52c3d513004](url)

**Comment by easyrider81** [comment]
public sever works again so reverted back

**Comment by ghost** [comment]
I have that too idk why but try updating the script
