### ISSUE TITLE
Smarter Bots

### ISSUE THREAD

**Issue by David1ali12** [davidmann4/ogar-feeder-bot#241]
after I fixed error in cmd 
now bots works very good any bot see my cell come to it 
but bots are not that smart like agar unlitimited bots their bots are pro agar unlitimed is open source I ask if u can make  ogar feeder like their bots because there are all codes there

**Comment by hassanila** [comment]
[**Ogar Unlimited**](https://github.com/AJS-development/Ogar-unlimited) link

**Comment by David1ali12** [comment]
https://github.com/AJS-development/Ogar-unlimited/tree/master/src/ai

**Comment by davidmann4** [comment]
funny, thx for the link

**Comment by David1ali12** [comment]
wow you replied
