### ISSUE TITLE
Bots work with HTTPs proxys? (reply fast plz)

### ISSUE THREAD

**Issue by Lukkez** [davidmann4/ogar-feeder-bot#245]

**Comment by ghost** [comment]
Yeah! HTTPs is more better.

**Comment by easyrider81** [comment]
@Nwuser can I ask why https are better?

**Comment by Lukkez** [comment]
For me don't work, only says Error! i buyed a plan on awmproxy and don't work :/ i need to create #HTTPS instead #HTTP on proxy.txt?

**Comment by davidmann4** [comment]
should work out of the box
