### ISSUE TITLE
what is onboardingTimer

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#246]

**Comment by hassanila** [comment]
@loboere OnboardingTimer is how long interval between each connection to proxies... so if you set it to a lower value like 100 the bots will spawn faster... yes you can also set it to 1 but need good internet connection.

**Comment by ghost** [comment]
I set myn to -999999999999999999999 would it do anything?

**Comment by hassanila** [comment]
@Butterflypanda Idk but its useless to set it to that "stupid" value and can also trigger some other unknown bugs...  you can set it to 0 and it will be same thing but just better...

**Comment by davidmann4** [comment]
you can onboard the clients over time with this value
