### ISSUE TITLE
Other extensions features

### ISSUE THREAD

**Issue by Lukkez** [davidmann4/ogar-feeder-bot#249]
How to get other extensions features? like agariomods, agarplus, igario, hkg, ogario? i have the code

**Comment by davidmann4** [comment]
do not understand your question

**Comment by hassanila** [comment]
@davidmann4 Please reopen this issue...  What @Lukkez is saying is to add features to this repo. Features like 16 split... chat... minimap... and much more.... Of course we will use this on our own "Ogar servers" to not be against the tos. Lol

**Comment by Lukkez** [comment]
Yea, i mostly use on parisgamma

**Comment by davidmann4** [comment]
open seperate issues for each feature

**Comment by Lukkez** [comment]
Ok
