### ISSUE TITLE
config.js Help

### ISSUE THREAD

**Issue by zeliad-papa** [davidmann4/ogar-feeder-bot#25]
Please explain the possible settings?

//this agar ip:port ? 
config.forceConnectToIp = false;
config.forceIp = "151.80.98.52:1507"

//what is forcekey? Party code?
config.forceKey = "EVZ74";

Another question

node feeder.js "GAME_ID"
GAMEֹ_ID = PARTY CODE?

**Comment by zeliad-papa** [comment]
[agar@vmi55044 agario-feeder-bot]$ node feeder.js 4UVFY
http://NOPROXY
Requesting party server
http://
Requesting party server
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONN                                                                                                                                                              REFUSED)
player 2 5.189.150.242:57643 joined.
ws://5.189.150.242:34343 connected
Engaging bots to party http://agar.io/#4UVFY on IP 37.187.163.130:1516
poland
Bot 1: client created
italy
Bot 2: client created
portugal
Bot 3: client created
japan
Bot 4: client created
reddit
Bot 5: client created
1 says: Connecting to ws://37.187.163.130:1516 with key 4UVFY
Bot 1: connecting...
Bot 1: connection error: Error: connect ECONNREFUSED
1 says: Connection failed with reason: Error: connect ECONNREFUSED
1 says: Server address set to: ws://37.187.163.130:1516 key 4UVFY
2 says: Connecting to ws://37.187.163.130:1516 with key 4UVFY
Bot 2: connecting...
Bot 2: connection error: Error: connect ECONNREFUSED
2 says: Connection failed with reason: Error: connect ECONNREFUSED
2 says: Server address set to: ws://37.187.163.130:1516 key 4UVFY
3 says: Connecting to ws://37.187.163.130:1516 with key 4UVFY
Bot 3: connecting...
Bot 3: connection error: Error: connect ECONNREFUSED
3 says: Connection failed with reason: Error: connect ECONNREFUSED
3 says: Server address set to: ws://37.187.163.130:1516 key 4UVFY
^C
[agar@vmi55044 agario-feeder-bot]$ player 2 5.189.150.242:57643 has left.
[agar@vmi55044 agario-feeder-bot]$

**Comment by davidmann4** [comment]
you need a socks.txt with 
NOPROXY 
in it

**Comment by zeliad-papa** [comment]
help me what my problem,

#scoks (all work i chacked)
[agar@vmi55044 agario-feeder-bot]$ cat socks.txt | wc -l
83

#config
config.userAgent = 'agario-feeder-bot';
config.mapserver = "ws://5.189.150.242:34343";
config.proxies = "socks.txt";

//set useRandomSkinName to false to always use the staticName
config.useRandomSkinName = true;
config.useStaticName = "austria";

config.forceConnectToIp = false;
config.forceIp = "151.80.98.52:1507"
config.forceKey = "EVZ74";

module.exports = config;

#mini-map Server 
[agar@vmi55044 server]$  npm run start

> mini-map-server@0.0.1 start /home/agar/agar-mini-map/server
> node dist/server.js

server is now on the port:34343
player 1 (My IP):59417 joined.
player 1 set nickname:
player 1 update address: (Unknown) -> ws://37.187.163.132:1530
player 1 set nickname: My Boll
player 2 5.189.150.242:36896 joined.

#agario-feeder-bot
[agar@vmi55044 agario-feeder-bot]$ node feeder.js J3UM8

http://109.221.201.153:1080
Requesting party server
http://109.123.70.137:1080
Requesting party server
http://101.200.178.189:1080
Requesting party server
http://113.21.231.81:1080
Requesting party server
http://113.21.231.106:1080
Requesting party server
http://110.138.100.9:8089
Requesting party server
http://109.238.208.242:1080
Requesting party server
http://109.202.118.121:1080
Requesting party server
http://108.53.207.220:49194
Requesting party server
http://107.185.206.82:10200
Requesting party server
http://107.181.128.160:1080
Requesting party server
http://106.185.48.200:1080
Requesting party server
http://104.230.52.82:15809
Requesting party server
http://103.54.218.68:1080
Requesting party server
http://103.53.169.106:1080
Requesting party server
http://103.31.21.50:1080
Requesting party server
http://103.27.236.241:1080
Requesting party server
http://103.251.90.124:1080
Requesting party server
http://103.249.28.85:1080
Requesting party server
http://103.24.244.21:1080
Requesting party server
http://101.44.3.50:1080
Requesting party server
http://101.200.81.253:1080
Requesting party server
http://115.154.138.26:1080
Requesting party server
http://114.6.45.106:1080
Requesting party server
http://114.252.91.114:1080
Requesting party server
http://114.252.64.74:1080
Requesting party server
http://114.24.5.179:3129
Requesting party server
http://113.111.43.163:1080
Requesting party server
http://113.11.213.99:1080
Requesting party server
http://113.106.223.130:1080
Requesting party server
http://111.179.97.196:1080
Requesting party server
http://103.62.148.25:1080
Requesting party server
http://116.226.190.76:1080
Requesting party server
http://116.116.108.101:1080
Requesting party server
http://115.29.33.119:1080
Requesting party server
http://115.29.139.240:54321
Requesting party server
http://115.230.127.132:1080
Requesting party server
http://115.154.138.20:1080
Requesting party server
http://114.252.83.135:1080
Requesting party server
http://113.105.237.86:1080
Requesting party server
http://112.124.37.23:1080
Requesting party server
http://101.81.193.202:1080
Requesting party server
http://119.47.91.113:1080
Requesting party server
http://119.29.147.153:1080
Requesting party server
http://119.136.183.100:1080
Requesting party server
http://119.117.177.233:1080
Requesting party server
http://118.8.61.142:1080
Requesting party server
http://118.34.192.120:1080
Requesting party server
http://115.64.203.53:1080
Requesting party server
http://115.47.4.136:1080
Requesting party server
http://115.29.160.83:1080
Requesting party server
http://115.28.37.33:1080
Requesting party server
http://115.28.27.236:1080
Requesting party server
http://104.220.26.167:14878
Requesting party server
http://103.243.27.45:1080
Requesting party server
http://121.40.221.73:8888
Requesting party server
http://121.40.102.199:1080
Requesting party server
http://121.156.170.167:1080
Requesting party server
http://120.72.85.30:1080
Requesting party server
http://120.27.108.88:1080
Requesting party server
http://120.25.123.49:1080
Requesting party server
http://120.24.174.107:1080
Requesting party server
http://120.234.6.50:1080
Requesting party server
http://120.234.15.130:1080
Requesting party server
http://119.29.73.13:1080
Requesting party server
http://118.192.148.228:1080
Requesting party server
http://118.192.145.99:1080
Requesting party server
http://123.89.150.11:1080
Requesting party server
http://123.117.85.89:1080
Requesting party server
http://122.53.178.100:1080
Requesting party server
http://122.144.131.111:1080
Requesting party server
http://122.117.227.162:1080
Requesting party server
http://122.10.10.135:1080
Requesting party server
http://121.40.96.76:8080
Requesting party server
http://121.40.34.139:3128
Requesting party server
http://121.40.241.97:9998
Requesting party server
http://121.12.148.149:1080
Requesting party server
http://120.55.91.216:1080
Requesting party server
http://120.27.101.186:1080
Requesting party server
http://123.57.206.99:35330
Requesting party server
http://123.56.94.68:1080
Requesting party server
http://121.42.142.104:1080
Requesting party server
http://120.55.195.140:1080
Requesting party server
http://
Requesting party server
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
ws://5.189.150.242:34343 connected
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
Engaging bots to party http://agar.io/#J3UM8 on IP 151.80.96.53:1530
netherlands
Bot 1: client created
lithuania
Bot 2: client created
argentina
Bot 3: client created
italy
Bot 4: client created
norway
Bot 5: client created
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
1 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 1: connecting...
Bot 1: connection error: Error: connect ECONNREFUSED
1 says: Connection failed with reason: Error: connect ECONNREFUSED
1 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Engaging bots to party http://agar.io/#J3UM8 on IP 151.80.96.53:1530
chile
Bot 6: client created
qing dynasty
Bot 7: client created
portugal
Bot 8: client created
prussia
Bot 9: client created
usa
Bot 10: client created
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
2 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 2: connecting...
Bot 2: connection error: Error: connect ECONNREFUSED
2 says: Connection failed with reason: Error: connect ECONNREFUSED
2 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Engaging bots to party http://agar.io/#J3UM8 on IP 151.80.96.53:1530
tsarist russia
Bot 11: client created
vinesauce
Bot 12: client created
hong kong
Bot 13: client created
moon
Bot 14: client created
hungary
Bot 15: client created
3 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 3: connecting...
Bot 3: connection error: Error: connect ECONNREFUSED
3 says: Connection failed with reason: Error: connect ECONNREFUSED
3 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
4 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 4: connecting...
Bot 4: connection error: Error: connect ECONNREFUSED
4 says: Connection failed with reason: Error: connect ECONNREFUSED
4 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
5 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 5: connecting...
Bot 5: connection error: Error: connect ECONNREFUSED
5 says: Connection failed with reason: Error: connect ECONNREFUSED
5 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
6 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 6: connecting...
Bot 6: connection error: Error: connect ECONNREFUSED
6 says: Connection failed with reason: Error: connect ECONNREFUSED
6 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
7 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 7: connecting...
Bot 7: connection error: Error: connect ECONNREFUSED
7 says: Connection failed with reason: Error: connect ECONNREFUSED
7 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
8 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 8: connecting...
Bot 8: connection error: Error: connect ECONNREFUSED
8 says: Connection failed with reason: Error: connect ECONNREFUSED
8 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
9 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 9: connecting...
Bot 9: connection error: Error: connect ECONNREFUSED
9 says: Connection failed with reason: Error: connect ECONNREFUSED
9 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
10 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 10: connecting...
Bot 10: connection error: Error: connect ECONNREFUSED
10 says: Connection failed with reason: Error: connect ECONNREFUSED
10 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
11 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 11: connecting...
Bot 11: connection error: Error: connect ECONNREFUSED
11 says: Connection failed with reason: Error: connect ECONNREFUSED
11 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
12 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 12: connecting...
Bot 12: connection error: Error: connect ECONNREFUSED
12 says: Connection failed with reason: Error: connect ECONNREFUSED
12 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
13 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 13: connecting...
Bot 13: connection error: Error: connect ECONNREFUSED
13 says: Connection failed with reason: Error: connect ECONNREFUSED
13 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
14 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 14: connecting...
Bot 14: connection error: Error: connect ECONNREFUSED
14 says: Connection failed with reason: Error: connect ECONNREFUSED
14 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
15 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 15: connecting...
Bot 15: connection error: Error: connect ECONNREFUSED
15 says: Connection failed with reason: Error: connect ECONNREFUSED
15 says: Server address set to: ws://151.80.96.53:1530 key J3UM8

**Comment by davidmann4** [comment]
what happens if you put NOPROXY into your socks.txt file ?

**Comment by davidmann4** [comment]
also only http proxies worked for me

**Comment by zeliad-papa** [comment]
[agar@vmi55044 agario-feeder-bot]$ cp socks.txt old.socks.txt
[agar@vmi55044 agario-feeder-bot]$ echo NOPROXY > socks.txt
[agar@vmi55044 agario-feeder-bot]$ cat socks.txt
NOPROXY
[agar@vmi55044 agario-feeder-bot]$ node feeder.js J3UM8
http://NOPROXY
Requesting party server
http://
Requesting party server
failed to connect to map server
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
Engaging bots to party http://agar.io/#J3UM8 on IP 151.80.96.53:1530
pewdiepie
Bot 1: client created
ussr
Bot 2: client created
romania
Bot 3: client created
prussia
Bot 4: client created
poland
Bot 5: client created
1 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 1: connecting...
Bot 1: connection error: Error: connect ECONNREFUSED
1 says: Connection failed with reason: Error: connect ECONNREFUSED
1 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
2 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 2: connecting...
Bot 2: connection error: Error: connect ECONNREFUSED
2 says: Connection failed with reason: Error: connect ECONNREFUSED
2 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
3 says: Connecting to ws://151.80.96.53:1530 with key J3UM8
Bot 3: connecting...
Bot 3: connection error: Error: connect ECONNREFUSED
3 says: Connection failed with reason: Error: connect ECONNREFUSED
3 says: Server address set to: ws://151.80.96.53:1530 key J3UM8
^C
[agar@vmi55044 agario-feeder-bot]$

**Comment by zeliad-papa** [comment]
I do not understand
Where is the problem?

**Comment by davidmann4** [comment]
can you pull the newest version and try ?

**Comment by zeliad-papa** [comment]
# NOPROXY

[agar@vmi55044 agario-feeder-bot]$ node feeder.js ZURRN
http://NOPROXY
Requesting party server
http://
Requesting party server
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
ws://5.189.150.242:34343 connected
Engaging bots to party http://agar.io/#ZURRN on IP 151.80.98.51:1509
ireland
Bot 1: client created
usa
Bot 2: client created
greece
Bot 3: client created
taiwan
Bot 4: client created
france
Bot 5: client created
1 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 1: connecting...
Bot 1: connection error: Error: connect ECONNREFUSED
1 says: Connection failed with reason: Error: connect ECONNREFUSED
1 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
2 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 2: connecting...
Bot 2: connection error: Error: connect ECONNREFUSED
2 says: Connection failed with reason: Error: connect ECONNREFUSED
2 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
3 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 3: connecting...
Bot 3: connection error: Error: connect ECONNREFUSED
3 says: Connection failed with reason: Error: connect ECONNREFUSED
3 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
4 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 4: connecting...
Bot 4: connection error: Error: connect ECONNREFUSED
4 says: Connection failed with reason: Error: connect ECONNREFUSED
4 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
5 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 5: connecting...
Bot 5: connection error: Error: connect ECONNREFUSED
5 says: Connection failed with reason: Error: connect ECONNREFUSED
5 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
^C
[agar@vmi55044 agario-feeder-bot]$

# There proxy

[agar@vmi55044 agario-feeder-bot]$ node feeder.js ZURRN
http://109.221.201.153:1080
Requesting party server
http://109.123.70.137:1080
Requesting party server
http://101.200.178.189:1080
Requesting party server
http://113.21.231.81:1080
Requesting party server
http://113.21.231.106:1080
Requesting party server
http://110.138.100.9:8089
Requesting party server
http://109.238.208.242:1080
Requesting party server
http://109.202.118.121:1080
Requesting party server
http://108.53.207.220:49194
Requesting party server
http://107.185.206.82:10200
Requesting party server
http://107.181.128.160:1080
Requesting party server
http://106.185.48.200:1080
Requesting party server
http://104.230.52.82:15809
Requesting party server
http://103.54.218.68:1080
Requesting party server
http://103.53.169.106:1080
Requesting party server
http://103.31.21.50:1080
Requesting party server
http://103.27.236.241:1080
Requesting party server
http://103.251.90.124:1080
Requesting party server
http://103.249.28.85:1080
Requesting party server
http://103.24.244.21:1080
Requesting party server
http://101.44.3.50:1080
Requesting party server
http://101.200.81.253:1080
Requesting party server
http://115.154.138.26:1080
Requesting party server
http://114.6.45.106:1080
Requesting party server
http://114.252.91.114:1080
Requesting party server
http://114.252.64.74:1080
Requesting party server
http://114.24.5.179:3129
Requesting party server
http://113.111.43.163:1080
Requesting party server
http://113.11.213.99:1080
Requesting party server
http://113.106.223.130:1080
Requesting party server
http://111.179.97.196:1080
Requesting party server
http://103.62.148.25:1080
Requesting party server
http://116.226.190.76:1080
Requesting party server
http://116.116.108.101:1080
Requesting party server
http://115.29.33.119:1080
Requesting party server
http://115.29.139.240:54321
Requesting party server
http://115.230.127.132:1080
Requesting party server
http://115.154.138.20:1080
Requesting party server
http://114.252.83.135:1080
Requesting party server
http://113.105.237.86:1080
Requesting party server
http://112.124.37.23:1080
Requesting party server
http://101.81.193.202:1080
Requesting party server
http://119.47.91.113:1080
Requesting party server
http://119.29.147.153:1080
Requesting party server
http://119.136.183.100:1080
Requesting party server
http://119.117.177.233:1080
Requesting party server
http://118.8.61.142:1080
Requesting party server
http://118.34.192.120:1080
Requesting party server
http://115.64.203.53:1080
Requesting party server
http://115.47.4.136:1080
Requesting party server
http://115.29.160.83:1080
Requesting party server
http://115.28.37.33:1080
Requesting party server
http://115.28.27.236:1080
Requesting party server
http://104.220.26.167:14878
Requesting party server
http://103.243.27.45:1080
Requesting party server
http://121.40.221.73:8888
Requesting party server
http://121.40.102.199:1080
Requesting party server
http://121.156.170.167:1080
Requesting party server
http://120.72.85.30:1080
Requesting party server
http://120.27.108.88:1080
Requesting party server
http://120.25.123.49:1080
Requesting party server
http://120.24.174.107:1080
Requesting party server
http://120.234.6.50:1080
Requesting party server
http://120.234.15.130:1080
Requesting party server
http://119.29.73.13:1080
Requesting party server
http://118.192.148.228:1080
Requesting party server
http://118.192.145.99:1080
Requesting party server
http://123.89.150.11:1080
Requesting party server
http://123.117.85.89:1080
Requesting party server
http://122.53.178.100:1080
Requesting party server
http://122.144.131.111:1080
Requesting party server
http://122.117.227.162:1080
Requesting party server
http://122.10.10.135:1080
Requesting party server
http://121.40.96.76:8080
Requesting party server
http://121.40.34.139:3128
Requesting party server
http://121.40.241.97:9998
Requesting party server
http://121.12.148.149:1080
Requesting party server
http://120.55.91.216:1080
Requesting party server
http://120.27.101.186:1080
Requesting party server
http://123.57.206.99:35330
Requesting party server
http://123.56.94.68:1080
Requesting party server
http://121.42.142.104:1080
Requesting party server
http://120.55.195.140:1080
Requesting party server
http://
Requesting party server
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)
ws://5.189.150.242:34343 connected
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect EHOSTUNREACH)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Engaging bots to party http://agar.io/#ZURRN on IP 151.80.98.51:1509
piccolo
Bot 1: client created
india
Bot 2: client created
mexico
Bot 3: client created
finland
Bot 4: client created
yaranaika
Bot 5: client created
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=WRONG_HTTP_CODE, error_source=null)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
1 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 1: connecting...
Bot 1: connection error: Error: connect ECONNREFUSED
1 says: Connection failed with reason: Error: connect ECONNREFUSED
1 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
2 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 2: connecting...
Bot 2: connection error: Error: connect ECONNREFUSED
2 says: Connection failed with reason: Error: connect ECONNREFUSED
2 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
3 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 3: connecting...
Bot 3: connection error: Error: connect ECONNREFUSED
3 says: Connection failed with reason: Error: connect ECONNREFUSED
3 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
4 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 4: connecting...
Bot 4: connection error: Error: connect ECONNREFUSED
4 says: Connection failed with reason: Error: connect ECONNREFUSED
4 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
5 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 5: connecting...
Bot 5: connection error: Error: connect ECONNREFUSED
5 says: Connection failed with reason: Error: connect ECONNREFUSED
5 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
Engaging bots to party http://agar.io/#ZURRN on IP 151.80.98.51:1509
indonesia
Bot 6: client created
kc
Bot 7: client created
russia
Bot 8: client created
estonia
Bot 9: client created
chile
Bot 10: client created
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
Failed to request server (error=REQUEST_ERROR, error_source=Error: read ECONNRESET)
6 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 6: connecting...
Bot 6: connection error: Error: connect ECONNREFUSED
6 says: Connection failed with reason: Error: connect ECONNREFUSED
6 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
7 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 7: connecting...
Bot 7: connection error: Error: connect ECONNREFUSED
7 says: Connection failed with reason: Error: connect ECONNREFUSED
7 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
8 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 8: connecting...
Bot 8: connection error: Error: connect ECONNREFUSED
8 says: Connection failed with reason: Error: connect ECONNREFUSED
8 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
9 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 9: connecting...
Bot 9: connection error: Error: connect ECONNREFUSED
9 says: Connection failed with reason: Error: connect ECONNREFUSED
9 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
10 says: Connecting to ws://151.80.98.51:1509 with key ZURRN
Bot 10: connecting...
Bot 10: connection error: Error: connect ECONNREFUSED
10 says: Connection failed with reason: Error: connect ECONNREFUSED
10 says: Server address set to: ws://151.80.98.51:1509 key ZURRN
^C
[agar@vmi55044 agario-feeder-bot]$

**Comment by AgarioCheats** [comment]
Perhaps the problem with can't parse more lines?
Have you tried one single proxy?

**Comment by AgarioCheats** [comment]
Also, how would it be possible to ignore errors? Often there proxies causes one packet less/more to be sent, which I believe causes error and then disconnects all bots. How would it be possible to make the bots auto-persist trying to rejoin the game even if they disconnect?

**Comment by davidmann4** [comment]
hmm, what happens if you do:
git pull
then just put 1 line into your proxy.txt:
NOPROXY

**Comment by davidmann4** [comment]
maybe just shitty proxies ? are they socks4,5 or http? you need http proxies

**Comment by zeliad-papa** [comment]
http://socksproxylist24.blogspot.co.il/2016/01/14-01-16-socks-proxy-list_3.html
NOT GOOD?

but my local IP server no connect 5 boll

**Comment by davidmann4** [comment]
looks like socks proxies to me - does local ip work ?

**Comment by zeliad-papa** [comment]
no its not work
you like teamviewr help?

**Comment by davidmann4** [comment]
skype?

**Comment by zeliad-papa** [comment]
yairnetmu

**Comment by zeliad-papa** [comment]
The problem with proxy
Everything works now
David thanks for everything
Grateful
