### ISSUE TITLE
[Request]See other players mass

### ISSUE THREAD

**Issue by Lukkez** [davidmann4/ogar-feeder-bot#253]

**Comment by mbm3** [comment]
This can be done easily with Agar Expose.

**Comment by Lukkez** [comment]
How? And add a option to turn on/off

**Comment by Lukkez** [comment]
Ik now

**Comment by WJKH** [comment]
@Lukkez if you have it done make a pull request to add it, don't open/close issues for nothing.

**Comment by Lukkez** [comment]
Ok, it's much easy but ok
