### ISSUE TITLE
[Request] Facebook Bots

### ISSUE THREAD

**Issue by cinicz** [davidmann4/ogar-feeder-bot#265]
@davidmann4 Will u add facebook login for bots? **Please .**
@edit or gmail login too

**Comment by davidmann4** [comment]
are there fb / g login on ogar servers?

**Comment by cinicz** [comment]
I want [THAT](https://www.youtube.com/watch?v=JJsPId1jgzQ)
Can u do it ?

**Comment by davidmann4** [comment]
read the issue rules
