### ISSUE TITLE
I have search the best ports and found this.

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#266]
# Port: Proxies: Works: Speed:

3128 = 157 = 22 = +/-                     

8080 = 157 = 30 = +                     

8118 = 22 = 4 = +

8126 = 1 = 1 = +

8136 = 1 = 1 = -/+

8146 = 1 = 1 = +

8147 = 1 = 1 = +

8585 = 1 = 1 = -/+

8888 = 7 = 1 = -/+

9999 = 5 = 3 = +/-  (Errors message: Crash will be prevent!/Packed error detected!).
9797 = 2 = 1 = +   (Errors message: Crash will be prevent!/Packed error detected!).
## Others ports don't works!

Lol This save your live :p

```
 + = Good Speed
 +/- = Less or more Speed
 -/+ = More or less Speed
 - = Bad Speed
```

**Comment by Lukkez** [comment]
What about socks? 61837, 16640, 19254 and much more

**Comment by ghost** [comment]
Guy my socks 5 almost all works type 10/9 i have 600+ bots i have crashed a ogar server :P, more i use socks 5 with ports 10000 and 45021.

I' am from Brazil (bad english).

**Comment by Lukkez** [comment]
Também sou do Brasil, feliz por achar um aqui no GitHub :D

**Comment by Lukkez** [comment]
E sério, tu tem muitas proxys boas?
Eu tenho proxy para 100 bot, queria crashar alguns servidores kkk

**Comment by ghost** [comment]
kkk eu lembro que tinha algum br aqui, tenho e fácil encontrar entra nesse site :http://vip-socks24.blogspot.com.br/

**Comment by Lukkez** [comment]
Quando eu coloco muitas os bots diminui, vi um video de um cara que fez 1000 bots com isso n sei como

**Comment by ghost** [comment]
Como assim num entendi que sentido k, tem alguns que não da tipo, você ta falando que ele conecta e sai? Talvez e o proxy ruim, repetido ou e porque o server tem um limite para ip.

Olha esse server http://agar.io/?ip=75.74.28.26:3001 k

**Comment by Nwuser** [comment]
Olha esse server http://agar.io/?ip=75.74.28.26:3001 k

**Comment by Lukkez** [comment]
Teu servidor?

**Comment by Nwuser** [comment]
Não e um que ache por ai, esses oly king são meus bots!

**Comment by Nwuser** [comment]
Esse server ta uma hora assim travado. Acho que exagerei kk,
