### ISSUE TITLE
[Request]Option to acid mode

### ISSUE THREAD

**Issue by Lukkez** [davidmann4/ogar-feeder-bot#267]
How to put acid mode? i have the code to acid mode it's:
setAcid($(this).is(':checked'));

**Comment by Lukkez** [comment]
How to make a option to this on extension?

**Comment by ghost** [comment]
@davidmann4 You can add a .txt file to edit configurations, like the Ogar Project.

**Comment by Lukkez** [comment]
On setting's on agar.io? like show mass check box

**Comment by davidmann4** [comment]
we have config.js for config stuff - what is a acid mode?

**Comment by Lukkez** [comment]
Nvm, i have now

**Comment by davidmann4** [comment]
what is a acid mode?

**Comment by Lukkez** [comment]
Open console and put setAcid
