### ISSUE TITLE
Spawning with different proxies

### ISSUE THREAD

**Issue by AgarioCheats** [davidmann4/ogar-feeder-bot#27]
There seems to be an issue for spawning bots with several proxies in one file (proxy.txt)
so for example
proxy1
proxy2
proxy3

Running the feeder.js logs 15 bots attempting to connect, however only 5 first manage to connect.
the rest 10 bots log connection error:
Bot 7: connection error: Error: unexpected server response (504)
Connection failed with reason: Error: unexpected server response (504)

All three proxies work.
I guess it's a simple issue with reading the next line and using that IP for spawning the next bots? I assume all the bots attempt to spawn using the first IP, instead of assigning each set of 5 bots unique IP from the list.

**Comment by davidmann4** [comment]
are you using the newest version? there was a bug which I fixed yesterday

**Comment by davidmann4** [comment]
you can run proxy.txt lines one by one like this:
node feeder.js ABCDEF 0
node feeder.js ABCDEF 1
node feeder.js ABCDEF 2

with the newest version it should work to runn them together

**Comment by AgarioCheats** [comment]
Okay, cool. Ill try. Run each one with a different console, right? Or use screen/tmux/pm2 perhaps

**Comment by davidmann4** [comment]
you can do both or just do a git pull and it will work

**Comment by WJKH** [comment]
> with the newest version it should work to runn them together

Not working for me, same as before.
Last line show: http:// then..
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect ECONNREFUSED)

BTW.. with last version I'm having a problem with this line:

```
this.client.headers['user-agent'] = config.userAgent;
```

```
Bot 1: client created
/home/ogar/agario-client/examples/feeder.js:29
    this.client.headers['user-agent'] = config.userAgent;
                                      ^
TypeError: Cannot set property 'user-agent' of undefined
    at Object.ExampleBot (/home/ogar/agario-client/examples/feeder.js:29:39)
    at /home/ogar/agario-client/examples/feeder.js:319:40
    at /home/ogar/node_modules/agario-client/servers.js:160:13
    at IncomingMessage.<anonymous> (/home/ogar/node_modules/agario-client/servers.js:66:17)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by davidmann4** [comment]
I guess you have a blank line in your proxy.tx at the end - the programm should ignor blank lines in the future.

can you rmeove the blank line and check if it is working?

**Comment by WJKH** [comment]
> I guess you have a blank line in your proxy.tx at the end

I was thinking the same before, but there's not a blank line at the end.

**Comment by davidmann4** [comment]
ahh you need to update the agario-client 

npm install agario-client

**Comment by davidmann4** [comment]
he just added the header feature yesterday
