### ISSUE TITLE
[Request] Skin Change shortcut

### ISSUE THREAD

**Issue by hassanila** [davidmann4/ogar-feeder-bot#270]
**Add a shortcut to change skin from those that are available in random order...
NOTE: This needs to work only when user is logged in (Google/Fb) and has more than one skin available...**

Yes, you are able to change skin in mid-game... **Try it for yourself**
# @davidmann4 Skins are available on **Ogar** (Unlimited version)... [link](https://github.com/AJS-development/Ogar-unlimited)
# It's very funny and **possible**, check out this video on [**youtu.be**](https://youtu.be/269wD50BJQg?t=334)

---

Example press **Z** to change to random/next skin (only owned skins)

![2016-02-29 06_19_31-agar io](https://cloud.githubusercontent.com/assets/15068696/13386410/726d0c4c-deac-11e5-8936-615264ff086d.png)

**Comment by MasonBurdette** [comment]
I've gotten a friend who's made one of these. It's private tho.

**Comment by hassanila** [comment]
@MasonBurdette It's not hard to make as it requires one javascript line only... the only problem is to inspect the canvas which cant be done in Chrome... -_-  fk

**Comment by WJKH** [comment]
@hassanila97 if it's not hard try to implement it and pull request.

**Comment by MasonBurdette** [comment]
Hint: edit the agario.js code, and make a script that replaces it.

**Comment by Lukkez** [comment]
chrispierce.tk, released... but is automatic
