### ISSUE TITLE
[ERROR URGENT] David Please help 

### ISSUE THREAD

**Issue by mayed505** [davidmann4/ogar-feeder-bot#272]
I wanted to encode my userscript so no one can decode and expose my secrete code.
So when i encoded it i kept getting semicolon errors please help 
thanks!
https://gyazo.com/2ab0915dc88e6f4e972411fa464c02bc
https://gyazo.com/95bbe91f75ac7cb50dac942aca0dabee

**Comment by WJKH** [comment]
You don't need encode the code, use it as you get it.

**Comment by Dohab** [comment]
1- Do as @WJKH if your pc isn't public.
2- try a different encrypor.
3- check your encrypt/decrypt encoding [check this out](http://stackoverflow.com/questions/9246051/how-do-i-fix-this-missing-semicolon-syntax-error-in-javascript).

**Comment by hassanila** [comment]
@davidmann4 I told you that it was better to have semicolons -_-
