### ISSUE TITLE
Ogar is patched with default AI?

### ISSUE THREAD

**Issue by mayed505** [davidmann4/ogar-feeder-bot#279]
Seems doesnt work for me default only blind works for me i even disabled scramble cords.

**Comment by wartoz** [comment]
need a fix please

**Comment by mayed505** [comment]
@Wartoz totally agree.

**Comment by ItzLevvie** [comment]
@mayed505 Have you tried it with an older version of Ogar?

**Comment by davidmann4** [comment]
puh funny

**Comment by davidmann4** [comment]
could not find anything in the commits of Ogar 

what is the problem?

**Comment by mayed505** [comment]
@davidmann4 i found the problem i forgot to comment out the old code to the new one xD
