### ISSUE TITLE
Fancy things

### ISSUE THREAD

**Issue by SrNicolas** [davidmann4/ogar-feeder-bot#286]
I need Someone to extract the Custom spectate mode from Agar.io powerups
And then i could do something fancy

Add me on skype if u wanna help`: nicolasdelito

Spoiler: Bots following your cell from All the map :D

**Comment by MasonBurdette** [comment]
This isn't needed, I've figured out how to instantly calculate offsets.  I have 100% WORKING follow mouse bots.

**Comment by davidmann4** [comment]
GRATS

**Comment by Petterholm** [comment]
@MasonBurdette add me on skype petter.holm11

**Comment by xa** [comment]
@MasonBurdette can you post video?
