### ISSUE TITLE
Assist with bots not connecting

### ISSUE THREAD

**Issue by makandz** [davidmann4/ogar-feeder-bot#31]
Hey,

I really like this project and I want to use it! I can't seem to get them to connect with proxy or without. Possible for you to help me on Skype at makan_dey ?

Thanks,
Makan D

**Comment by zeliad-papa** [comment]
we need you try to elaborate on the problem (more info) + logs

**Comment by makandz** [comment]
1. I installed everything that was needed, the mini-map server and everything is installed correctly. I want to test the project with only 5 bots for now, so I made proxy.txt into NOPROXY. I edited the config.js to this: http://pastebin.com/dzvCP2H6
2. The issue is when I run node feeder.js P8M5R 0 (and without 0) I get only one line that says: ws://127.0.0.1:34343 connected
3. In the Minimap server it shows 1 player under anonymous connected. 

Am I doing something wrong? Thanks.

**Comment by davidmann4** [comment]
everything sound good so far :)

**Comment by davidmann4** [comment]
where is the problem ?

**Comment by davidmann4** [comment]
I added oyu in skype - you need to set config.gameServerIp

**Comment by makandz** [comment]
I don't seem to have got the request. :/ What's your Skype so I can request?

**Comment by davidmann4** [comment]
I've added makan_dey

**Comment by makandz** [comment]
Weird. Try joining this group I made with only myself, maybe I can add you there. https://join.skype.com/AgmjPdo1HdYi
