### ISSUE TITLE
Fix blind mode

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#331]
someone fix blind mode for public servers

**Comment by auxo-git** [comment]
I think this repo is dead.
But if you wanted a working blind mode download this (its that breakbot thing)
http://www.mediafire.com/download/qua25u55b3uj6zb/Break+Bot+V4.zip

ps. it doesnt matter which tampermonkey script you use

**Comment by hassanila** [comment]
Fixed here: **https://github.com/davidmann4/ogar-feeder-bot/pull/333**
