### ISSUE TITLE
No bots?/Proxy Help

### ISSUE THREAD

**Issue by Trikkstar123** [davidmann4/ogar-feeder-bot#339]
Before posting this I am not asking for proxies. IM new to this and wanted to know where to paste in new proxies in the file and also what type of proxies the ogar feeder bot uses since I have only been getting 5 bots.

**Comment by Trikkstar123** [comment]
I get this error on cmd below

C:\Users\sameer\Desktop\RealZays BOTS>node feeder.js
ogar-feeder-bot started! Join a game in Chrome with the Userscript installed.
Press CTRL + C to stop this script.
startup
server-booted-up
{ name: 'connect_server', ip: 'ws://167.114.211.162:1500' }
client requested bots on: ws://167.114.211.162:1500
HTTP ; NOPROXY
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; NOPROXY
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 202.201.125.51:9999
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 181.74.190.175:13045
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 50.63.188.25:60088
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 176.31.53.167:7777
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 172.98.189.75:31477
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 172.98.170.34:31477
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 148.223.57.45:3389
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 14.140.110.198:28637
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 166.62.97.243:18628
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 162.255.185.252:10200
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 177.224.18.100:10000
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 177.152.173.182:54032
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 180.153.87.22:10080
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 177.243.87.130:58993
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 178.151.177.24:10911
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 177.236.113.33:49357
Attempting connection to ws://167.114.211.162:1500
SOCKS5 ; 181.188.51.137:34357
Attempting connection to ws://167.114.211.162:1500
Bot_1: Connecting to: ws://167.114.211.162:1500
Bot_2: Connecting to: ws://167.114.211.162:1500
net.js:927
      throw new RangeError('port should be >= 0 and < 65536: ' + port);
      ^

RangeError: port should be >= 0 and < 65536: NaN
    at lookupAndConnect (net.js:927:13)
    at Socket.connect (net.js:904:5)
    at Socket.connect (net.js:865:37)
    at Object.exports.createConnection (C:\Users\sameer\Desktop\RealZays BOTS\node_modules\socks\lib\socks-client.js:77:16)
    at SocksAgent.createConnection (C:\Users\sameer\Desktop\RealZays BOTS\node_modules\socks\lib\socks-agent.js:59:17)
    at SocksAgent.addRequest (C:\Users\sameer\Desktop\RealZays BOTS\node_modules\socks\lib\socks-agent.js:86:10)
    at new ClientRequest (_http_client.js:139:16)
    at Object.exports.request (http.js:31:10)
    at WebSocket.initAsClient (C:\Users\sameer\Desktop\RealZays BOTS\node_modules\ws\lib\WebSocket.js:683:21)
    at new WebSocket (C:\Users\sameer\Desktop\RealZays BOTS\node_modules\ws\lib\WebSocket.js:78:18)

**Comment by SrNicolas** [comment]
U got a proxy with no port/ or port is more than 65536
