### ISSUE TITLE
Bug, After 5-10min bots stop follow me (youtube)

### ISSUE THREAD

**Issue by zeliad-papa** [davidmann4/ogar-feeder-bot#34]
https://www.youtube.com/watch?v=KpnhX8XMnZM&feature=youtu.be
00:46 purple bot not come to me

**Comment by zeliad-papa** [comment]
We need to understand the problem #34
Print Debug might add my location all the time
And see what is happening there If right location

**Comment by makandz** [comment]
I think that is happening because there was a delay between you and the server. Are you sure the you're using fast proxies?

**Comment by davidmann4** [comment]
had the bug aswell for a few times - my bet is an issue with the map server

**Comment by zeliad-papa** [comment]
this privte proxy,
and my server no big load.

**Comment by zeliad-papa** [comment]
now I run three scripts
Anyone maximum 13 Proxy
And works well

**Comment by davidmann4** [comment]
ohh wow that's funny

**Comment by davidmann4** [comment]
fixed?
