### ISSUE TITLE
WHY???

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#347]
ALL I GET IS THIS:
![why](https://cloud.githubusercontent.com/assets/15255724/14094000/68aa7ed0-f520-11e5-9eca-4a00f491c85f.jpg)
IT SEEMS IMPOSSIBLE TO FIND A BOT MOD MADE ONLY FOR OGAR SERVERS THAT ACTUALLY WORKS!!!

**Comment by imangryskills** [comment]
I get the same thing ^^ Not sure what to do...

**Comment by Megabyte918** [comment]
@Agarian add me on discord I have one for you

**Comment by sejo153** [comment]
I think you didnt dowload node

**Comment by Nick8fr32** [comment]
go i the config.js and make _line 15_ to `config.feederServer = "ws://127.0.0.1:8081";`

and then make a batch file and put this in 
@echo off
color 0a
cd server
cls
node server.js
Pause

**Comment by ItzLevvie** [comment]
@sejo153 He had node installed already.

**Comment by Agarian** [comment]
@Nick8fr32 

    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\owner\Downloads\ogar-feeder-bot-master\serve
r\server.js:1:76)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
Press any key to continue . . .

**Comment by Nick8fr32** [comment]
u did something wrong @Agarian

**Comment by ghost** [comment]
cause i downloaded a fresh one just now my bad

**Comment by Nick8fr32** [comment]
did u make config.sample to config

**Comment by ghost** [comment]
re doing so right now please wait

**Comment by Agarian** [comment]
i still get this and i did npm install 

module.js:339
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\owner\Downloads\ogar-feeder-bot-master\confi
g\feeder.js:15:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Press any key to continue . . .

**Comment by Nick8fr32** [comment]
what is the name of ur config??

**Comment by easyrider81** [comment]
like @Nick8fr32 said did you rename the config.sample.js to config.js?

**Comment by ghost** [comment]
thats taken care of but i still only get this:

![capture](https://cloud.githubusercontent.com/assets/15255724/14185667/e97596f6-f748-11e5-94fa-e708d87770f8.JPG)
- i put the UUID in the config, did npm install, renamed the files what am i missing?

does this really work on ogar servers?
also the user script doesnt allow _show mass_ to work tho

**Comment by Agarian** [comment]
the user script doesnt allow *show mass* to work tho

**Comment by Nick8fr32** [comment]
it also work in agario servers

**Comment by ghost** [comment]
i dont care about regular servers. im only worried about getting these on ogar

**Comment by Nick8fr32** [comment]
did u do the server thing i said before??

**Comment by easyrider81** [comment]
you installed the userscript into your browser right?

**Comment by Nick8fr32** [comment]
he need to change the ip on the userscript

**Comment by ghost** [comment]
yess userscript installed jeez
@Nick8fr32 what server thing? config.feederServer = "ws://127.0.0.1:8081"; i already did

**Comment by Nick8fr32** [comment]
http://pastebin.com/raw/0M8V6KZQ
download my userscript

**Comment by Nick8fr32** [comment]
then it should work

**Comment by ghost** [comment]
nope...
i keep getting _port undefined_ as shown in the screenshot above

**Comment by Nick8fr32** [comment]
omg...

**Comment by easyrider81** [comment]
you need to change server on the user script too 
![ba0193dce161ee2e34ed6c52a817a8b6](https://cloud.githubusercontent.com/assets/127005/14185990/1f607b5c-f774-11e5-8c5d-70d0c1917b5b.png)

change it to ws://127.0.0.1:8081 also

**Comment by ghost** [comment]
i dont fucking know but its annoying the hell outta me

**Comment by ghost** [comment]
also @easyrider81 its already like that

**Comment by Nick8fr32** [comment]
did u make a server batch file??

**Comment by ghost** [comment]
can someone just send me their server files???

**Comment by ghost** [comment]
and @Nick8fr32 yes i did

**Comment by Nick8fr32** [comment]
where??

**Comment by ghost** [comment]
in every folder in the server for precautionary/test measures i ran them all, none worked

**Comment by Nick8fr32** [comment]
where can i send u the files

**Comment by ghost** [comment]
try my email tommyb3751gmail.com
you can send it's file type as .zip .rar .tar .gz it doesnt matter
but .zip and .rar is best

let me know when u sent it

**Comment by Nick8fr32** [comment]
it is just saying i am not allowed to send .bat files

**Comment by ghost** [comment]
put the files in a .zip format lol its easier

**Comment by Nick8fr32** [comment]
http://pastebin.com/raw/husfRXdp

**Comment by Nick8fr32** [comment]
just do what i said in there and when u want to run the bot open start.bat

**Comment by Agarian** [comment]
i cant put filenames as *.*

**Comment by Nick8fr32** [comment]
why?

**Comment by ghost** [comment]
disregard that...

**Comment by Nick8fr32** [comment]
make a .bat file called start
and put this in

@echo off
color 0a
echo agario feeder bot
echo --------------------
echo Press enter to start the bots
pause
start server.bat
echo server is ready
echo --------------------
:start
cls
node feeder.js
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
echo CRASH!!
pause
echo --------------------
goto start

Make a .bat file called _server_ and put this in
@echo off
color 0a
cd server
cls
node server.js
Pause

**Comment by Nick8fr32** [comment]
then do this

**Comment by ghost** [comment]
STILL SAYS PORT UNDEFINED

**Comment by ghost** [comment]
why cant u email me a .zip of your files??

**Comment by Nick8fr32** [comment]
send a screenshot

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/15255724/14185667/e97596f6-f748-11e5-94fa-e708d87770f8.JPG)

**Comment by Nick8fr32** [comment]
because my script is with fb bots

**Comment by ghost** [comment]
DUDE COME ON

**Comment by Nick8fr32** [comment]
config.serverPort = 8081;

**Comment by ghost** [comment]
it is!

**Comment by Nick8fr32** [comment]
then i dont know what u can do

**Comment by ghost** [comment]
FUCK THIS

**Comment by ghost** [comment]
WHATS SO WRONG ABOUT EMAILING ME YOUR FILES?? ITS TOO EASY

**Comment by Nick8fr32** [comment]
get in discord https://discord.gg/0sQTygI0LsRslibb

**Comment by ghost** [comment]
says i must be a member

**Comment by ghost** [comment]
DM (Direct Message) me

**Comment by Nick8fr32** [comment]
then join this https://discord.gg/0vBVOXYElF6YRBPh

**Comment by ghost** [comment]
im hellcat BTW

**Comment by ghost** [comment]
and @Nick8fr32 ITS STILL NOT WORKING WHAT THE FUCK

**Comment by ghost** [comment]
THIS IS A POOR EXCUSE OF A MOD

**Comment by m-byte918** [comment]
@Agarian calm down m9

**Comment by Megabyte918** [comment]
@Agarian I have some for you but their not meant to bypass any anti-bot systems their just supposed to simply work. PM me on disc ill send them to you

**Comment by Agarian** [comment]
K

**Comment by ghost** [comment]
Im online @Megabyte918
