### ISSUE TITLE
Connecting more than 5 Bots

### ISSUE THREAD

**Issue by thisismo** [davidmann4/ogar-feeder-bot#35]
After connecting 5 Bots, the 6th says: 'Connection failed with reason: Error: connect ECONNREFUSED 151.xx.xx.xx:xxxx

**Comment by makandz** [comment]
That means it's on the next proxy and that proxy isn't working. Did you edit the proxy.txt file at all?

**Comment by thisismo** [comment]
Yes, of course. It simply means that the next bots aren't running over the proxy.

**Comment by davidmann4** [comment]
5 connections per ip is the limit
