### ISSUE TITLE
Windows VPS problem!

### ISSUE THREAD

**Issue by philw1508** [davidmann4/ogar-feeder-bot#359]
I am using a Windows 2008 r2 as a vps...and i use windows remote desktop....My problem is that when I want to play agario on my "real pc" i dont get the ip of the agario server when i run the server and feeder on my vps... but I tried it on chrome on the vps and then i got the IP OF THE AGARIO SERVER!!!! Can someone help me please? :) Thanks!

**Comment by dimamelnic** [comment]
you have to un remote computer
stick to the script on your computer
and it will work

**Comment by philw1508** [comment]
But how to stick it?
yes i run windows remote desktop

**Comment by loboere** [comment]
same , not server detected , previously detects the server but not anymore

**Comment by philw1508** [comment]
i did port forwarding but it doent work :(

**Comment by philw1508** [comment]
It's actually working with port forwarding..

**Comment by picusc** [comment]
Can you tell me how you managed to get it to work? I have a Windows server too but I can't get it to work!!
