### ISSUE TITLE
MSGPACK error with agar-mini-map

### ISSUE THREAD

**Issue by TheEpTic** [davidmann4/ogar-feeder-bot#37]
So ermm, tried running this on multiple servers yet get the same error. Any idea?

var packet = msgpack.unpack(buffer);
                                 ^

TypeError: First argument must be a Buffer
    at TypeError (native)
    at WebSocket.ws.onmessage (/home/x/agario-client/AgarClones/custom.js:267:34)
    at WebSocket.onMessage (/home/x/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (/home/x/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/x/node_modules/ws/lib/Receiver.js:537:18
    at /home/x/node_modules/ws/lib/Receiver.js:361:7
    at /home/x/node_modules/ws/lib/PerMessageDeflate.js:247:5
    at afterWrite (_stream_writable.js:346:3)

**Comment by davidmann4** [comment]
msgpack is an issue with the map server.

**Comment by davidmann4** [comment]
which version of the script / map server are you using 

we will replace the map server at some point with a custom user script because to many people have problems with the map server stuff.

**Comment by TheEpTic** [comment]
Everything the latest. Only just found out about this project from the guy who made agario-client :>

**Comment by davidmann4** [comment]
I saw that the map-server guy made an update on his side... maybe that causes problems? 

will check it once I've time for it. This could take a while - sorry

**Comment by TheEpTic** [comment]
That sound logical, as it's moaning about the packet it's receiving. Oh and that's fine! Take your time :)

Do you have an old copy of the map-server if you have time quickly? Thanks :)

**Comment by davidmann4** [comment]
hmm, maybe this helps:

https://github.com/dimotsai/agar-mini-map/releases

**Comment by TheEpTic** [comment]
My word, this mini map thing is horrible. Even those don't work on any of my systems. Some without outdated node and some with the latest node. Absolutely nothing, wow ;o

**Comment by davidmann4** [comment]
hmm yeah - this repo is still very young. make sure to favourite it and share it a lot. It already atracted a few talented programmers which contributed code.

**Comment by TheEpTic** [comment]
Will do! I really hope there's a fix for this soon, I'm also going to try and find a way round it myself :)

**Comment by clouedoc** [comment]
Use node 0.12v !!!!!!!!

Envoyé de mon iPhone

**Comment by TheEpTic** [comment]
node 0.12v? What?

**Comment by zeliad-papa** [comment]
ubuntu?
http://askubuntu.com/questions/586671/installing-node-js-through-a-ppa-does-not-fetch-the-latest-version
