### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by ZeroxYT** [davidmann4/ogar-feeder-bot#38]
If someone could make a youtube video on installation that would be great! XD

**Comment by zeliad-papa** [comment]
you need edit config and change name to config.js

**Comment by ZeroxYT** [comment]
i updated it btw

**Comment by loboere** [comment]
how to install?

**Comment by davidmann4** [comment]
read readme.md - a small guide is written there 

everything will be easier in 1 week - keep tuned and favourite the repo
