### ISSUE TITLE
Avoid other players

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#39]
bot should not run into other players

**Comment by davidmann4** [comment]
anyone has an idea how we could do this? 

maybe a new moveto(x,y) function called safeMoveToXY which always avoids other players

so maybe something like this:

*check if someone is between me and the target
*check if it has more mass than me
*if both is true make a new path 1° different - recalculate 

@Apostolique how did you solved this ?

**Comment by WJKH** [comment]
@RealDebugMonkey bot is doing much better than others.
Could you save our day?

**Comment by RealDebugMonkey** [comment]
Depends on how you prioritize what your bot's goals. In the old version of the bot I made it so it would calculate a desirability value for each food pellet we could see. It would then calculate path to each pellet and see if there was someone in the way, if there was it would eliminate it as a candidate.

Of course, that led to issues when there was no food on the screen. It would also stupidly go towards a pellet that was near a player as long as the player was not directly in the path of the food. It's a hard problem to solve.

**Comment by davidmann4** [comment]
hmm clever approach, I like it!

**Comment by davidmann4** [comment]
added in b057c9856394c066a006f8e26b5aa9e73920292f

currently avoids viruses if smart move is active
