### ISSUE TITLE
the code is doing nothing?

### ISSUE THREAD

**Issue by kittykut** [davidmann4/ogar-feeder-bot#393]
C:\Users\user\Desktop\BOTS\ogar-feeder-bot-master>node feeder.js
agario-feeder-bot started! Join a game in Chrome with the Userscript installed.
Press CTRL + C to stop this script.

This is all that comes up in my cmd, i have added a proxy and tried to run again still nothing

**Comment by Nick8fr32** [comment]
Its hard to Explain What u need to do ;(

**Comment by kittykut** [comment]
please try

**Comment by Nick8fr32** [comment]
It is the server that u use that dont work Anymore

**Comment by kittykut** [comment]
can i choose any server?

**Comment by kittykut** [comment]
i have to change it in config and userscript correct?

**Comment by Nick8fr32** [comment]
Yes and i think u Can use any vps

**Comment by kittykut** [comment]
us a vps? can you show me the server you are using?

**Comment by Nick8fr32** [comment]
ws://127.0.0.1:8081

**Comment by kittykut** [comment]
doesnt work for me

**Comment by Nick8fr32** [comment]
Okay wait 2 min i Will get on my pc to help u

**Comment by kittykut** [comment]
thank you!

**Comment by Nick8fr32** [comment]
do u know how to make a .bat file?

**Comment by kittykut** [comment]
yes

**Comment by Nick8fr32** [comment]
make a .bat file called **server**

**Comment by kittykut** [comment]
alright, done

**Comment by Petterholm** [comment]
Talk on pm

Den lørdag 9. april 2016 skrev Nick8fr32 notifications@github.com
følgende:

**Comment by Nick8fr32** [comment]
what is ur email @kittykut

**Comment by Nick8fr32** [comment]
@Petterholm sorry

**Comment by kittykut** [comment]
do you have skype

**Comment by Nick8fr32** [comment]
just send ur email

**Comment by kittykut** [comment]
skriptkitty@tuta.io

**Comment by Nick8fr32** [comment]
look at ur mail @kittykut

**Comment by kittykut** [comment]
what mail

**Comment by Nick8fr32** [comment]
i send u a mail on skriptkitty@tuta.io

**Comment by Nick8fr32** [comment]
@kittykut does it work now??

**Comment by hassanila** [comment]
you made this as a chat -_-  :-1:

**Comment by Nick8fr32** [comment]
@hassanila97 wtf dude I was just trying to help him instead of saying I'm busy all the time like u do -_-

**Comment by hassanila** [comment]
skype is better for help.

**Comment by Nick8fr32** [comment]
@hassanila97 maybe but if u send ur Skype it is the same as sending ur ip

**Comment by ItzLevvie** [comment]
@Nick8fr32 You could've used Discord or TS3.
