### ISSUE TITLE
Only get one fb bot

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#407]
when I use 20 level 60 account cookies I only get 1 fb bot no failed token

**Comment by philw1508** [comment]
Yes me too :/

**Comment by ghost** [comment]
Are yours? You need to delete cookies before leaving.

**Comment by hamido12** [comment]
i have 16 cookies  work bots fb or not

**Comment by wartoz** [comment]
i got fb bot script and fb bots works fine :p add iTwiGXDev on skype

**Comment by ghost** [comment]
I have 10 cookies and all of them works 10 mass bots come to me but I wont share how to make them all work and also I made un changeable cookies

**Comment by philw1508** [comment]
Don't trust Wartoz!! He is a scammer

**Comment by ravyn120** [comment]
fixed it

**Comment by Cyanox62** [comment]
How did you fix it?
