### ISSUE TITLE
Can Someone Make a Tutorial

### ISSUE THREAD

**Issue by SnowyTube** [davidmann4/ogar-feeder-bot#42]
I really Don't understand the Instructions if Someone can help us To Get Bots we will be Really thankful for him......

Need it Badly......

**Comment by makandz** [comment]
Instructions are on the homepage and each library has more instructions to follow. I don't understand how much more clear you want it.

If you want bots this bad, simply get Agariopowerups. They are _much_ easier to use.

**Comment by SnowyTube** [comment]
bro they r just 4 bots with just 10 mass

**Comment by SnowyTube** [comment]
i want like 100 bots of 132 mass

**Comment by SnowyTube** [comment]
bro if u can do a video tutorial that will be really helpful

**Comment by SnowyTube** [comment]
English is Not My Mother langauge so i can't really understand that

**Comment by makandz** [comment]
"i want like 100 bots of 132 mass"

Would require a level 100 Facebook account and triple mass boost set on. Every single time.

**Comment by LuffyReal** [comment]
I have

Date: Tue, 19 Jan 2016 15:19:52 -0800

**Comment by SnowyTube** [comment]
I know i m lvl 84 i will 100 after a month i can pay for triple mass just tell how to make these bots

**Comment by SnowyTube** [comment]
@luffyreal skype????

**Comment by LuffyReal** [comment]
lucasdushake my skype

Date: Tue, 19 Jan 2016 15:55:02 -0800

**Comment by SnowyTube** [comment]
Bro i mean to say if u can make a screenshot or video tutorial that would be better

**Comment by chazderry** [comment]
I agree we need a video tutorial that would be great. Did @LuffyReal  ever send you the video @SnowyTube
