### ISSUE TITLE
Multiple cookies!

### ISSUE THREAD

**Issue by DeadWarrior58** [davidmann4/ogar-feeder-bot#422]
Hello people, this is not for these bots but I still need help. I want some fb bots but out of 10 cookies only the newer works and I just updated them. Please help, i tested each of them but when i add another one the old one doesn't work anymore.

**Comment by Nick8fr32** [comment]
do u get tokens from the cookies??

**Comment by mrdrxtk** [comment]
i have 150+ cookies works

vs good elit proxy

**Comment by Nick8fr32** [comment]
@mrdrxtk where did u get it

**Comment by DeadWarrior58** [comment]
@Nick8fr32 no i don't get tokens.... how do i find them?

**Comment by JakeTDC** [comment]
How do u get tokens i mean i got 2 working i see them but i need more

**Comment by DeadWarrior58** [comment]
@JakeTDC where did you find the tokens?

**Comment by DeadWarrior58** [comment]
I tried to google : Facebook auth tokens but it was a hard tutorial, i have to register and some other stuff

**Comment by JakeTDC** [comment]
Oh  i make facebook accounts and level them up

**Comment by wartoz** [comment]
i got 180+ working cookies 17.04.16 add : iTwiGXDev on skype

**Comment by Nick8fr32** [comment]
How do u get that many cookies? @Wartoz

**Comment by wartoz** [comment]
from friends

**Comment by DeadWarrior58** [comment]
@JakeTDC  how do you get permanent tokens? PLEASE HELP

**Comment by Nick8fr32** [comment]
i dont think u can get more than 2 hours @DeadWarrior58

**Comment by DeadWarrior58** [comment]
@Nick8fr32 i can't even get 1 minute so atleast tell me for the 2 hours tokens

**Comment by Nick8fr32** [comment]
why ??

**Comment by DeadWarrior58** [comment]
because i don't have tokens

**Comment by Nick8fr32** [comment]
no u make tokens from cookies

**Comment by DeadWarrior58** [comment]
how?

**Comment by DeadWarrior58** [comment]
wait i'll send you a account

**Comment by DeadWarrior58** [comment]
//Agarbot2
  {
    "datr": "(Not wanna include)",
    "c_user": "100011818176928",
    "xs": "216%3AHqMzJLOlJmHcpg%3A2%3A1460835617%3A-1"
  },

**Comment by DeadWarrior58** [comment]
but i need a token too... it is like : 
    "token": "CAAJoMBwWJiMBAFJXgZAGzOdA9f9Q6TyZAPnBLFWMLTJkrWBPgsHZAwGW2f3GgiQxBMZBgZAnOXqTpfchZAjjZC705UTsTF2SHcUvDNicbG4MzaVvtLnyfHlaVmIpSscDoTClZBjadGqcZAg3rA0fDkYgPV4FZAjemBwZCuaSOfZBYvATyUGC7UKYwicVi2LrKHe9142sDq659IaPTAZDZD"

**Comment by DeadWarrior58** [comment]
but where do i find it

**Comment by Nick8fr32** [comment]
okay ;)

**Comment by Nick8fr32** [comment]
http://pastebin.com/raw/CV0URAA8

**Comment by DeadWarrior58** [comment]
but i want it for multiple bots

**Comment by DeadWarrior58** [comment]
for 1 bot it works but i want more

**Comment by Nick8fr32** [comment]
@DeadWarrior58 http://pastebin.com/raw/yVKd1BaP

**Comment by DeadWarrior58** [comment]
wait my friend.... where do i put the first script?

**Comment by Nick8fr32** [comment]
https://goo.gl/LtkuNL

**Comment by DeadWarrior58** [comment]
it has expired

**Comment by DeadWarrior58** [comment]
i made an account

**Comment by DeadWarrior58** [comment]
add me on discord name : DeadWarrior58

**Comment by Nick8fr32** [comment]
https://goo.gl/S3vXJ3
