### ISSUE TITLE
Why can I only connect 5 bots?

### ISSUE THREAD

**Issue by SnowyTube** [davidmann4/ogar-feeder-bot#43]
My friend successfully installed the bots but he said he just got 4 bots can sombodee explain that how to make more bots i have proxies and how i can use them

**Comment by WJKH** [comment]
Read the proxy.txt and don't open more issues with just a simple question.

**Comment by davidmann4** [comment]
you will need to use proxy servers to connect more than 5 clients to a ogar server.

**Comment by SnowyTube** [comment]
I got 50 proxies how many bots i can run on this and can explain the codes
for connecting a proxies to client

**Comment by thisismo** [comment]
Try to solve it yourself. It's not to hard. Use Google. Btw agar.io allows 5 game instances per IP, means 5 per proxy.

**Comment by SnowyTube** [comment]
@thisismo why i m Here.....

**Comment by SnowyTube** [comment]
thisismo add Me on Skype Help Me a Bit

**Comment by makandz** [comment]
@thisismo The actual number from what I know is 12. But keeping the bots at 5 each is safer then that :3
