### ISSUE TITLE
Keycode to active bots

### ISSUE THREAD

**Issue by heliocosta-dev** [davidmann4/ogar-feeder-bot#432]

**Comment by Nick8fr32** [comment]
i can make it if u help me with getting facebook acc @tweenkapy

**Comment by ravyn120** [comment]
@Nick8fr32 I'll send you 20 cookies if you make it for me

**Comment by Nick8fr32** [comment]
Do all your cookies work? @ravyn120

**Comment by ravyn120** [comment]
@Nick8fr32 yes made sure too

**Comment by Nick8fr32** [comment]
can we talk on my [discord](https://goo.gl/S3vXJ3) @ravyn120 ?

**Comment by ravyn120** [comment]
@Nick8fr32 sure

**Comment by ravyn120** [comment]
@Nick8fr32 I'm in ur chat thing
