### ISSUE TITLE
How can I change bots split control like it's for E .

### ISSUE THREAD

**Issue by piyushdevcode** [davidmann4/ogar-feeder-bot#440]
I tried by changing the code but it didn't helped me .plz if anyone knows help me

**Comment by David1ali12** [comment]
easy on scripte case is 69 change to another case as you want stop running on ur pc agario is lagging alot

**Comment by piyushdevcode** [comment]
How can I make it to "T"

**Comment by ghost** [comment]
Go to userscript and find the javascript code E and modify

**Comment by David1ali12** [comment]
change case 69 to   84 have fun XD

**Comment by piyushdevcode** [comment]
Thnx martinali
