### ISSUE TITLE
Run bots on someone else's computer from yours?

### ISSUE THREAD

**Issue by Cyanox62** [davidmann4/ogar-feeder-bot#446]
Is there a possibility that I can run my bots through a VPS to a friend on Skype's computer? I mean to control them and run them through a VPS on my computer, but have a friend with the userscript installed and everything actually receive the bots? Any help is appreciated.

**Comment by Qasimmodo** [comment]
Yes. edit config.js and set the server to ws://bots.myservers.io:8081 then, locate the userscript and edit the userscript and also set it to ws://bots.myservers.io:8081 . You can use "find" (CTRL + F) to look for it, just search for ws:// or 8081 and you'll probably find it. Then simply give him or anyone in the future your userscript, get him to give you his UUID, put it in config.js. Then run the server-sided script. 

Sorry if that was confusing, hope I helped.

**Comment by Cyanox62** [comment]
What do you mean my run the "server-sided" script? Also, do i need to run this in a VPS or can i do it from my PC? Also do i need to portforward? And if so what ports?

**Comment by Cyanox62** [comment]
Nevermind, i got it :)
Thanks

**Comment by Qasimmodo** [comment]
If it's been resolved close this ^_^
