### ISSUE TITLE
Set Max amount of bots

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#45]
I want to use like 8000 proxies but i want to set max bots to 100. I don't want to delete proxies. And some proxies may not work so it might crash. Please fix it so it just skips the broken proxies and doesn't make it crash.

**Comment by makandz** [comment]
Yeah it's true about the crashing part. If there are a lot of proxies that don't work, you get hit with an X Coordinates error.

**Comment by davidmann4** [comment]
closed with fdd2f2bccab545feb887ec1f3bea9bfef02cc358
