### ISSUE TITLE
Trading Cookies

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#450]
i'll give someone 79 working FB cookies for 30+ FB cookies

message me on skype:

**Comment by nicolaspielte** [comment]
@ravyn120 add me nicolaspielte (rαwq.) i have 70 Facebook cookies

**Comment by hassanila** [comment]
What's the catch there hah,  I give you 30 and you give me 79.. fuck off (if you are scamming)

**Comment by easyrider81** [comment]
i guess he will still use his 79 plus your 30 and you get your 79. sharing is caring.

**Comment by ravyn120** [comment]
No catch I just want more fb cookies

**Comment by ravyn120** [comment]
I'll go first if you want @hassanila97

**Comment by nicolaspielte** [comment]
@hassanila97 trade Cookies? how many cookies do you have?

**Comment by ravyn120** [comment]
@nicolaspielte I'll trade I have 79

**Comment by nicolaspielte** [comment]
@ravyn120 trade Cookies i have 70? add me nicolaspielte (rαwq.)

**Comment by hassanila** [comment]
@nicolaspielte I have 200+

**Comment by nicolaspielte** [comment]
@hassanila97 traden? :D i have 70

**Comment by hassanila** [comment]
I got em from some friends...  so idk.. they dont want me to share :D

**Comment by nicolaspielte** [comment]
:( still need cookies pity

**Comment by hassanila** [comment]
![2016-04-22 16_57_35-agar io](https://cloud.githubusercontent.com/assets/15068696/14750008/e6942b60-08c2-11e6-886b-307a79ab225a.png)

Fuck agar.io I cant login/logout

**Comment by nicolaspielte** [comment]
@hassanila97 nice <3 <3 <3
![unbena77nnt](https://cloud.githubusercontent.com/assets/18007730/14750090/4cc1d37e-08c3-11e6-93f4-0ab85d5b9e4a.png)

**Comment by hassanila** [comment]
123.000 players in EU..   most are bots :P

**Comment by nicolaspielte** [comment]
xD

**Comment by nicolaspielte** [comment]
@hassanila97 will not you give me a few more cookies? :D

**Comment by hassanila** [comment]
Sry I can't, otherwise I have no friends :D

On 22 April 2016 at 20:32, nicolaspielte notifications@github.com wrote:

> @hassanila97 https://github.com/hassanila97 will not you give me a few
> more cookies? :D
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/davidmann4/ogar-feeder-bot/issues/450#issuecomment-213544861

## 

_Med vänliga hälsningar_
_Hassan_

**Comment by nicolaspielte** [comment]
then I'll thy friend :D  OK hmm

**Comment by David1ali12** [comment]
hassan answer on skype

**Comment by Lukkez** [comment]
Can you give this script ? @hassanila97 not server, just UI

**Comment by nicolaspielte** [comment]
@hassanila97 can you sent me your Bots :D that would be really cool of you: D against 70 cookies? pls.

**Comment by nicolaspielte** [comment]
@hassanila97 can you me sent me your Stop script?

**Comment by hassanila** [comment]
I didnt make it yet to work from node.js, what I've done is to restart the script and wait for connection using batch on Windows.. and I have a completely different version of bots.. not online and it's private. so..

**Comment by nicolaspielte** [comment]
@hassanila97 sent me :D

**Comment by Lukkez** [comment]
@hassanila97 You can't send the ui of bot counter etc?

**Comment by hassanila** [comment]
I can when I have time.. cuz  it requires me to edit much of the feeder and userscript

**Comment by nicolaspielte** [comment]
@hassanila97 can sent me the Stop and Start script pls
![image](https://cloud.githubusercontent.com/assets/18007730/15039247/d069674a-12ab-11e6-89c8-8d7892016da4.png) skype Name nicolaspielte (rawq)
