### ISSUE TITLE
FB bots disconnect issue & collect mass mode.

### ISSUE THREAD

**Issue by CupidStunts** [davidmann4/ogar-feeder-bot#456]
well seen as though no one gives anything for free on here. i want to add these last 2 issues that bug me with the bots. nearly all FB bots disconnect after about 10-20 mins & i want eat/collect mass mode. with these last 2 things i will be content & happy. for trade i have 99 FB cookies. all made by me & only i have them. a good 30 of them are 43 mass & the rest will lvl up as time goes by :) lowest lvl is like 11 last i checked. i will not send cookies first as idk if you can be trusted so i will just leave this here

![ttttttttttttttttt](https://cloud.githubusercontent.com/assets/18208728/14759203/5f12acd0-0911-11e6-9472-7f211c02404e.jpg)

send me the code & ill send you the cookies...simple! dont try scam me :/

**Comment by Martinali12** [comment]
so if I fix it u how many cookies u give me ?

**Comment by David1ali12** [comment]
there nothing wrong with code so delete this post before someone scam u lol

**Comment by CupidStunts** [comment]
yah the disconnect issue is most likely proxies.sometimes they are ok. sometimes they just dissapear..
no one will scam me lol. ill want to test the code first lol. i know there are some scammers on here so i put it in to say dont bother trying lol

**Comment by Martinali12** [comment]
so If I fix disconnect you will give 100 cookies ?

**Comment by ravyn120** [comment]
Hey @CupidStunts I have the mass collecting feature add me on skype: ravyn812

**Comment by JakeTDC** [comment]
Change the defualt to blind easy pzy:) 
and btw ive got 100 working proxies (HTTP)
AND THEY NEVER disconnect

**Comment by CupidStunts** [comment]
@ravyn120 ill add you on skype
@JakeTDC the blind mode dont work lol & im just using free proxies so i aint really bothered. i could setup my own proxys with dante or squid but dont see the point.

**Comment by Enderbel** [comment]
I can buy the tokens work ?

**Comment by ravyn120** [comment]
Holy  crap i just noticed something i have 350 fb tokens damm

**Comment by DeadWarrior58** [comment]
@JakeTDC  i really need your help... how do i make a lot of cookies i can only make one but i doesn't work because i disconnect from facebook so i play with registered account

**Comment by DeadWarrior58** [comment]
@JakeTDC  i don't beg for cookies (because i don't know how to use them) nor tokens the only thing i want is help... and if you send me 1 token .... then... thx... but that's not the point i want my own accounts pls help me

**Comment by santabis** [comment]
Give me cookie, i help you)?
skype: facebook:222415918146688
bots not disconecting)

![image](https://cloud.githubusercontent.com/assets/17793119/14764821/882bb4ba-0a09-11e6-9d2b-975f4434bf6d.png)

**Comment by sejo153** [comment]
@JakeTDC How do you using HTTP proxies? 
@ravyn120 wanna share for share?

**Comment by Nick8fr32** [comment]
just type #HTTP and then the proxies under @sejo153

**Comment by sejo153** [comment]
Ok i'll try
