### ISSUE TITLE
need help with fb bots small question.

### ISSUE THREAD

**Issue by mastkilxp** [davidmann4/ogar-feeder-bot#458]
so i got around 30 facebook bots :D and it does say all 30 fb bots connected succesfully and says 30 token so it works. but when i do go in-game the bots only comes in small ones (10mass) i cant figure out why the bots arent working yes the fb cookies are mine i got from 30 friends fb cookies they didnt mind what i did wrong.

**Comment by CupidStunts** [comment]
update agario client

**Comment by Cyanox62** [comment]
How/where do you update it from? I have 60 working tokens but none of them show up in game. Would be great to fix this.

**Comment by mastkilxp** [comment]
so i updated agario client but now in the console i get this error spammed really fast [typerror: cannot read property 'name' of undefined]

**Comment by mastkilxp** [comment]
any fix for this please?

**Comment by Cyanox62** [comment]
I have the same issue https://github.com/davidmann4/ogar-feeder-bot/issues/463

**Comment by CupidStunts** [comment]
https://github.com/pulviscriptor/agario-client

**Comment by mastkilxp** [comment]
so i downloaded the file do i have to replace to replace my files with those files?
i really dont get how to update it cus it only tells me how to download it and install it

**Comment by easyrider81** [comment]
Just replace the files in the node_modules/agario-client folder. npm install agario-client on the node CMD is easier.

**Comment by mastkilxp** [comment]
ok thanks it worked but i get still this error sometimes [typerror: cannot read property 'name' of undefined] any fix for that or?

**Comment by easyrider81** [comment]
screen print the full error here.

**Comment by mastkilxp** [comment]
here it is http://imgur.com/4aEyiyB hope you can figure it out it spams really quickly

**Comment by KyraCloud** [comment]
Easyrider81 can you add me on skype i dont know how to update agario client

**Comment by easyrider81** [comment]
Comment out line 530 in agario-client.js and get better proxies.

what's your skype @KyraCloud

**Comment by mastkilxp** [comment]
:D worked thankyou so much btw can you add me on skype?:mastkilxp

**Comment by easyrider81** [comment]
added.

**Comment by Cyanox62** [comment]
Easyrider, please add my skype: zpasswordz
