### ISSUE TITLE
what should I do?

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#468]
I have 357 FB tokens all working and I don't know what to do with them because FB bots don't work for me

**Comment by santabis** [comment]
Give me
xs
dara r
c user
i help you))
Skype: facebook:222415918146688

**Comment by ravyn120** [comment]
@santabis fuck off

**Comment by santabis** [comment]
@ravyn120 -_-

**Comment by ravyn120** [comment]
@santabis you just want cookies...

**Comment by sejo153** [comment]
yea i have about 30 and using bots on c9.io and get bots about 200 but no fb :/

**Comment by Nick8fr32** [comment]
ravyn get on discord i can help u

**Comment by santabis** [comment]
@santabis i help you, and you me cookie
Well there is no way

**Comment by ravyn120** [comment]
@Nick8fr32 okay

**Comment by ravyn120** [comment]
@Nick8fr32 cant Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient.

**Comment by Nick8fr32** [comment]
i send u a friend request
