### ISSUE TITLE
Share usercript with restar button

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#470]
If someone have...

**Comment by Nick8fr32** [comment]
i made one that restarts when u press **s**

**Comment by santabis** [comment]
add to cookie) for facebook bots)
https://docs.google.com/forms/d/11_w6BpkgSdD9mqWtnY7OjuxUfDJCAIdA_9Nyf5mqUiw/viewform#responses

**Comment by sejo153** [comment]
@Nick8fr32 wanna share
@santabis yea sure, have my own why should use yours :3

**Comment by Nick8fr32** [comment]
@sejo153 it is already shared [here](https://github.com/davidmann4/ogar-feeder-bot/issues/420)

**Comment by sejo153** [comment]
@Nick8fr32 i dont understand, can u ss me or something ?

**Comment by piyushdevcode** [comment]
Does this work with vps too

**Comment by sejo153** [comment]
close
