### ISSUE TITLE
What is ws://104.236.100.252:8081 used for?

### ISSUE THREAD

**Issue by Luka967** [davidmann4/ogar-feeder-bot#476]
I've locally made another line of defense against bots on Ogar, and I needed to actually test it. So I picked this up. However I'm struggling to find out why doesn't the userscript work.
I've went to F12 mode and saw this error:
`VM3781:6 GET http://`**`104.236.100.252:8081`**`/socket.io/?EIO=3&transport=polling&t=LH9qBfT net::ERR_CONNECTION_REFUSED`.
Everything else seems to work fine.

So what is that IP used for?

**Comment by ItzLevvie** [comment]
That is the feeder server.

**Comment by ItzLevvie** [comment]
1) Make sure you've changed ```var socket = io.connect('ws://104.236.100.252:8081');``` to ```var socket = io.connect('ws://127.0.0.1:8081');``` (which can be found at https://github.com/davidmann4/ogar-feeder-bot/blob/master/agario-feeder-bot.user.js#L84)
***
2) Make sure you've changed ```config.feederServer = "ws://104.236.100.252:8081";``` to ```config.feederServer = "ws://127.0.0.1:8081";``` (which can be found at https://github.com/davidmann4/ogar-feeder-bot/blob/master/config.sample.js#L15)

**Comment by Luka967** [comment]
Ah, it worked. Thanks
