### ISSUE TITLE
Give a script for pellet eating function for bots 

### ISSUE THREAD

**Issue by piyushdevcode** [davidmann4/ogar-feeder-bot#480]
Any help regarding this is appreciated

**Comment by CupidStunts** [comment]
got skype?

**Comment by wartoz** [comment]
cupidstunts have you the script ? my skype : iTwiGXDev

**Comment by CupidStunts** [comment]
i have it yeah :)

**Comment by piyushdevcode** [comment]
Cupid stunts Skype me at -piyush2510001

**Comment by wartoz** [comment]
cupid add me again i canceled the request skype  : iTwiGXDev

**Comment by CupidStunts** [comment]
added you both.. i think

**Comment by piyushdevcode** [comment]
Yup

**Comment by CupidStunts** [comment]
@gamer2510 have dude :)

**Comment by CupidStunts** [comment]
fun

**Comment by piyushdevcode** [comment]
Ur the Cupid stunts

**Comment by CupidStunts** [comment]
@gamer2510  lol. is that an insult or a compliment?
