### ISSUE TITLE
FB Bots cant connect

### ISSUE THREAD

**Issue by KyraCloud** [davidmann4/ogar-feeder-bot#481]
i tested this with normal and with fb bots when i use fb bots they cant connect to the server but with normal bots they can i dont know why someone help me?

**Comment by SanjaySasimandir** [comment]
@KyraCloud Hey, First make sure that your cookies are working. You can see that when the bat file starts up. If it say failed to get toke it means the cookies are bad. If your cookies are working, its probably the dead proxies. So make sure that you are using latest working proxies. Get proxies from sites like http://proxybag.blogspot.com/ or http://www.vipsocks24.net/ . I use both of them and they have very good proxies . regularly update your proxies to get a good number of bots.

**Comment by KyraCloud** [comment]
@nfsboy101 Thanks the cookies are working ill try to check for new proxies, also is it normal to not have tokens in the fb manager?

**Comment by KyraCloud** [comment]
@nfsboy101 oh also where do i get more cookies or do i jusr create accounts like crazy.

**Comment by Nick8fr32** [comment]
@KyraCloud u cant create that Many acc its gonna ask for a phone nummer

**Comment by KyraCloud** [comment]
@Nick8fr32 i have over 40 phone numbers i use an app.

**Comment by Nick8fr32** [comment]
Yea i know u Can use some sites to get that to but Maybe Someone already used all of them

**Comment by KyraCloud** [comment]
@Nick8fr32 lol thats not what i mean theirs a web site where you can create email just by entering a name and then i use those email to create a phone number using and app #unlimited cookies

**Comment by Nick8fr32** [comment]
Can u help me with that?

**Comment by KyraCloud** [comment]
@Nick8fr32 sure first let me find the email creating  site :)

**Comment by KyraCloud** [comment]
@Nick8fr32 you have skype?

**Comment by Nick8fr32** [comment]
no but i have [discord](https://goo.gl/bAer3k)

**Comment by KyraCloud** [comment]
@Nick8fr32 whats ur name

**Comment by sejo153** [comment]
@Nick8fr32 When i create accounts, i use fake phone number :D

**Comment by Nick8fr32** [comment]
U need to confirm ur number so how

**Comment by sejo153** [comment]
on gmail it dont require that i think
