### ISSUE TITLE
question about fb cookies

### ISSUE THREAD

**Issue by mastkilxp** [davidmann4/ogar-feeder-bot#483]
so i want to get a few more fb cookies. atm i got 23 working but i want to get atleast 50 fb bots. so does this work? i create like 20 more fb accounts take their cookies and paste them in my script? is that going to work? cus cookies? cache? idk can anyone please explain. any information will be appreciated.

**Comment by CupidStunts** [comment]
yes you create new FB accounts. copy c_user,,,,datr,,,,,xs into FBmanager. make sure that you have good proxys tho. http are best really they last longer

**Comment by CupidStunts** [comment]
be sure to leave the account logged in tho & just dlete the cookies

**Comment by ghost** [comment]
I use HTTP goods for the fb, and SOCKS for the normals, It is just as well

**Comment by mastkilxp** [comment]
hmm i dont get it? so i created 5 accounts and did it like this but didnt work out.
1. i created the account player agario lvl them to lvl 3
2. i copy those cookies from that user after they are lvl 3.
3.pasted them in FBmanager.
4. trying them but it says still 23/23 while i just added 5 more accounts :/ i dont understand how u meant to do this? 'leave the account logged in & just dlete the cookies' i dont understand pls explain or skype:mastkilxp and thanx for the tip i try use HTTP proxies :)

**Comment by Nick8fr32** [comment]
u need to delete the cookie before u logout of the acc @mastkilxp

**Comment by Nick8fr32** [comment]
forget it XD

**Comment by mastkilxp** [comment]
but doesnt that remove the cookies from working?

**Comment by Nick8fr32** [comment]
no i do it in that way

**Comment by mastkilxp** [comment]
k thankyou :D gonna try it. message soon the result thx so much already!!

**Comment by mastkilxp** [comment]
you got to delete the cookies from the editthiscookie right?

**Comment by Nick8fr32** [comment]
i dont use editthiscookie i just go  in agario>f12>resourse>cookie>facebook copy it all and find the c_user, datr and xs. then i click on cookie>www.facebook.com  and press clear

**Comment by mastkilxp** [comment]
k thx

**Comment by mastkilxp** [comment]
i just gotta be sure sorry. so after i do clear in agario facebook cookies, i can just create a new acc again and repeath the steps? and it should work?

**Comment by Nick8fr32** [comment]
yes @mastkilxp ;)

**Comment by KyraCloud** [comment]
@CupidStunts is their a way to log into mutiple fb account i can only have 1fb account logged in at a time.

**Comment by CupidStunts** [comment]
when you got the cookies..just dlete them then facebook still thinks its logged in :)
thats what i do & it works

**Comment by mastkilxp** [comment]
ok thanx but is it normal you can only create 3 facebooks? or is it 3 facebooks a day? idk? but anyway i cant use HTTP proxies cus the script only supports socks5 :( any fix?

**Comment by mastkilxp** [comment]
can anyone please add me on skype?: mastkilxp i need some help

**Comment by mastkilxp** [comment]
with the script
