### ISSUE TITLE
Complete new problem

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#486]
Now i cant use bots as in the user script isnt connecting to the feeder script

**Comment by CupidStunts** [comment]
hydra you got skype.

**Comment by CupidStunts** [comment]
ill give you my script just give me your uuid & you will be good to go

**Comment by ghost** [comment]
yea ClassicAnon

**Comment by CupidStunts** [comment]
k ill add now

**Comment by ghost** [comment]
i meant classictoxin\* sorry

**Comment by CupidStunts** [comment]
lol

**Comment by CupidStunts** [comment]
you got it?
