### ISSUE TITLE
Token Generator?

### ISSUE THREAD

**Issue by DeadWarrior58** [davidmann4/ogar-feeder-bot#490]
Can someone make a token generator? You put for example 10 cookies and it creates a file with the tokens like this : 

Tokens : 
   "token1",
   "token2",
   "token3"

Thank you,
DeadWarrior58

**Comment by Nick8fr32** [comment]
@DeadWarrior58 i have it

**Comment by DeadWarrior58** [comment]
@Nick8fr32  send it on discord

**Comment by Nick8fr32** [comment]
Later
