### ISSUE TITLE
how do i setup HTTP proxies instead of socks5?

### ISSUE THREAD

**Issue by mastkilxp** [davidmann4/ogar-feeder-bot#496]
does anyone know this? how do i change from SOCKS5 to HTTP proxies? pleas let me know how i should do it.

**Comment by easyrider81** [comment]
Just put #HTTP in the proxy list file and your http proxies underneath. This is all stated in the proxy-sample.txt file.

**Comment by mastkilxp** [comment]
alright thank you so much :)
