### ISSUE TITLE
Facebook bots not working

### ISSUE THREAD

**Issue by Flathe** [davidmann4/ogar-feeder-bot#498]
Hey guys,

I tried to use Facebook bots, but all token failed ... I tried with new Fb account cookies, same error

Can someone help me ? 
Thx

**Comment by mastkilxp** [comment]
did you logged in to your fb account and copy the cookies and paste and logged out and so on?
cus if thats how u did it its wrong u got to copy the cookies place them in FBmanager then go in agar.io
f12>recourses>cookies>facebook.com and clear those after u cleared them in agar.io then log out. then the internet web idk still thinks the account is online. for anymore help message me at skype:mastkilxp i help you out with this noproblem :)

**Comment by Flathe** [comment]
Oh okay dude, thanks a lot !!
