### ISSUE TITLE
Using multiple proxies in one instance does not work

### ISSUE THREAD

**Issue by WJKH** [davidmann4/ogar-feeder-bot#5]
There's some problem when you try load more than one proxy.

I have tried all the proxy one by one and works fine, then try the whole list and...
Failed to request server (error=REQUEST_ERROR, error_source=Error: connect EHOSTUNREACH)

I assume that the format of the proxy list is IP:PORT line break IP:PORT...

**Comment by davidmann4** [comment]
yes thats true - did not figgured out the reason behind this - maybe a bug in @camilleeyries 's lib I am using ... others reported the same issue aswell... you can run multiple instances like this:

node feeder.js abc123 0
node feeder.js abc123 1
node feeder.js abc123 2
node feeder.js abc123 3

we need to fix this - if you found a solution please make a pull request

**Comment by davidmann4** [comment]
you also can put a NOPROXY line into your socks.txt to use your local ip

**Comment by davidmann4** [comment]
fixed in newest version
