### ISSUE TITLE
Botz wont connect (c9.io)

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#506]
Past night i use them everything was working fine
[PICTURE](http://prntscr.com/axykm4)
Changed server in tampermonkey and config.
Dont know why wont work.

**Comment by piyushdevcode** [comment]
Ur workspace r private lol

**Comment by piyushdevcode** [comment]
Don't show ur username dude

**Comment by piyushdevcode** [comment]
Do u have skype

**Comment by sejo153** [comment]
it used to work like this, but i fix ty
