### ISSUE TITLE
BotCount issue

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#526]
Maximum bot count for me is 1000, and I have put SOCKS5 and #HTTP proxies for the bots, fully checked.

onboardingtime = 0
botsperip = 2

I run the bots, and i'm only getting a count up to 45 and then it lowers down, what is causing this?

**Comment by sejo153** [comment]
I dont even check proxies, i put only socks five about 500 proxy (because i dont check them) 
onboarding timer 40
bots per ip 3
And get about 150 sometimes 200 (but then they start lagging) on [c9.io](https://ide.c9.io)

**Comment by ghost** [comment]
yeah if I go over 200, it lags.
and it gives 100 bots, thanks.
