### ISSUE TITLE
How do you start bots in a different Operating system? 

### ISSUE THREAD

**Issue by 0katz** [davidmann4/ogar-feeder-bot#532]
Making this project for only windows is very limiting, there's Linux and Mac users that have a different file system for files, I can't  run start.bat from Linux because it's not supported I even tried a third party application "Wine cmd " which gives me a DOS command prompt but it still missing dependencies. Can start.bat be implemented in the Userscript so the browser loads them?

**Comment by CupidStunts** [comment]
you start the server & feeder in node on linux....the same way you do on windows... on mac idk but you can run it from a c9.io free vps

**Comment by 0katz** [comment]
I didn't look at the code under start.bat before posting this question. It's just initializing the f.js file,This issue can be closed. For Linux users install node from github and the OpenSSL dependency for crypto support.
