### ISSUE TITLE
Can anyone give opponent mass viewing script?!!

### ISSUE THREAD

**Issue by piyushdevcode** [davidmann4/ogar-feeder-bot#539]
Please do not ask for proxies
Please do not talk about cheating on public servers.

**Comment by CupidStunts** [comment]
-    window.agar.hooks.drawCellMass = function(cell, old_draw) {
  -     if(cell.size > 20) return cell;  
  -    }
  - 
  -    window.agar.hooks.cellMassTextScale = function(cell, old_scale) {
  -    }
  -   

its already in PR's

**Comment by piyushdevcode** [comment]
Thnx my bro
