### ISSUE TITLE
Auto detect agario party ip address

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#54]
I don't want to continue changing the agario server ip each time I join a new server. Please add an auto detector. I know that run start shows up change, u should add it to node feeder.

**Comment by davidmann4** [comment]
good stuff!

**Comment by makandz** [comment]
This can be added into the userscript very easily. @davidmann4 if you can get the userscript done, we can decode the main Agar.io script to see how it calls the server IP and send it to the server automatically.

**Comment by WJKH** [comment]
As far as I know, a server have many rooms.
Then we use party key for bots or friends to play in the same room.

You don't need look at main.out.js to get party key, you can take it from URL or party box.

**Comment by ghost** [comment]
@MastaCoder 

http://pastebin.com/raw/zZmNX5Hm

**Comment by KingMatt123** [comment]
What is that code suppost to do?

**Comment by makandz** [comment]
@davidbigglehorn1995 Is that the Agar.io main_out.js decoded or just Agar-clones main_out.js?

**Comment by WJKH** [comment]
@MastaCoder I didn't compared the code but it seems or at least have some code used at main_out.js
BTW.. main_out.js isn't encoded.

**Comment by makandz** [comment]
@WJKH the normal Agar.io one is.. http://agar.io/main_out.js

**Comment by WJKH** [comment]
Yes, I know and it's not encoded.
Goto http://jsbeautifier.org/ and paste the code there if you want get a more readable code.

**Comment by davidmann4** [comment]
done
