### ISSUE TITLE
HTTP proxy error

### ISSUE THREAD

**Issue by anonymousxxx02** [davidmann4/ogar-feeder-bot#541]
when i use http proxy i get this error
`Connection Failed: Error: unexpected server response (404)`
PLEASE HELP

**Comment by DylanIssa2** [comment]
Then the proxy is not correct. 404 means "not found".

**Comment by anonymousxxx02** [comment]
@Anaphylaxis but i check the proxy and they are working

**Comment by hassanila** [comment]
That error means the proxy doesnt support websockets...

**Comment by anonymousxxx02** [comment]
@hassanila97 do you know how to fix that???

**Comment by easyrider81** [comment]
yeah, get different proxies

**Comment by hassanila** [comment]
**Dont use HTTP proxies as the almost always dont support Websocket protocol.... use only SOCKS4 and SOCKS5 proxies and you will be good**

**Comment by anonymousxxx02** [comment]
@easyrider81 different http proxy or SOCKS4/5 ??

**Comment by anonymousxxx02** [comment]
Ok thanks guys for your help
