### ISSUE TITLE
how to login to agar account with cookies c-user,-datr,xs like bots do

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#545]
If I want to check my bot lvl or my bot skin and without going to log in on facebook I mean loginng with cookie possible and how THX

**Comment by ravyn120** [comment]
Uhh I think you can switch them in agar.io in inspect element

**Comment by SanjaySasimandir** [comment]
You need to edit the cookies using inspect element and then save the html file. and the run it. I think this would work.

**Comment by sukass** [comment]
use editthiscookie, or you could just use agario-client. it can check level afaik. good luck
