### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by chazderry** [davidmann4/ogar-feeder-bot#55]
You need to make a video tutorial to make sure people do not mess up the installment.

**Comment by WJKH** [comment]
Sure and we will upload it to Youtube :D
https://github.com/davidmann4/agario-feeder-bot#how-to-install-and-use

**Comment by makandz** [comment]
I don't get why everyone needs a video. The instructions are perfectly clear on the README.md. This script isn't for people that don't know there way around Node.js..
