### ISSUE TITLE
Restart program after crash, or make it stop crashing.

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#56]
I'm using about 100 proxies on average. Because some of them don't work, they crash the program and I have to run node feeder.js again. Please fix this as I want to leave a bot on playing with these feeder bots overnight. Atleast make the program relauch after it has crashed!

**Comment by AmazingGamerBoy** [comment]
100 proxies*^^^

**Comment by AmazingGamerBoy** [comment]
some*

**Comment by davidmann4** [comment]
error message? 

how much RAM does your machine has ?

**Comment by WJKH** [comment]
Used it for a long time and never crash.
Better find some good proxy, because 100*5=500

**Comment by KingMatt123** [comment]
I have 6gb ram on my vps. And I'm using in average 100 to 200 proxies and I font want to check all of them

**Comment by KingMatt123** [comment]
Dont*

**Comment by ghost** [comment]
@WJKH which proxy provider would you recommend?

**Comment by WJKH** [comment]
Run your own proxy, better and cheap.

If you have a VPS just get some IP from your provider and run as many as you need.
Anyway 100 FB bots is crazy.

**Comment by makandz** [comment]
I know why it does it. When you have too many proxies that don't work, you get hit with an error some of them. Also some proxies tend to send a different packet then what the server understands so it crashes right on the spot. Look for the number it crashes at and remove the proxy for those batch of bots.

**Comment by KingMatt123** [comment]
Here is a crash image with the server on top
![pic](https://cloud.githubusercontent.com/assets/15712937/12527931/cea4aa0e-c1da-11e5-989a-b1d88d30d68a.png)
