### ISSUE TITLE
THE END of BOTS 

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#562]
# https://agar-server-1-party-privatebots.c9users.io/ priavte server like ruglar like agar   join to play

**Comment by wartoz** [comment]
there is nothing on your website

**Comment by wartoz** [comment]
No application seems to be running here!

**Comment by wartoz** [comment]
turn in public

**Comment by ghost** [comment]
it works now lol
srry I was updating

**Comment by GGsP839X** [comment]
Share the code for the bots with us/me? Would help a lot to develop a feeder bot for agar.io again :+1:

**Comment by ghost** [comment]
this private server I cant do anything for bots :/

**Comment by GGsP839X** [comment]
I won against your bots :ghost:

**Comment by Qwerliety** [comment]
.....
\]\;.wokhuwkgjhwagkheraghlkjfhgkjawbtlkjbd;gjvhjhbkjahrktjfkjejrhg
djghdjfh,ksjrgge
fuck you

**Comment by ghost** [comment]
@Qwerliety  fuck you too kid
