### ISSUE TITLE
old agar.io is back????

### ISSUE THREAD

**Issue by anonymousxxx02** [davidmann4/ogar-feeder-bot#564]
changelog:
Reverted game back to the state it was a few days ago. I feel like there's a better way to add features without unbalacing the game, so I'll try that out soon.

There might be a Oceania server coming if there is interest. A South American server is planned but we're still trying to find a suitable host there.

A party system is in the works.

**Comment by imangryskills** [comment]
What does this mean?

**Comment by anonymousxxx02** [comment]
go check agar.io Changelog

**Comment by ghost** [comment]
that what is says Support: support [at] agar.io
Business inquiries: biz [at] agar.io
Please refrain from sending emails that aren't necessary, I receive a lot of emails already (seriously, a lot). Feature request should go to reddit.com/r/agario.
I apologize if I don't reply to your email, be assured that I have read it, but I don't have time to reply to all of them.

**Comment by anonymousxxx02** [comment]
sorry my fault..i read it from bottom

**Comment by ghost** [comment]
:/
