### ISSUE TITLE
Bots are officially back!!!

### ISSUE THREAD

**Issue by anonymousxxx02** [davidmann4/ogar-feeder-bot#572]
Hi guys..i just find out that clientm.pw bots are back

**Comment by 2368432172** [comment]
Hi, is there any free bots that work now? Thanks

**Comment by anonymousxxx02** [comment]
@2368432172 no

**Comment by ghost** [comment]
same the agario lobbies full of clientm.pw bots

**Comment by RaxBoon** [comment]
Hello eh investigates and told me to run bots need to update the ip manually as you do that?

**Comment by anonymousxxx02** [comment]
@RaxBoon even if you update ip manually bots will not work...agario client dont work anymore

**Comment by RaxBoon** [comment]
ok tanks you

**Comment by SharkFinProductions** [comment]
YAY
