### ISSUE TITLE
Restart crashed program

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#58]
I sometimes use a lot of proxies that don't work and I don't have time to check then. It would be really good if the crashing problem was solved. If not, can someone please give me a file like a bash file to restart the program immediately after it crashes?

**Comment by makandz** [comment]
You can make a script that loops the function. I know this can be done on Linux but not sure about Windows.

**Comment by iNewLegend** [comment]
linux bash:
while true; do
command //put your command
done

**Comment by davidmann4** [comment]
use a bash script mentioned above
