### ISSUE TITLE
anyone can make me macro script?

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#588]
I need for tricksplit, doublesplit and feed. Thanks

**Comment by Ben-Lazrek-Yassine** [comment]
1-kys
2-this is not a request repo
3-get what ever u want from here https://greasyfork.org/fr/scripts/by-site/agar.io
4-GTFO :)

**Comment by AlexandriteErikParacelsus** [comment]
@bangana tru
