### ISSUE TITLE
problem with fps in agar, please help

### ISSUE THREAD

**Issue by sejo153** [davidmann4/ogar-feeder-bot#589]
I know this is not anything about the bots or idk but im asking for help.

Here are mine laptop specs:
processor: core 2 duo T5670 1.80GHz running 64bit windows 7 system
ram memmory: 2GB
grapichs:Mobile Intel(R) 4 Series Express Chipset Family - 64MB

Grapich card seems prety bad, but it shouldnt lag that much

I got 40-50fps if no one is near my cell, and if it is u got like 30-35fps

Thanks :))

**Comment by polarbear2g** [comment]
It should lag that much i have a 4duo 4 gb ram and get 30fps, i upgraded my graphics card and now it is 100fps
