### ISSUE TITLE
Facebook authentication has been patched.

### ISSUE THREAD

**Issue by makandz** [davidmann4/ogar-feeder-bot#59]
I'm making this so no more duplicates pop up. Facebook authentication has been patched by Moneyclip. If you have Facebook authentication turned on then it will only spawn one bot and disconnect all other bots. 

There is another issue I think I am the only one experiencing, but none of the proxies spawn bots anymore. Don't know how to solve that one yet or just might be my issue. I'll update this when I figured it out.

**Comment by ghost** [comment]
agarbots.net. agarbot.ovh, agarhelper.com have all disabled the ability to buy bots, looks like bots (for the most part) have been patched! AHAHAHAHAHAHHA.

**Comment by WJKH** [comment]
Good news :+1: 

Everyone was abusing of FB bots and the result was unplayable game.
About proxies, I believe they changed from 5 clients per IP to 3 per IP.

4 says: Connected, spawning
4 says: Disconnected from server, bye!
5 says: Connected, spawning
5 says: Disconnected from server, bye!

Anyway, 10 mass bots are very useful if these can follow mouse, eject mass and split them.
Also if bots will avoid opponents you will get enough bots to grow fast.

**Comment by KingMatt123** [comment]
Guys agarbot.ovh have bypassed the limitations of Facebook logins or something, they have big bots.

**Comment by SnowyTube** [comment]
Yep i saw the bots were 30 mass

**Comment by DaAwesomeRazor** [comment]
LOl agarbots.ovh just got a unch of facebook accoints. I dont think they bypassed anytihng

**Comment by WJKH** [comment]
Alright, they used different accounts.
If you want setup yours just get 10 FB accounts and level up running some bot 24/7

**Comment by ModeratorProxy** [comment]
I am a Moderator at www.agarbot.ovh and I can tell you that we did not use 1000 accounts we where just very smart and used our current business for the better :)

**Comment by ModeratorProxy** [comment]
and we never used 5 bots per IP so it did not have an effect on us whatsoever

**Comment by makandz** [comment]
@WJKH Is right. Facebook accounts are limited to 1 connection per account. So they most likely have a couple dozen accounts.

**Comment by davidmann4** [comment]
Q_Q nothing to fix here
