### ISSUE TITLE
Bots work :) Good bots.

### ISSUE THREAD

**Issue by ZfsrGhS953** [davidmann4/ogar-feeder-bot#595]
Bots: http://agarinfinity.com/
Please note that Agar Infinity emulates a agar.io page for each bot, because the owner couldn't decrypt agario.core.js. Because of this, a strong PC is needed.
Recommended settings:
Amount of bots: 35
Browser: Chrome 64-bit
Proxy: Betternet VPN
CPU: i7-4770 or higher
RAM: 8GB or higher

How to discover more bots?
For this, need to debug agario.core.js.
If you watch carefully, come across this piece of code, it is responsible for key generation of outgoing messages: Mouse Eject Split Spawn Spectate Q

``` javascript
function jc(b, d, e) {
            b = b | 0;
            d = d | 0;
            e = e | 0;
            var f = 0
              , g = 0
              , h = 0
              , j = 0;
            j = i;
            i = i + 16 | 0;
            h = j;
            f = c[b + 20 >> 2] | 0;
            if (!f) {
                i = j;
                return
            }
            if ((a[b + 36 >> 0] | 0) != 0 ? (e | 0) > 0 & (a[13884] | 0) != 0 : 0) {
                g = lg((e | 0) > -1 ? e : -1) | 0;
                qr(g | 0, d | 0, e | 0) | 0;
                b = b + 40 | 0;
                d = c[b >> 2] | 0;
                c[h >> 2] = d;
                d = _(d, 1540483477) | 0;
                d = (_(d >>> 24 ^ d, 1540483477) | 0) ^ 114296087;
                d = _(d >>> 13 ^ d, 1540483477) | 0;
                c[b >> 2] = d >>> 15 ^ d;
                if (e) {
                    d = 0;
                    do {
                        b = g + d | 0;
                        a[b >> 0] = a[b >> 0] ^ a[h + (d & 3) >> 0];
                        d = d + 1 | 0
                    } while ((d | 0) != (e | 0))
                }
                jb(9, c[f >> 2] | 0, g | 0, e | 0) | 0;
                ng(g);
                i = j;
                return
            }
            jb(9, c[f >> 2] | 0, d | 0, e | 0) | 0;
            i = j;
            return
        }
```

But it's hard to analyse such a big encrypted code. So, I emphasise this part:

``` javascript
d = c[b >> 2] | 0;
                c[h >> 2] = d;
                d = _(d, 1540483477) | 0;
                d = (_(d >>> 24 ^ d, 1540483477) | 0) ^ 114296087;
                d = _(d >>> 13 ^ d, 1540483477) | 0;
                c[b >> 2] = d >>> 15 ^ d;
```

What happened? d is loaded from a memory location. The d is then stored in another memory location. Then modified the key with bit shifts, multiplications and XORs (xorshift random number algorithm). Then, it is applied to the message in this part of code:

``` javascript
if (e) {
                    d = 0;
                    do {
                        b = g + d | 0;
                        a[b >> 0] = a[b >> 0] ^ a[h + (d & 3) >> 0];
                        d = d + 1 | 0
                    } while ((d | 0) != (e | 0))
                }
```

To be continued...

**Comment by agariotips** [comment]
http://192.99.58.70/deobfuscate/ < very good deobfuscator (if needed)

**Comment by ZfsrGhS953** [comment]
That's good. However, asm.js isn't on deobfuscation list. I need a deobfuscator that can convert asm.js back into minified javascript.

**Comment by fayizan** [comment]
@ZfsrGhS953 this guy claim he decrypted core.js,look at his github https://github.com/G047/Agar.io-Bots

**Comment by nuclearc** [comment]
@ZfsrGhS953 i'm working on my client too. I can encrypt/decrypt packets as well , but i have big problem.
Problem is about packet 113. Client needs to response to it. Its generated from 112 that server sent and 255(init 1). Maybe you have some info about that?

**Comment by ZfsrGhS953** [comment]
Starting value is 673720360. I'm also developing my own bots for agar.io clones(like Agar-API.tk). Currently, I'm trying to implement coordinate scrambling, so that the bots can work on agarlist.com.

**Comment by yario-o** [comment]
Lol nuclearc said : It isn't good to put starting value here and you did it

**Comment by ZfsrGhS953** [comment]
He said that HE doesn't want to put the id here, he didn't tell ME anything about it.

**Comment by nuclearc** [comment]
then how is my server working with protocol v9? starting value = 0x28282828 ^ ....

**Comment by yario-o** [comment]
Oh okay

**Comment by ZfsrGhS953** [comment]
Because everything's right! 673720360 is 0x28282828 in hex.

**Comment by nuclearc** [comment]
ye but its xored with init1

**Comment by MasonBurdette** [comment]
@nuclearc @ZfsrGhS953 
so would you XOR this for the decryption : 
Packet 255 ^ Packet 241

I suppose the key(s) reset everytime Packet 241 is sent.  Also, when/how often is 241 sent to client?

**Comment by nuclearc** [comment]
no key is reset on packet 18

**Comment by MasonBurdette** [comment]
@nuclearc you're friends with razor and sonic, right? add me on skype 'masonburdette@outlook.com'.

**Comment by NuclearC** [comment]
cant find you :/ can you add me? my skype is nuclear.agar

**Comment by David1ali12** [comment]
I just saw Mass bots today , did you guys made it ?

**Comment by MasonBurdette** [comment]
@David1ali12 those are Chither bots. I just finished my bots, but they are 10 mass. I have the byte converter, but I haven't gotten enough accounts.

**Comment by ItzLevvie** [comment]
"@ZfsrGhS953 this guy claim he decrypted core.js,look at his github https://github.com/G047/Agar.io-Bots" - @fayizan 

That's related to SC bots not a decrypted agario.core.js

**Comment by ImHITMan** [comment]
ItzLevvie He might have, I know him. His original name was DrGoat. if the decrypted version is written in CSS then it is right.

**Comment by ItzLevvie** [comment]
"ItzLevvie He might have, I know him. His original name was DrGoat. if the decrypted version is written in CSS then it is right."

Ah, okay. I didn't know that he created a new account lol
