### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Andrews54757** [davidmann4/ogar-feeder-bot#601]
Hello, recently I have developing a project called OpenAgar. I have come here to request one thing from @davidmann4 . OpenAgar uses a special key system like agar.io does to protect its servers from bots. @davidmann4, Please don't update your bots to work with OpenAgar. Even though OpenAgar uses socket.io instead of ws, please don't do it. You may update your bots so it works with open agar when the security feature is disabled, but please do not try to cheat the security feature. We are trying to build a game with honest players. Thank you.

**Comment by davidmann4** [comment]
ok cool
