### ISSUE TITLE
davidmann4 i need your help.

### ISSUE THREAD

**Issue by Tatitooo** [davidmann4/ogar-feeder-bot#603]
I know that you left this project already, i want to do anything but i dont know how where can i contact you? i leave you my skype and discord here
Skype: itztati14 Or iTzTati
Discord: Tati#2487
@davidmann4

**Comment by Shair17** [comment]
this project is dead

**Comment by Tatitooo** [comment]
I know but... I made a Coords system to this project but i got a problem, i just want to talk whit Davidmann4

**Comment by davidmann4** [comment]
sup?

**Comment by davidmann4** [comment]
added you - my skype is david.mann.rsa

**Comment by Tatitooo** [comment]
Thanks.

**Comment by Tatitooo** [comment]
@davidmann4 , i actually send you Friend Request, i didnt got yours, if you can discord is more stable and we can talk easier, Thanks You Tati#2487

**Comment by davidmann4** [comment]
ok

**Comment by Tatitooo** [comment]
^ Not a issue
