### ISSUE TITLE
Getting Error when trying to run feeder.js

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#61]
Here is my error:
![prob](https://cloud.githubusercontent.com/assets/15712937/12534369/b7eab8be-c2aa-11e5-9967-3e8eebc7eeec.png)

**Comment by KingMatt123** [comment]
Line 198 of feeder.js error

**Comment by ghost** [comment]
just disable safeMoveTo in the config file, it doesn't work yet anyway.

**Comment by KingMatt123** [comment]
I fixed it with removing the 2 {} brackets on line 198, working now but i cant connect to minimap server

**Comment by davidmann4** [comment]
which node version ?

**Comment by KingMatt123** [comment]
Fixed\* Just in your code David remove the two brackets {} on line 198 of feeder.js

**Comment by davidmann4** [comment]
which node version ?

**Comment by davidmann4** [comment]
tutorial will be available her: https://github.com/davidmann4/agario-feeder-bot/wiki

**Comment by WJKH** [comment]
I have the same issue.

$ node -v
v0.12.9

I was using this version because we was running minimap server.
Which version you are using now?

**Comment by KingMatt123** [comment]
I use node 0.12.9 as well. I just install the node version manager (nvm) and change it to 0.12.9. But it's fixed now if you read through this issue's comments.
