### ISSUE TITLE
AGAR.IO PROTOCOL

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#613]
Hi ! I am lefela4.
I fixed the hole agar.io procole + FB !
I have a question for you. I have problem whit map offset for the userscript or the feeder.
My bots go in corner or idk where. 
They follow my mouse in their position.
I do : 
		var playerRealX = (window.player.x - m.minx) / length_x;
		
		var playerRealY = (window.player.y - m.miny) / length_y;

like you say in the minimap project

var botRealX = (valid_player_pos["x"] * bot.client.length_x) + bot.client.min_x;
		
var botRealY = (valid_player_pos["y"] * bot.client.length_y) + bot.client.min_y;

in the feeder. THX !

**Comment by henopied** [comment]
Well, you must first look at the demodulated modulator modulation module, then you can apply the fn change onto the x, y euclidean plane.

**Comment by ghost** [comment]
lol

**Comment by ghost** [comment]
u are wrong !Cz u alway say thing have no sence. I figured out the protocol whitout what u said so no.

**Comment by MrSonicMaster** [comment]
So basically you need to overmodulate the reverse d0x script from DrBoat and DrGot and then you can reverse the polarity of the reverse script handler on agar.io and it will reactivate the demodulation processor thread causing the X and Y to become overmodulated, revealing their real value. Thats how 2 fix move

**Comment by ghost** [comment]
tf ?

**Comment by ghost** [comment]
No, u hate me lol.

**Comment by MrSonicMaster** [comment]
No that's 100%noscamtotallylegit the way to do it

**Comment by ghost** [comment]
lol. He is funny no?

**Comment by MrSonicMaster** [comment]
nolie

**Comment by ghost** [comment]
hahaha,

**Comment by MrSonicMaster** [comment]
idk y u say hahahha becuz thats h0w 2get real XY value

**Comment by Optimusprimeagario** [comment]
just close this shit

**Comment by MrSonicMaster** [comment]
L

**Comment by MrSonicMaster** [comment]
L
L
L
L
L
L
L
L
lefela you are a good coder

**Comment by Optimusprimeagario** [comment]
L L L L

**Comment by MrSonicMaster** [comment]
:+1: :-1: :100: :1234:

**Comment by ghost** [comment]
lol

**Comment by ghost** [comment]
it dead

**Comment by NuclearC** [comment]
biiitch

**Comment by NuclearC** [comment]
overmodulated modulator modulation hacksbuffer xored lefela with minions.ovh's ass

**Comment by StrikerJS** [comment]
and reversed md6 hash xored with byte 0x03 of the hack buffer bytelength

**Comment by KillEmUp** [comment]
just build lol

**Comment by ghost** [comment]
kids are here to build a wall.

**Comment by Lemons1337** [comment]
Have you demodulated the protobuf init key with the reversed synthetic obstructor?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
WE MUST TO BUILD A WALL.
