### ISSUE TITLE
Userscript issues

### ISSUE THREAD

**Issue by WJKH** [davidmann4/ogar-feeder-bot#68]
I was testing last version and it's working much better, those new features are great.
Good job, well done :+1: 

I have found some issues while running the userscript:
- FB login isn't working
- Sometimes I see a blank page flashing while playing

Console output:

```
Uncaught TypeError: c.MC.updateServerVersion is not a function
Uncaught TypeError: c.MC.setProfilePicture is not a function
Uncaught TypeError: c.MC.doLoginWithFB is not a function
```

Also have some issue with feeder.js https://github.com/davidmann4/agario-feeder-bot/issues/61

**Comment by KingMatt123** [comment]
Hi, all you have to do to fix this issue it to edit line 198 of feeder.js by removing the 2 brackets {}.

**Comment by iNewLegend** [comment]
AmazingGamerBoy 10x!

**Comment by KingMatt123** [comment]
I meant not the main issue, but the #61 one

**Comment by WJKH** [comment]
I already read your comment AmazingGamerBoy and I'm using your fix till now.
Just refer to it because davidmann4 doesn't updated the code and he asked the node version we are running.

**Comment by davidmann4** [comment]
@WJKH because if you run the newest node version it should run with this code. ( #61 )

**Comment by davidmann4** [comment]
works now
