### ISSUE TITLE
Userscript collision any other script 

### ISSUE THREAD

**Issue by zeliad-papa** [davidmann4/ogar-feeder-bot#72]
I can not run UserScript feeder If I use AgarPlus or any other script that gives me Sample Zoom

Has anyone checked that?

**Comment by ghost** [comment]
most userscripts cannot be ran in unison.

**Comment by zeliad-papa** [comment]
@davidmann4 
Maybe add a  userscript:
-FAST SLIP
-FAST FOOD
-ZOOM
-OPTION TO SELECT MOUSE OR BOT CONTROL

**Comment by WJKH** [comment]
Fast mass ejector below, taken from another script.

```
(function() {
    var amount = 7;
    var duration = 50; //ms

    var overwriting = function(evt) {
        if (evt.keyCode === 69) { // KEY_E
            for (var i = 0; i < amount; ++i) {
                setTimeout(function() {
                    window.onkeydown({keyCode: 87}); // KEY_W
                    window.onkeyup({keyCode: 87});
                }, i * duration);
            }
        }
    };

    window.addEventListener('keydown', overwriting);
})();
```

Zoom is working.
Option to select mouse or bot control? What do you mean?

Now I miss the minimap there, I don't know where I'm going.

**Comment by zeliad-papa** [comment]
I do not know any JS
You can edit it on Github please its help for all

Option to select mouse or bot control? What do you mean? 
i can select who control loction mass come or bot or mosue

**Comment by WJKH** [comment]
Just copy/paste the code below the line 78.

Do you mean like it was before?
Bots come directly without following mouse?

**Comment by davidmann4** [comment]
works now?

**Comment by WJKH** [comment]
The userscript is working right now.
Anyway like others scripts doesn't allow to use both scripts together.

I will check if the minimap userscript could work with the feeder userscript, just miss the map feature there.

**Comment by WJKH** [comment]
The minimap script is working with feeder bots script :+1:
