### ISSUE TITLE
User-Agent error

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#73]
I get a error when running node feeder.js in node. Node v5.50
https://gyazo.com/4b9120ef194414044a9e0ede3c2f2e5c

**Comment by davidmann4** [comment]
update the agario-bot

**Comment by Petterholm** [comment]
I have done it

Den mandag 25. januar 2016 skrev David Mann notifications@github.com
følgende:

**Comment by davidmann4** [comment]
this one https://github.com/pulviscriptor/agario-client

**Comment by Petterholm** [comment]
i got alot of errors when installing but in the node_modules folder it is a folder named agario-client but it didnt work

**Comment by Petterholm** [comment]
what can i do?

**Comment by davidmann4** [comment]
jsut do the following:
npm install agario-client

**Comment by Petterholm** [comment]
i have done it

**Comment by Petterholm** [comment]
But i still get error

**Comment by Petterholm** [comment]
https://gyazo.com/db9a1975db0ecf12c54ec2238d8969b1

**Comment by davidmann4** [comment]
please open an issue in the agario-client repo if you can not build the newest version
