### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by juliopeyrot** [davidmann4/ogar-feeder-bot#76]
can u make a vid on how to download

**Comment by ZeroxYT** [comment]
they can say they will, but they wont. i asked 1-2 weeks ago... still nothing

**Comment by makandz** [comment]
Well it's not at the stake of the developer to do this. People can make videos if they want or not, honestly this isn't something that anyone should just be using. It requires lot's of knowledge with basic Node.js. If you need a video to understand how to use it if the script is too difficult for you to use, this isn't the right script.

@davidmann4 Close this as it isn't an issue with the script itself.
