### ISSUE TITLE
why i get this error?

### ISSUE THREAD

**Issue by Muszek1996** [davidmann4/ogar-feeder-bot#77]
XMLHttpRequest cannot load http://37.187.163.132:1502/socket.io/?EIO=3&transport=polling&t=L9wbZGd. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://agar.io' is therefore not allowed access. The response had HTTP status code 400.
VM20878:6 GET http://37.187.163.132:1502/socket.io/?EIO=3&transport=polling&t=L9wbakN

**Comment by davidmann4** [comment]
hmm interesting issue - which browser do you use?

**Comment by davidmann4** [comment]
dows it work now?
