### ISSUE TITLE
always get this error

### ISSUE THREAD

**Issue by mbm3** [davidmann4/ogar-feeder-bot#78]
Error: ENOENT: no such file or directory, open 'proxy.txt'

ive renamed it to proxy.txt, and made sure it matched it the config.js.
im running on a 2015 macbook air.

**Comment by auxo-git** [comment]
That means your proxy.txt is in the wrong location

**Comment by davidmann4** [comment]
rename proxy.sample.txt to proxy.txt

**Comment by mbm3** [comment]
i did...

**Comment by davidmann4** [comment]
put in the whole path

**Comment by mbm3** [comment]
ok

**Comment by mbm3** [comment]
OMG THANKS IT WORKED!!!
