### ISSUE TITLE
Error: Cannot find module 'agario-client'

### ISSUE THREAD

**Issue by jeanhugues** [davidmann4/ogar-feeder-bot#80]
Hello,

I try to run the script. I followed all the steps.

I wanted to know if we needed the agario-client module?

When launching the  "node feeder.js", I get the following error: "Error: Can not find module agario-customer"

Thanks for your help.

**Comment by zeliad-papa** [comment]
npm install agario-client

**Comment by jeanhugues** [comment]
Thank you yairnet.

I miss a lot of node modules; you have a tip to avoid installing them one by one?
