### ISSUE TITLE
Does the script joins automatically my game?

### ISSUE THREAD

**Issue by Octolus** [davidmann4/ogar-feeder-bot#84]
hi, i want to join a public agar server and use the scripts..

the config asks for server ip, isnt this updated automatically via the user script?

**Comment by davidmann4** [comment]
yes, ip is set automatically - please do not use on public server

**Comment by Octolus** [comment]
well on my "own" server

[root@agar agario-feeder-bot-master]# npm install package.json
npm ERR! not a package /root/tmp/npm-30184/1453936351786-0.9111451699864119/tmp.tgz
npm http GET https://registry.npmjs.org/package.json
npm http 304 https://registry.npmjs.org/package.json

**Comment by Octolus** [comment]
@davidmann4  dude, what am i supposed to do with the config then? idk what i should put, it asks for ip.... .

**Comment by Octolus** [comment]
and what are "install all the modules"..

**Comment by davidmann4** [comment]
ip setting is not used at all - it is a bug

npm install package.json
