### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by Petterholm** [davidmann4/ogar-feeder-bot#89]
cant connect to facebook when using the extension and where to find facebook auth?

**Comment by Petterholm** [comment]
and how to connect bots to facebook=

**Comment by davidmann4** [comment]
works for me - do oyu use the newest version?

**Comment by Petterholm** [comment]
I dont use the newest version because it doesnt work

**Comment by WJKH** [comment]
First, FB auth is working fine.
Second, you can't connect more than one client per account.

If you want connect multiple accounts you will need modify the feeder code.

**Comment by Petterholm** [comment]
Ok but the newest version of the user client doesnt work

**Comment by Petterholm** [comment]
When i install the newest version with tampermonkey it doesnt show my client id

**Comment by Petterholm** [comment]
i managed to connect to facebook but i have another problem 
https://gyazo.com/ed09eb7b27d4bfb15452e8c3f9a3dd61

**Comment by hamido12** [comment]
this my fb https://www.facebook.com/drxx30 add me bro i need

**Comment by KingMatt123** [comment]
Your agar page doesnt need to show u the id, when u connect to the server it should say your id there which u can then copy into the config.js

**Comment by Petterholm** [comment]
When i use the newest version and i connect to a server and play it doesnt show anything

Sendt fra min iPad

**Comment by davidmann4** [comment]
which browser ?
