### ISSUE TITLE
Make bots split if they have to much mass before they hit the player

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#9]
Sometimes a fed bot is chasing you, would be nice if the bot would be smart enough to split feed you.

**Comment by custoso** [comment]
if distance is less than x*radius of master cell (or if coordinates of master-cell are close to the coordinates of the bot), and for i; in each bot's bot.mass is more than 50 mass, bot.split();

Coordinates way:
coordinates mastercell = (2500,2500)
coordinates bot cell = (2500 +- 500, 2500+-500)

var distance_bots = (bots.x,bots.y);
var distance_master = (master.x,master.y);

So if distance_bots is in a radius of about 250 in coordinates from the master cell, split.

 if (distance_master == distance_bots(master.x+500,master.y+500) or distance_master == distance_bots(master.x+500,master.y-500) or distance_master == distance_bots(master.x-500,master.y+500) or distance_master == distance_bots(master.x-500,master.y-500);

![splitcalculations](https://cloud.githubusercontent.com/assets/16456554/12262952/b5ef2744-b92b-11e5-8ac8-74150ab82d94.png)

**Comment by davidmann4** [comment]
it is even easier:

``` javascript
 getDistanceBetweenBalls: function(ball_1, ball_2) {
        return Math.sqrt( Math.pow( ball_1.x - ball_2.x, 2) + Math.pow( ball_2.y - ball_1.y, 2) );
    },
```

**Comment by WJKH** [comment]
I believe it's better to implement something like https://github.com/davidmann4/agario-feeder-bot/issues/12 and https://github.com/davidmann4/agario-feeder-bot/issues/13 then you will get full control of bots.

**Comment by davidmann4** [comment]
yeah I think it is the most common way to do it :)

would need a own userscript + server - currently we piggyback on the minimap userscript:
https://github.com/dimotsai/agar-mini-map

**Comment by davidmann4** [comment]
if you have good AI > player controlled

most of the scripts ony provide macro managment capabilities

**Comment by WJKH** [comment]
Well, minimap script works fine with bots as far as I have tested and you have minimap feature :)
Anyway there're some others scripts for bots that could be used, just need adapt server code to work and use some or all of the script features.

**Comment by davidmann4** [comment]
done
