### ISSUE TITLE
npm install Error

### ISSUE THREAD

**Issue by mhchen-UA** [davidmann4/ogar-feeder-bot#96]
So when i did `npm install` on node.js command prompt after I git cloned the repo, It gave out a list of errors and said 

> Failed at the msgpack@1.0.2 install script "node-gyp rebuild".

Is this supposed to happen? I saw the node_modules files with a list of other files, but none of them are config.js, where I was supposed to copy config.sample.js     I'm using windows 10 btw, If this issue only happens with windows 10 then I'll download virtualbox and use mac.

**Comment by davidmann4** [comment]
funny its not needed at all
guess you can remvoe it from the package.json

**Comment by mhchen-UA** [comment]
Thanks man!
