### ISSUE TITLE
Bots don't split or feed on command with new userscript

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#97]
My bots don't split or feed when I press E and R. It worked with the script that used to flash, but with the new one it doesn't.

**Comment by KingMatt123** [comment]
Sorry it works now :)

**Comment by mhchen-UA** [comment]
Are you using windows or mac? Does this not work for windows? cuz it gave me errors when I npm install the package.json

**Comment by KingMatt123** [comment]
Mark PM me on skype, I can help
