### ISSUE TITLE
Low quality SOCKS crashing agario-client

### ISSUE THREAD

**Issue by pulviscriptor** [davidmann4/ogar-feeder-bot#98]
Hi.
User of `agario-feeder-bot` reported me crashes https://github.com/pulviscriptor/agario-client/issues/73
There is problem in SOCKS, some of them sends random data, you can see investigation here https://github.com/pulviscriptor/agario-client/issues/56#issuecomment-171772427
*It can be not SOCKS, but some other problem, but i think it is SOCKS
I made `on.packetError` event for that. You can see how to use it in [readme](https://github.com/pulviscriptor/agario-client/blob/master/README.md)
Also there is crash in `ws` library, you can see my report here https://github.com/websockets/ws/issues/669 
So until official fix users may want to fix their `ws` too.

**Comment by WJKH** [comment]
Feeder bot doesn't support socks yet, only proxy.

**Comment by pulviscriptor** [comment]
@WJKH 
Oh, okay, then i will ask packet from user and we will see if proxy causing same packet problems as SOCKS or there is agario-client issue.
I will report results here.

**Comment by makandz** [comment]
The bot was updated to accept SOCKS now :)

@davidmann4

**Comment by pulviscriptor** [comment]
Since i did not received any answer from @Petterholm i will close this issue.
