### ISSUE TITLE
npm install Error (2)

### ISSUE THREAD

**Issue by mhchen-UA** [davidmann4/ogar-feeder-bot#99]
So from #96, I deleted the msgpack but now the sleep@3.0.0 is giving me an error as well. Is this needed as well or not?

**Comment by davidmann4** [comment]
nope not needed

**Comment by mhchen-UA** [comment]
Thanks man

**Comment by mhchen-UA** [comment]
Well actually, the npm install worked fine. So I deleted the msgpack and sleep from package.json.  Now  what exactly is supposed to happen after I installed agario-feeder-bot into tampermonkey. I could zoom out further, but I don't see any other interfaces appearing. 

Maybe because I didn't 

> copy config.sample.js to config.js and adjust values
> copy proxy.sample.txt to proxy.txt and adjust values

I don't see proxy.txt or config.js in the agario-feeder-bot folder, or the node_modules folder

**Comment by WJKH** [comment]
You need rename both files, get your ID then run server and feeder.

**Comment by mhchen-UA** [comment]
Thank you so much @WJKH

**Comment by mhchen-UA** [comment]
wait @WJKH Where do I use the run command in? It's not working in node.js command prompt

**Comment by mhchen-UA** [comment]
or were you supposed to type  `node feeder` and `cd server` then `node server.js`  because I had an error when I did node feeder. 
`Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Michael Chen\Documents\GitHub\agario-feeder-bot\feeder.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`

**Comment by mhchen-UA** [comment]
Actually. could you elaborate on install "all" libs with npm. Like could you list out the file names I have to do npm install on

**Comment by mhchen-UA** [comment]
Actually, I just renamed the files to their appropriate name. So I got it (Woohoo). Now the next problem is... I think the userscript for chrome.

On my command prompt, it says:

> agario-feeder-bot started! Join a game in Chrome with the Userscript installed.
> startup
> server-booted-up

So now the only difference I see in agar.io is that I can zoom out further. I don't have any interfaces or bots. is it because of errors in the javascipt coding? It seems to be missing a lot of semicolons if you ask me.

**Comment by WJKH** [comment]
Run the server, then run the feeder.
Check your browser console or server console to get your ID, put it in config file, refresh browser.

If you can't get bots then check console again.

**Comment by mhchen-UA** [comment]
Do you mean the client_uuid?
I change that into config file/

**Comment by mhchen-UA** [comment]
okay so when I ran the server with `node server`  It said it's starting the server, but I can't type anything into my command prompt after that. So I couldn't run the feeder.

**Comment by WJKH** [comment]
Run feeder in another console

**Comment by mhchen-UA** [comment]
thanks bruh

**Comment by mhchen-UA** [comment]
@WJKH  Actually it's still not working. I'm running both feeder and server on 2 command prompts. But my agar stays the same. I changed the id from the client_UUID which is 4 charaacters into the config file. And I even copy and pasted the ws:\ code into the config file. I'll record a video for you to show you what I'm doing. Can you tell me what i did wrong?

**Comment by mhchen-UA** [comment]
https://youtu.be/uhSBHgGOsJ8

**Comment by WJKH** [comment]
Feeder server isn't Agar.io server, you need put there the IP of your feeder server.
config.feederServer = YOUR_IP
If you run it locally, 127.0.0.1

Also change the IP in the userscript...
var socket = io.connect('ws://127.0.0.1:8081');

**Comment by davidmann4** [comment]
can I close this thread?

**Comment by mhchen-UA** [comment]
well thanks to @WJKH WJKH, yes!
